### ISSUE TITLE
Training Link/Data

### ISSUE THREAD

**Issue by mook-worldbank** [AIFDR/inasafe#1025]
Two quick comments regarding the inasafe training:

1. The Link to the "Data" on the "Socialisation" page (http://inasafe.org/en/training/socialisation/index.html) is broken. 

2. In the "Insafe in More Detail" page (http://inasafe.org/en/training/socialisation/inasafe_in_more_detail.html), section on "Flood Footprint in InaSAFE", I cannot find the data source "flood_osm_bpbd18113_jakarta.shp" in the inasafe data repository.

**Comment by mach0** [comment]
@Charlotte-Morgan I think this can be closed as there is no reply since July .. 
Think (hope) everything was found.
