### ISSUE TITLE
Wizard should write allow_resampling = False for population density exposure

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1078]
# Problem

In reference to issue #1008 it is useful to be able to prevent resampling of exposure layers in certain situations. For example where the exposure represents population density, it should not be resampled.

# Proposed solution

We have already added a flag to the dock.py to prevent using the hazard resolution if the exposure layer has the keyword **allow_resampling** set to false. It would be good to make the wizard automatically add this keyword in the case that we have **exposure** with unit **density**.

**To think about:** Can we drive this behaviour from metadata? Maybe @ismailsunni can update the metadata schema to accommodate this?

# Expected outcome

Density data should have the ``allow_resampling`` keyword set to try.

# CC

@Charlotte-Morgan @assefay @manombawa

**Comment by akbargumbira** [comment]
Hi @borysiasty, I guess you need to rollback the commit above for this
