### ISSUE TITLE
Some Issues on Flood OSM Building Impact Function

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1083]
# Problem
I used standard Jakarta scenario from data.inasafe.org. There are some issues that concern me:

1. The clipped layer (get it from the temp folder of inasafe) is shifted about ~10m for each pixel.
![screenshot from 2014-06-12 16 57 20](https://cloud.githubusercontent.com/assets/992519/3256413/02467ae8-f218-11e3-9f19-8f9777cd03e1.png)

2. There are some cases that the interpolation behaves a bit strange. I read the code, as the default it uses neighbor interpolation pixel value after the building gets converted to centroid. See this screenshot below:
![screenshot from 2014-06-12 17 22 06](https://cloud.githubusercontent.com/assets/992519/3256639/72321d46-f21b-11e3-97d8-7cd7f144c68d.png)
The left pixel of those 2 buildings has value 0.93, the right pixel next to them is 0.79. They have the same top and bottom neighbour pixel's value. From that, shouldn't the left one be categorized as red and the right one as green (not the other way around)?

# CC
@Charlotte-Morgan @timlinux

**Comment by akbargumbira** [comment]
I think the shifting intermediate layer was interfering the interpolation. I am satisfied with the interpolation result. Closing this

**Comment by timlinux** [comment]
Example of flood impact in new V4 architecture

![2017-02-27 16_42_55-qgis 2 14 11-essen - dki_jakarta](https://cloud.githubusercontent.com/assets/178003/23365451/d4ede67e-fd0b-11e6-9de2-14a8f03ad48b.png)
