### ISSUE TITLE
Issues in Parameter of Impact Function

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1099]
# Problem
Right now we declare one parameter for each IF. But, in fact we don't need some parameters for some cases in that IF. For example FloodBuildingImpactFunction, we declare the parameter as:
 ```
parameters = OrderedDict([
        ('threshold [m]', 1.0),
        ('postprocessors', OrderedDict([('BuildingType', {'on': True})]))
    ])
```
In fact, for vector data we don't use threshold to do the analysis. Since it will be shown to user in IF Option, the user may interpret that they need to fill the threshold.

Another case is for VolcanoBuildingImpact. We declare the parameter as:
```
parameters = OrderedDict([
        ('distances [km]', [3, 5, 10])])
```
While for polygon data (which represents the KRB area), we also don' t use this parameter.

# Proposed Solution
Define the parameters based on type of the input or separate the IF based on hazard
# CC
@timlinux @Charlotte-Morgan @cchristelis @ismailsunni

**Comment by akbargumbira** [comment]
Finally other people noticed this (@Charlotte-Morgan) :)
To track related issues:
- https://github.com/AIFDR/inasafe/issues/1666
- https://github.com/AIFDR/inasafe/issues/1671

I will ensure this is fixed when we review all the IFs!

**Comment by timlinux** [comment]
Agreed. Note on the roadmap that we have plans to use the new style parameters UI for IF parameters. We can / should add a parameter constraint that indicates which hazard layer types and which exposure layer types are supported for this.

Also in the case of flood polygons it would probably be nice to support thresholds where a polygon stores flood depth, but in that case we would need need some more sophisticated constraint mechanism e.g. ``layer_type==polygon and depth_attribute is not null``.

**Comment by akbargumbira** [comment]
This is resolved. I am closing this
