### ISSUE TITLE
Add the unit of the minimum needs in the configuration

### ISSUE THREAD

**Issue by vdeparday** [AIFDR/inasafe#1155]
In the impact function configuration option, in the minimum needs tab, there is not unit mentioned, it would be good to say if it is per day or per week and if it is per individual or per family directly within the dialog. The questions came up during a workshop.

![image](https://cloud.githubusercontent.com/assets/1036189/3725019/3d723ca2-1684-11e4-91eb-af8172b4f724.png)

**Comment by akbargumbira** [comment]
I am closing this now as we already have it
