### ISSUE TITLE
Flood impact function (not experimental) is not given the correct results

### ISSUE THREAD

**Issue by vdeparday** [AIFDR/inasafe#1157]
QGIS 2.4 on Mac (Kynchaos), InaSAFE 2.1 from repo

See the screenshots below. Running the Flood impact function (regular one), some buildings are considered are not inundated when they are clearly right in the middle of the flood zone.

Could that be a projection issue? Is there a requirement for projection in InaSAFE or does it do on the fly?
Could it be the validity of the hazard layer? As it is only one bug multi-polygon?

The flood (experimental) function does not work with the new wizard see other bug #1158 

Layers used:
Hazard data from here: http://www.haitidata.org/layers/cnigs.spatialdata:hti_hazardhydrology_rareflood_westdepartment_nathat_polygon_052
buildings from OSM with InaSAFE downloader

![image](https://cloud.githubusercontent.com/assets/1036189/3725833/2b0414ec-168d-11e4-984f-9a8b6326e9ee.png)

![image](https://cloud.githubusercontent.com/assets/1036189/3725852/588160aa-168d-11e4-8616-89a7f18d31bc.png)

**Comment by akbargumbira** [comment]
We removed this IF for 3.1 and just keep the QGIS style IF. I am closing this then
