### ISSUE TITLE
Python error on Mac OS when running flood IF for affected population

### ISSUE THREAD

**Issue by emirhartato** [AIFDR/inasafe#1212]
# Problem
There is python error when running InaSAFE using food IF to calculate affected population on Mac OS.

# System
MacBook Pro OS X Lion
Ram 4GB
QGIS 2.4 / InaSAFE 2.1.0 from QGIS Repo

# Proposed Solution
At first, I thought it's plugin problem, so I did uninstall and re-install the plugin but it still showing the same error. But, when the user tried flood IF for affected buildings, it runs pretty well as usual.

# Error Log
Processing started

Please wait - processing may take a while depending on your hardware configuration and the analysis extents and data.

This analysis will calculate the impact of Annual Floods in Lower Shire Wihin 5 Years on Malawi Population 2008 and bullet_list the results aggregated by District .

The following postprocessors will be used:

Gender: Calculates gender related statistics.
Age: Calculates age related statistics.
Minimum needs: Aggregates minimum needs.
Checking available memory

Computed cellsize was None. Memory check currently only works for raster input layers.
Select attribute

Please select which attribute you want to use as ID for the aggregated results

Preparing hazard data

We are resampling and clipping the hazard layer to match the intersection of the exposure layer and the current view extents.

Preparing exposure data

We are resampling and clipping the exposure layer to match the intersection of the hazard layer and the current view extents.

Preparing aggregation layer

We are clipping the aggregation layer to match the intersection of the hazard and exposure layer extents.

Select attribute

Please select which attribute you want to use as ID for the aggregated results

Pre-clipping input data...

Modifying Annual Floods in Lower Shire Wihin 5 Years clipped to avoid intersections with the aggregation layer

Calculating impact

This may take a little while - we are computing the areas that will be impacted by the hazard and writing the result to a new layer.

Problem

The following problem(s) were encountered whilst running the analysis.

ImportError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

An exception occurred when calculating the results. Calculation error encountered:
numpy.core.multiarray failed to import
Diagnostics (click for details)

In file "/Users/sergiomauriciopedrazafernandez/.qgis2/python/plugins/inasafe/safe_qgis/utilities/impact_calculator_thread.py", line 186, in run check_integrity=self._check_integrity)
In file "/Users/sergiomauriciopedrazafernandez/.qgis2/python/plugins/inasafe/safe_qgis/safe_interface.py", line 537, in calculate_safe_impact check_integrity=check_integrity)
In file "/Users/sergiomauriciopedrazafernandez/.qgis2/python/plugins/inasafe/safe/engine/core.py", line 68, in calculate_impact F = impact_function.run(layers)
In file "/Users/sergiomauriciopedrazafernandez/.qgis2/python/plugins/inasafe/safe/impact_functions/inundation/flood_population_evacuation_polygon_hazard.py", line 215, in run hazard_layer, exposure_layer, attribute_name='population')
In file "/Users/sergiomauriciopedrazafernandez/.qgis2/python/plugins/inasafe/safe/engine/interpolation.py", line 149, in assign_hazard_values_to_exposure_data attribute_name=attribute_name)
In file "/Users/sergiomauriciopedrazafernandez/.qgis2/python/plugins/inasafe/safe/engine/interpolation.py", line 352, in interpolate_polygon_raster res = clip_grid_by_polygons(target.get_data(scaling=False),
In file "/Users/sergiomauriciopedrazafernandez/.qgis2/python/plugins/inasafe/safe/storage/raster.py", line 410, in get_data A = self.band.ReadAsArray()
In file "/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages/osgeo/gdal.py", line 1233, in ReadAsArray import gdalnumeric
In file "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 454, in _import mod = _builtin_import(name, globals, locals, fromlist, level)
In file "/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages/osgeo/gdalnumeric.py", line 1, in from gdal_array import *
In file "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 454, in _import mod = _builtin_import(name, globals, locals, fromlist, level)
In file "/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages/osgeo/gdal_array.py", line 25, in _gdal_array = swig_import_helper()
In file "/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages/osgeo/gdal_array.py", line 21, in swig_import_helper _mod = imp.load_module('_gdal_array', fp, pathname, description)

# Data
Sorry I can't upload the population data because it's huge.
I'm using AfriPop: http://www.worldpop.org.uk/data/summary/?contselect=Africa&countselect=Malawi&typeselect=Population

Hazard layer: https://dl.dropboxusercontent.com/u/11990722/q5_atkins_flood_hazard.rar

Aggregation layer: https://dl.dropboxusercontent.com/u/11990722/mw_ta_lowershire.rar (use 'Area' for aggregation column)

cc: @severinmenard

**Comment by timlinux** [comment]
I'm busy downloading the test datasets....

**Comment by timlinux** [comment]
Hi @emirhartato I know you probably long forgot about this ticket now, but just a note to say that I downloaded the test datasets you referenced and ran the scenario on InaSAFE 3.2, QGIS 2.8.3, OS X Yosemite. Everything runs fine for me and I will close this ticket.

![Uploading Screen Shot 2015-09-17 at 14.58.57.png…]()
