### ISSUE TITLE
We need a roadmap for deploying the Function Centric wizard

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1240]
Please consult with @borysiasty and @mbernasocchi to draw up a list of issues covering all tasks that need to be completed to get the function centric wizard into production for InaSAFE 2.2

**Comment by ismailsunni** [comment]
Hi @borysiasty 
Some additional issues and feed back  for the wizard
- [ ] #1467 
- [ ] #1466 
- [ ] #1465 
- [ ] #1453 
- [ ] #1452 

And one more thing, does loading from postGIS work? The `Next` button is not enabled when I chose `postGIS`

**Comment by Charlotte-Morgan** [comment]
Hi @borysiasty & @ismailsunni
Thanks for your work on the wizard. Today is my first day back in the office and I have had a little play without reading all the other comments.
I  have added some IFCW related tickets
- [ ] #1470
- [ ] #1471
- [ ] #1472
- [ ] # 1473

**Comment by ismailsunni** [comment]
Hi @borysiasty 
Just add another obvious issues:

- [ ] #1475 
- [ ] #1476

**Comment by borysiasty** [comment]
And also:
- [ ] #1476

**Comment by Charlotte-Morgan** [comment]
see #1163 for previous feedback and comments on the wizard development

**Comment by ismailsunni** [comment]
Another one:
- [ ] #1548  [IFCW] Add Keywords Continouous or Classified For Raster

**Comment by ismailsunni** [comment]
I will close this ticket since we have the wizard works now :)

Some unfinished issue are included in another new ticket, see #1578
