### ISSUE TITLE
We need to deploy a geonode instance for hosting InaSAFE data packages

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1241]

**Comment by Charlotte-Morgan** [comment]
The InaSAFE geonode is being designed and developed this week!!
it will be used to share InaSAFE training data and as a catalogue to let people know what hazard data have been developed by technical agencies in Indonesia for use in InaSAFE.

#cc 
@iyan

**Comment by gubuntu** [comment]
testing instance deployed at http://geonode.inasafe.org. 

Geonode and geoserver in one docker container; PostGIS in another container. Geonode 2.4 pre-release (master) on Ubuntu 14.04. 

Still some network issues to resolve.
