### ISSUE TITLE
Bugs on Keywords Editor

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1281]
Problems
------------
I found several bugs on keywords editor.

1. Failed to delete keywords.
    - Open /inasafe_data/hazard/Flood_Current_Depth_Jakarta_geographic.asc
    - Open keywords editor
    - Go to advance tab
    - Remove all keywords
    - Keywords are gone
    - Ok
    - Open the keywords editor for the same layer
    - The previous deleted keywords come again (should it be gone?)

1. Deleted keywords keep showing in the dialog.
    This is for aggregation layer only (as far as I found)
    - Open /inasafe_data/boundaries/kabupaten_jakarta.shp
    - Open keywords editor for this layer
    - Go to advance tab
    - Select aggregation attribute or female ratio attribute or another postprocessor related keywords.
    - Click remove selected
    - The keyword is still there. (should it be gone?)
    - Select all keywords
    - Click remove selected
    - All postprocessor related keywords still there. (should it be gone?)

1. UI error. (I found it twice, but I don't know how to replicate it and forget to take screenshot).
    Both UI for predefined keywords and user defined keywords are shown together.

Solution
-----------
Debug it.

Expected Outcome
-------------------------
The keyword editor should have an expected behavior.

**Comment by lucernae** [comment]
@timlinux Do we prefer to to load from the xml instead of .keywords file always? When I see it in the code, right now we always load from .keywords.

**Comment by ismailsunni** [comment]
@lucernae from the xml. We want to get rid of `.keywords` file as soon as possible
