### ISSUE TITLE
We need to create nightly builds for testers

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1297]

**Comment by Charlotte-Morgan** [comment]
@timlinux - tell her she's dreaming :)

**Comment by timlinux** [comment]
How do you like these apples?:

![repository details_003](https://cloud.githubusercontent.com/assets/178003/9439462/8e4495cc-4a67-11e5-8609-c0b9b57710da.png)

![plugins settings_004](https://cloud.githubusercontent.com/assets/178003/9439464/94cc03c6-4a67-11e5-852a-95883dbd69fc.png)

![plugins installed 42 _005](https://cloud.githubusercontent.com/assets/178003/9439466/99067804-4a67-11e5-828a-f3207872871d.png)

# Some caveats:

* Currently it is set to build hourly - though I still need to see if the builds run successfully each hour
* The version number is not updated with each build - in my last JK trip we had actually discussed the auto builds and concluded that instructing people to grab a copy from GIT would generally be preferred since they have a know trackable version. 
* Since the version number is not updated, you will not receive upgrade notices in the QGIS plugin manager - you should manually remove and reinstall the plugin.

# Usage procedure:

* Click on ``Plugins -> Manage and Install Plugins`` in the plugin manager
* Click on the ``Settings`` tab on the left of the plugin manager
* Ensure that ``Show also experimental plugins`` is checked in the plugin manager settings
* Scroll down on the settings main content area until you see the `Add`` button - then click the add button
* Set the ``Name`` to ``InaSAFE Nightly``
* Set the ``URL`` to ``http://nightly.inasafe.org/plugins.xml`` - leave all other options in their default state
* Click OK
* Click back on the ``All`` tab on the left
* Search for ``InaSAFE`` in the plugin manager
* You should find a plugin called ``InaSAFE-Nightly`` listed
* Select it and then press ``Install Plugin`` or ``Reinstall Plugin`` if you are trying to update it

# Warning:

* Ensure that your git checkout is moved aside from your ``{HOME}/.qgis2/python/plugins`` folder before attempting to install the nightly - otherwiese it will trash anything that was already in ``{HOME}/.qgis2/python/plugins/inasafe``

**Comment by timlinux** [comment]
I also updated the front page of the wiki to include a link with instructions for using the nightly builds:

![selection_006](https://cloud.githubusercontent.com/assets/178003/9439888/40aac332-4a6b-11e5-90bc-fc9598ecf760.png)

And added a page based on the notes above there: https://github.com/AIFDR/inasafe/wiki/Nightly%20Builds
