### ISSUE TITLE
Cannot `Save as` a minimum needs configuration file

### ISSUE THREAD

**Issue by maning** [AIFDR/inasafe#1327]
Error below:
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/maning/.qgis2/python/plugins/inasafe-dev/safe_qgis/tools/global_minimum_needs_configuration.py", line 478, in save_minimum_needs_as
    options=QtGui.QFileDialog.DirectoryOnly)
TypeError: QFileDialog.getSaveFileName(QWidget parent=None, QString caption=QString(), QString directory=QString(), QString filter=QString(), QString selectedFilter=None, QFileDialog.Options options=0): argument 'options' has unexpected type 'FileMode'

Python version:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

QGIS version:
2.6.0-Brighton Brighton, exported

Python path: ['/home/maning/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/maning/.qgis2/python', u'/home/maning/.qgis2/python/plugins', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs/httplib2-0.8-py2.7.egg', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs/requests-2.0.1-py2.7.egg', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs/raven-3.5.1-py2.7.egg', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs/gsconfig-0.6.6-py2.7.egg', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs/gsimporter-0.1-py2.7.egg', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs/nose-1.3.0-py2.7.egg', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs/nose_html-1.1-py2.7.egg', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs/coverage-3.7-py2.7-win32.egg', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/dist-packages/pip-1.5.2-py2.7.egg', '/home/maning/malawi/geonode', '/usr/local/lib/python2.7/dist-packages/pyModis-1.0.0-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', '/home/maning/.qgis2/python/plugins/mmqgis/forms', '/home/maning/.qgis2/python/plugins/MetaSearch/ext-libs', '/home/maning/.qgis2/python/plugins/inasafe-dev', '/home/maning/.qgis2/python/plugins/inasafe-dev/third_party', '/home/maning/.qgis2/python/plugins/opengeo/ext-libs', '/usr/share/qgis/python/plugins/fTools/tools', '~/.qgis/python', '/home/maning/inasafe_dev/inasafe_data_ph']

In addition, reloading the config does not save the previously edited values thus reverting to the original values.

@cchristelis

**Comment by cchristelis** [comment]
I didn't assign this to myself, so it got a little lost in the see of issues.
