### ISSUE TITLE
Legend layout not appearing in QGIS 2.6

### ISSUE THREAD

**Issue by maning** [AIFDR/inasafe#1328]
Running develop branch under with QGIS version: 2.6.0-Brighton Brighton, legend in the pdf output does not appear.  See below:

![screenshot from 2014-11-05 18 40 36](https://cloud.githubusercontent.com/assets/353700/4916476/b986927c-64d9-11e4-9b5f-5d31967308f1.png)

**Comment by akbargumbira** [comment]
Fixed here in develop: https://github.com/AIFDR/inasafe/pull/1485
Fixed here in master: https://github.com/AIFDR/inasafe/pull/1486

Please try it again @maning and if the issue still appears, please reopen this issue. Thanks

**Comment by maning** [comment]
@akbargumbira, great work!  We tested already with latest develop and its working now.
