### ISSUE TITLE
IF Logic: polygon flood impact on people

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1361]
Looking for a few words explaining the way the IF works.
IF assesses people in affected polygons and then reports 1%.
Can anyone explain where the 1% comes from and what the background logic is?

# cc
@vanpuk
@uniomni

**Comment by akbargumbira** [comment]
It comes from the option :) I guess you are asking why we give 1% as the default value?

**Comment by timlinux** [comment]
Yeah the answer to that is lost in project history...

**Comment by Charlotte-Morgan** [comment]
see #1869 
closing this as its covered in the above ticket
