### ISSUE TITLE
ParameterContainer needs to be able to have validation rules

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1405]
# Problem 

When we have a collection of parameters in a parameters list / container, we need to be able to set cross validation rules between parameters e.g. 

Value of Parameter 1 may not exceed value of Parameter 2

We need this because sometimes parameters are not atomic (e.g. resource editor in needs manager).

# Proposed solution

Figure out some kind of hook we can add to the container that gets called whenever a parameter value changes. When the hook is called, emit a signal indicating if the parameters state is valid. Also at-fault parameters should have their visuals updated so the user can see which are causing an issue.

Lastly perhaps we could add a message area outside of the scroll view which shows current state of the parameters with helpful text indicating what the current validation error is.

# Expected outcome

* Users of the parameters collection would then attach / implement the validation function when cross parameter validation is needed
* End users would receive user-friendly hints to help them to input the correct data into generated dialogs.

**Comment by ismailsunni** [comment]
I have updated the ParameterContainer so that it can validate between parameter. I have made an example also in the repo.
I have added another update to give ParameterContainer show a desription text.

**Comment by ismailsunni** [comment]
And adding the message box that shows custom message if there is a validation error.

**Comment by ismailsunni** [comment]
Done in parameter repository and have been used in some parts of inasafe. Closing this.
