### ISSUE TITLE
BUG - Flood impact on population - python error

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1409]
Vector flood impact on population produces this error.

# Problem

The following problem(s) were encountered whilst running the analysis.

```
ValueError
```

# Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.

# Details

These additional details were reported when the problem occurred.

```python
An exception occurred when calculating the results. Calculation error encountered:
cannot convert float NaN to integer
Diagnostics (click for details)

In file "C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe-dev\safe_qgis\utilities\impact_calculator_thread.py", line 186, in run check_integrity=self._check_integrity)
In file "C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe-dev\safe_qgis\safe_interface.py", line 541, in calculate_safe_impact check_integrity=check_integrity)
In file "C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe-dev\safe\engine\core.py", line 68, in calculate_impact F = impact_function.run(layers)
In file "C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe-dev\safe\impact_functions\inundation\flood_population_evacuation_polygon_hazard.py", line 297, in run affected_population)
In file "C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe-dev\safe\impact_functions\core.py", line 148, in population_rounding_full number = int(rounding * ceil(1.0 * number / rounding))
```
# Akbar :)

**Comment by akbargumbira** [comment]
I have fixed this in all vector on raster analysis (treat Nan as 0). I am closing this
