### ISSUE TITLE
We need metadata and other resources handled on 'save as'

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1423]
When saving a file using 'save as', the layer metadata and any other related files should also be copied over.

See also #1244

**Comment by timlinux** [comment]
See also for reference @Etienne: https://github.com/qgis/QGIS/pull/1738
	
Issue 1738 of qgis/QGIS

For users of QGIS < 2.8 this will not work - we should add a note to the changelog about that.

**Comment by mbernasocchi** [comment]
As from 2.8 use as this:

self.iface.layerSavedAs.connect(self.save_auxiliary_files)

@pyqtSlot('QgsMapLayer')
def save_auxiliary_files(self, layer):
    print layer
