### ISSUE TITLE
InaSAFE 'ReadLayerError'

### ISSUE THREAD

**Issue by emirhartato** [AIFDR/inasafe#1430]
# Problem
Can't run analysis with InaSAFE because 'ReadLayerError'

# Platform
QGIS 2.6.1 Brighton 64 Bit
InaSAFE 2.2
Windows 8

# Expected Problem
I was thinking this because QGIS/InaSAFE can't access the data or can't store the data on the hard drive. I tried to run QGIS as admin, but still shows same error.

# Process Log
Please wait - processing may take a while depending on your hardware configuration and the analysis extents and data.

This analysis will calculate the impact of Banjir Jakarta tahun 2007 on Bangunan .

The following postprocessors will be used:

Building type: Calculates building types related statistics.
Checking available memory

Computed cellsize was None. Memory check currently only works for raster input layers.
Preparing hazard data

We are resampling and clipping the hazard layer to match the intersection of the exposure layer and the current view extents.

Preparing exposure data

We are resampling and clipping the exposure layer to match the intersection of the hazard layer and the current view extents.

Preparing aggregation layer

We are clipping the aggregation layer to match the intersection of the hazard and exposure layer extents.

Problem

The following problem(s) were encountered whilst running the analysis.

ReadLayerError
Suggestion

You can try the following to resolve the issue:

Could not find file c:\users\naomi angelia\appdata\local\temp\inasafe\2014-12-06\Naomi_Angelia\work\clip_jucm_b.tif
Details

These additional details were reported when the problem occurred.

An exception occurred when setting up the model runner.
Could not find file c:\users\naomi angelia\appdata\local\temp\inasafe\2014-12-06\Naomi_Angelia\work\clip_jucm_b.tif
Diagnostics (click for details)

In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe_qgis\widgets\dock.py", line 1430, in run self.runner = self.calculator.get_runner()
In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe_qgis\utilities\impact_calculator.py", line 185, in get_runner hazard_layer = self.hazard_layer()
In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe_qgis\utilities\impact_calculator.py", line 120, in hazard_layer return self._get_layer(self._hazardLayer)
In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe_qgis\utilities\impact_calculator.py", line 82, in _get_layer return convert_to_safe_layer(layer)
In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe_qgis\safe_interface.py", line 465, in convert_to_safe_layer return read_safe_layer(layer.source())
In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe_qgis\safe_interface.py", line 443, in read_safe_layer return safe_read_layer(make_ascii(path))
In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe\storage\core.py", line 26, in read_layer return Raster(filename)
In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe\storage\raster.py", line 104, in __init__ self.read_from_file(data)
In file "C:\Users\Naomi Angelia\.qgis2\python\plugins\inasafe\safe\storage\raster.py", line 189, in read_from_file raise ReadLayerError(msg)

**Comment by timlinux** [comment]
I'm closing this as we cannot replicate it here.
