### ISSUE TITLE
Application Help for IF Wizard

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1452]
# Problem
When we click the help in IF Wizard, it opens keyword wizard help. We should create an application help for this particular wizard

# CC
@timlinux @ismailsunni @borysiasty @Charlotte-Morgan

**Comment by timlinux** [comment]
I think we should remove the help button on wizards - the whole point of the wizard is to lead the user step by step through a process - so in my opinion help in this context is redundant and we should rather increase / improve the explanatory text on each page of the wizard.

**Comment by borysiasty** [comment]
Ok, I removed the button, keeping the help file for now - just in case.
