### ISSUE TITLE
The provenance of minimum needs should be put under minimum needs section

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1455]
# Problem
I just realised that we put the provenance field under Option tab on IF options. This is ambiguous. Is this the provenance of the default threshold that we give (because we put it below threshold)? No.
![provenance](https://cloud.githubusercontent.com/assets/992519/5585217/277cd632-90d7-11e4-8bd9-d4b3c9e6df7d.png)

On IF Wizard
![min_needs](https://cloud.githubusercontent.com/assets/992519/5585219/36eee704-90d7-11e4-9f98-dc48bcb4600b.png)

# CC
@timlinux @cchristelis @Charlotte-Morgan @ismailsunni @borysiasty

**Comment by cchristelis** [comment]
@akbargumbira I think you are right. I think there are a couple of issues with the current options system both internally and from a UI experience. We should re-think our approach here. This would be a worthwhile update in view of the great work being done on the IF rework. I will have a think about this and try and come up with a suggestion on how to handle these.

**Comment by timlinux** [comment]
@cchristelis can you attend to this for 3.2 please?

**Comment by timlinux** [comment]
@cchristelis can you give an update on this?

**Comment by cchristelis** [comment]
This was fixed in f4d1e4c591de45db3ce4006cc7e583f3cfc36083
