### ISSUE TITLE
The Summary on IF Wizard does not reflect the IF Parameter Dialog

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1456]
# Problem
Basically this is (https://github.com/AIFDR/inasafe/issues/1454) a general issue. All the IF parameters that are changed in IF Parameter Dialog on IF Wizard do not get carried into the next step.

On IF Params Option, I:
- do not check gender postprocessing
- change the age ratio (it should also give error as the total ratio is more than 1)
![postprocessors](https://cloud.githubusercontent.com/assets/992519/5585265/a563bd58-90d8-11e4-969e-a973a2c54af6.png)

On Minimum Needs, I:
- change the rice to 21 kilograms weekly
![min_needs2](https://cloud.githubusercontent.com/assets/992519/5585270/cc5397bc-90d8-11e4-8572-e43c23503269.png)

But the summary gives me this:
![summary_2](https://cloud.githubusercontent.com/assets/992519/5585274/da5fb1ce-90d8-11e4-8af4-f1f1083f0a64.png)

# CC
@timlinux @ismailsunni @Charlotte-Morgan @borysiasty

**Comment by ismailsunni** [comment]
It's been fixed in 248bf01
