### ISSUE TITLE
[IFCW] Add Help Text For Choosing Layer from Disk

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1465]
Problem
-----------
There is no information on what kind of layer that the user need to find from disk (when user want to use layer from disk)

Solution
-----------
Probably add simple message like 'please select a polygon or raster flood layer' in the blue box like in the image below.
![inasafe_021](https://cloud.githubusercontent.com/assets/1421861/5612093/f721cdd8-9501-11e4-9ce6-60bd1f5d5335.png)

We can get the requirement of the layer from the impact function that has been chosen.

This apply for hazard, exposure, and aggregation layer

Expected Result
----------------------
Users know what kind of layer they need to find in the disk

cc @timlinux

**Comment by Charlotte-Morgan** [comment]
hi @borysiasty - this wizard is looking very good & its nice to be able to play with it after so long in the making.
I agree with @ismailsunni - it would be good for the user to have some more specific information as they select the hazard and exposure data.
Would it be possible to be more explicit in the description of each IF ?
