### ISSUE TITLE
[IFCW] Add Explanation to Impact Function

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1467]
Problem
-----------
There is no explanation what do an Impact Function need (layer) on Impact Function selection step. It can help user to decide what the want to choose. For example:
```
This impact function works with raster hazard and vector exposure
```
The string can derived from impact function metadata. And format them to make it better (for blue box)

![inasafe_023](https://cloud.githubusercontent.com/assets/1421861/5612276/e7ca4dc6-9504-11e4-8d88-f95feb8cb083.png)

For the green box, it seems we have long list of impact function. Is it possible to make it short, by putting generic impact function in one category? I'm not sure how we can define generic. Perhaps it needs another IF API.

Some Ideas for Solution
--------------------------------
- [ ] Add explanation for what impact function needs from the metadata
- [ ] Use invisible table and better case (e.g. title case for key)
- [ ] Use UN OCHA icon to visualize it (e.g. Flood Building Impact Function will show flood and building icon)
- [x] Make the list of impact functions shorter by grouping generic IF to one hazard category

Expected Result
----------------------
Better display and explanation on impact function selection wizard

**Comment by borysiasty** [comment]
This issue is mostly obsolete. I move it to 3.1 to not forget to make nicer description for the function.

**Comment by ismailsunni** [comment]
I am closing this is obsolete. We are using matrix now.
