### ISSUE TITLE
We need to review all icons for visual clarity and consistency

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1469]
See also #1468 - I think their is fairly broad leeway here for you to redo all the icons to make them clear and consistent. Currently they are visually cluttered and quite hard to read. What would be quite ideal for me would be to follow the same visual style of the QGIS built in icons but with an 'InaSAFE orange' theme to them.

You can see also this page (though somewhat outdated now) for some of the early thinking that went into the QGIS / OSGEO icons:

http://robert.szczepanek.pl/icons.php

I think the master library for OSGEO icons is here:

http://trac.osgeo.org/osgeo/browser/graphics/trunk

**Please note** that all icons must be made available under a creative commons license so we cannot make derivative works from non free icons.

**Comment by MariaSolovyeva** [comment]
Would be good if I could see the whole interface where the icons are used, to have the idea of the proportions and white space.  A screenshot would be great.
