### ISSUE TITLE
BUG - [IFCW] - python error

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1470]
IF fails to run due to insufficient overlap.

# problem
the IFCW seems to have a problem defining the analysis extent for EQ.
This is regardless of which choice is selected for the analysis extent.
- it it not easy for the user to define the analysis extent before the data are loaded and visible when given the choice of 
- use users extent
- use current screen extent (nonsense before data are loaded)
- use layers extent (this should work as a default)
# error message
An error has occurred while executing Python code:

Traceback (most recent call last):
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\gui\tools\wizard_dialog.py", line 2288, in on_pbnNext_released
    self.setup_and_run_analysis()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\gui\tools\wizard_dialog.py", line 2156, in setup_and_run_analysis
    self.analysis_handler.setup_and_run_analysis()
  File "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe-dev\safe\utilities\analysis_handler.py", line 332, in setup_and_run_analysis
    raise e
InsufficientOverlapError: There was insufficient overlap between the input layers and / or the layers and the viewable area. Please select two overlapping layers and zoom or pan to them or disable viewable area clipping in the options dialog. Full details follow:
    Failed to obtain the optimal extent given:

 - Hazard: C:/WorkSpace/Data/InaSAFE projects/InaSAFE projects/data/earthquake_bg_padang.tif
 - Exposure: C:/WorkSpace/Data/InaSAFE projects/InaSAFE projects/data/popmap10_all.tif
 - Viewable area Geo Extent: [-1.0825958702064897, -1.0, 1.0825958702064897, 1.0]
 - Hazard Geo Extent: [96.956, -5.5188329539999, 104.63933026000001, 2.2894972560001]
 - Exposure Geo Extent: [95.05902541031102, -10.997474511110997, 141.00718741031102, 5.907682588889002]
 - Viewable area clipping enabled: True
 - Details: Bounding boxes of hazard data, exposure data and viewport did not overlap, so no computation was done. Please make sure you pan to where the data is and that hazard and exposure data overlaps.

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.4.0-Chugiak Chugiak, 8fdd08a

Python path: ['C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISCH~1/apps/qgis/./python', u'C:/Users/AIFDR_ADMIN/.qgis2/python', u'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins', 'C:/PROGRA~1/QGISCH~1/apps/qgis/./python/plugins', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\bin', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\arcpy', 'C:\\Program Files (x86)\\ArcGIS\\Desktop10.2\\ArcToolbox', 'C:\\PROGRA~1\\QGISCH~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISCH~1\\bin', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISCH~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\\inasafe-dev', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe-dev\\safe_extras\\parameters', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\MetaSearch\\ext-libs', 'C:\\PROGRA~1\\QGISCH~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe', 'C:\\Users\\AIFDR_ADMIN\\.qgis2\\python\\plugins\\inasafe-dev']

**Comment by borysiasty** [comment]
@Charlotte-Morgan could you please provide detailed steps how to reproduce it? I never get this error.

**Comment by borysiasty** [comment]
Another words, are you able to reproduce it using one of the sample layers, as I don't have popmap10_all.tif to test it.

**Comment by borysiasty** [comment]
And please remember the wizard only test if layer **extents** overlap, not **data** on the layers. If one layer covers all the world, it will overlap with any other layer and pass this test, even if features (or non-null raster cells) on that layer don't hit any features on the second layer. I believe it's beyond wizard's scope to perform a real test, as it's not visible before running the analysis. So for those (rare?) cases the error should be nicely caught by the analysis handler rather than by the wizard,

**Comment by Charlotte-Morgan** [comment]
hi @borysiasty & @ismailsunni 
scenario is :
- [ ] open QGIS load data for place A & define an analysis extent using Tims Tool.
- [ ] then load different data in the same session for place B, zoom to place B, make place B data active & press run.

- [ ] i got this again this week. (but knew what i was doing wrong)
- [ ] I think it may need a user warning @cchristelis ie "Your data extent has been set but does not coincide with your analysis data"

**Comment by borysiasty** [comment]
Ok, now I got it. I guess the same error occurs if you run the analysis from the dock, doesn't it?

I can implement a warning in the wizard's AnalysisHandler, so the problem will be solved only for analyses called from the wizard. However, in the near future the AnalysisHandler is expected to be used also by the dock, what should fix the problem completely.

**Comment by Charlotte-Morgan** [comment]
Correct. I was creating this error from the dock.

Sent from my iPhone

On 30 Jan 2015, at 9:32 pm, Borys Jurgiel <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, now I got it. I guess the same error occurs if you run the analysis from the dock, doesn't it?

I can implement a warning in the wizard's AnalysisHandler, so the problem will be solved only for analyses called from the wizard. However, in the near future the AnalysisHandler is expected to be used also by the dock, what should fix the problem completely.

-
Reply to this email directly or view it on GitHub<https://github.com/AIFDR/inasafe/issues/1470#issuecomment-72209342>.

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
-------------------------------------------------------------------------------------------------------------------------

**Comment by Charlotte-Morgan** [comment]
@borys: LGTM
I loaded data manually, defined analysis extent, ran an analysis from the dock.
Then  .... zoomed to a new location
Opened wizard, selected IF ... told it to use current extent of map display
Happy .. happy .. Happy

**Comment by borysiasty** [comment]
:-)
