### ISSUE TITLE
[IFCW] Categorical vs Categorised

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1471]
# problem
The overview text in the  IFCW is the same for both categorical and categorised IF.

# proposed solution
If these IF are the same then we only need one
If these IF are different then we need to explain to users the difference

# cc
@maning @assefay @timlinux @dichapabe

**Comment by dichapabe** [comment]
Hi @Charlotte-Morgan 

They are the same because I based my script from this IF and improved it. I didn't delete it because I'm not the author.

**Comment by ismailsunni** [comment]
Hmm, if categorical is improved version of categorised, I agree to delete the categorised one. Deleting a file is very easy. Now, it depends on you, @Charlotte-Morgan  :)

cc @timlinux @akbargumbira

**Comment by akbargumbira** [comment]
Hi, I had a quick look at the code for Categorical and Categorised on Population, correct me if I am wrong, but they calculate the impact differently.

Let's say the threshold parameter is high_t, medium_t, low_t.
The categorised one will categorise the impacted population into three:
- High Impact: total population impacted by the hazard that has value in interval [medium_t, hight_t]
- Medium Impact: total population impacted by the hazard that has value in interval [low_t, medium_t)
- Low Impact: total population impacted by the hazard that has value in interval [0, low_t)

The categorical will categorise the impacted population into:
- High Impact: total population impacted by the hazard that has value equals to hight_t
- Medium Impact: total population impacted by the hazard that has value equals to medium_t
- Low Impact: total population impacted by the hazard that has value equals to low_t

**Comment by dichapabe** [comment]
Hi @akbargumbira you are right. Sorry I lost it in my mind. I remember this is what are we discussing in #1091 

I have a proposal so that we can make categorical and categorised as one IF.

I added 'categorised' as an parameter (better if check box or radio button):

            parameters = OrderedDict([
                    ('low_thresholds', 1.0),
                    ('medium_thresholds', 2.0),
                    ('high_thresholds', 3.0),
                    ('categorised', 1.0),


In my code, if the parameter 'categorised' is 1 (true) it will use the computation of categorical IF which are:
high impact: value = high
medium impact: value = medium
low impact: value = low

else, it will use the computation categorised IF which range the values:
high impact: value <= high
medium impact: value < medium
low impact: value < low

            if categorised == 1:
                        if high_t == 0:
                            hi = numpy.where(0, population, 0)
                        else:
                            hi = numpy.where(data == high_t, population, 0)
                        if medium_t == 0:
                            med = numpy.where(0, population, 0)
                        else:
                            med = numpy.where(data == medium_t, population, 0)
                        if low_t == 0:
                            lo = numpy.where(0, population, 0)
                        else:
                            lo = numpy.where(data == low_t, population, 0)
            
                    else:
                        if high_t == 0:
                            hi = numpy.where(0, population, 0)
                        else:
                            hi = numpy.where(data <= high_t, population, 0)
                        if medium_t == 0:
                            med = numpy.where(0, population, 0)
                        else:
                            med = numpy.where(data < medium_t, population, 0)
                        if low_t == 0:
                            lo = numpy.where(0, population, 0)
                        else:
                            lo = numpy.where(data < low_t, population, 0)


For now, I can't work on this because I'm doing different work in the office. Maybe by February I can work with InaSAFE again.

cc:
@maning @timlinux @Charlotte-Morgan

**Comment by akbargumbira** [comment]
@dichapabe I think that would be a good workaround. We can remove the other IF if we add the option to tell that the hazard is already categorised..

**Comment by ismailsunni** [comment]
Since @dichapabe can work on this in Febuary, perhaps the instant solution is updating the metadata (overview and description) so that the user will be able to see that they are different.

A small suggestion for @dichapabe , perhaps you can use boolean instead float for `categorised`. 

But, I think it's quite easy to add those `if else` statement. Pehaps, I can help you to make it available in version 3.0 *hopefully it's not a "paper-cut"

**Comment by akbargumbira** [comment]
Hi, I am in favor of merging both of the IF, with some workaround:
* Users should tell the IF if their hazard data is already classified or not. We can achieve this by putting that on hazard's keywords or on the IF option.
* If the data is classified e.g representing the risk category, user then should put the number of categories and its labels. e.g:
  - Number of categories: 3. Then it's gonna give 3 fields to be filled by users: (<value of the data>: <the category of that value>
  - 1: Low
  - 2: Medium
  - 3: High

* If the data is continuous, e.g representing the depth of the flood, user then should put the number of categories, its boundaries (lower and upper), and its label, e.g:
- Number of categories: 3. Then it's gonna give 3 fields to be filled by users: ([lower boundary, upper boundary]: <the category of that value that falls in the range>)
- [0, 0.75]: Low
- [0.75, 1]: Medium
- [1, > 1]: High

**Comment by Charlotte-Morgan** [comment]
some suggestions:
- [ ] We need to confirm if @dichapabe intention is to use RISK data as the legend refers to risk not hazard.  All other IF work with hazard data. The introduction of RISK data and a risk IF needs to be documented.
-[ ] we should not merge IFs that operate on hazard and risk data as the reporting and terminology required is completely different. 
- [ ] I would recommend that users be able to define ranges for classes & not thresholds. Ranges can then be used in the legend.
- [ ] the results of the categorical and categorised IF are reported differently, requirements need to be clarified and documented ...

**Comment by Charlotte-Morgan** [comment]
@ismailsunni - i would like to change the word 'risk' to 'hazard' unless @dichapabe is not happy.
![image](https://cloud.githubusercontent.com/assets/5743135/5936496/ba3589be-a717-11e4-9357-a3375c57a8d1.png)
The heading says Hazard Level; i think the table rows should also say ...high hazard area, ... medium hazard area etc
 @maning @assefay - any comments / is this ok?

**Comment by maning** [comment]
@Charlotte-Morgan  After much discussion within our office on the proper use of terms (hazard, exposure, vulnerability, risk) I concur that this should be termed as hazard and not risk.  @dichapabe, please remove all string referring to risk in the IF.

**Comment by akbargumbira** [comment]
Hi, with my proposal above, we could define the label itself, be it hazard,
risk, or any term, and with non hardcoded value of each category (right
now, it's hardcoded - for categorical, 1 is low, 2 medium, 3 high)

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan @maning and @akbargumbira 

So, based on @maning 's comment, it's hazard not risk. So, we can merge it (am I right?). Based on point 1 and 2 in @Charlotte-Morgan 's previous comment.

Point 3 of @Charlotte-Morgan 
> I  would recommend that users be able to define ranges for classes & not thresholds. Ranges can then be used in the legend.

CMIIW, but I think threshold and classes are same, in the end. Let's say there is 3 classes, low, medium, high. The threshold for low is 1, medium is 2, and high is 3. It's the same may as low has range 0-1, medium 1-2, high 2-3.

> the results of the categorical and categorised IF are reported differently, requirements need to be clarified and documented ...

Sure. We need to do it.

cc @timlinux

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - i added another long comment last night but i do not see it here :(

**Comment by Charlotte-Morgan** [comment]
@ismailsunni @timlinux 
here is an attempt to reconstruct a very considered contribution that i failed to post late yesterday.

I don't think these should be merged together because the user input and reporting requirements are so different.

- [ ] if data are classified ie in classes then they should define class values not 'thresholds'. ie the wording on this screen is misleading
![image](https://cloud.githubusercontent.com/assets/5743135/5955099/cdccbe88-a7d1-11e4-87a1-8d38abaf8fe0.png)
- [ ] if data are continuous the IF should ask users for ranges. Ranges should be mutually exclusive.

- [ ] results should be reported for 
 - [ ] classes as "High Hazard Class"
 - [ ] ranges as "High Hazard (value - value)  as in flood impact on buildings

![image](https://cloud.githubusercontent.com/assets/5743135/5955149/6e7f1664-a7d2-11e4-9d05-9be9d556ec89.png)

if you can merge & deal with this and keep the user well informed then .. good

**Comment by timlinux** [comment]
Can we remove teh release blocker tag from this? The bits that we care about (consistent nomenclature, ability to flag classified vs continuous rasters) are in place for 3.0 and the rest should happen in the next release.

**Comment by Charlotte-Morgan** [comment]
+ 1 for go ahead

**Comment by assefay** [comment]
Sorry to chip in late. Agreed with @Charlotte-Morgan and @maning  on the use of hazard.

@ismailsunni @dichapabe : I was trying to use the Classified Hazard Building Impact Function. I was not able to set properly a classified raster layer through the keyword creation wizard interface and have that function available as a choice of an impact function.

I believe the change described below is required? I tried this locally and It seems to work. I am bit late on this but I thought the :param notation was not used any more?
 
I also saw in the key editor something like generic [categorized]: should that be removed ?

```
diff --git a/safe/impact_functions/generic/classified_hazard_building.py b/safe/impact_functions/generic/classified_hazard_building.py
index d5b7a01..0c26596 100644
--- a/safe/impact_functions/generic/classified_hazard_building.py
+++ b/safe/impact_functions/generic/classified_hazard_building.py
@@ -44,7 +44,7 @@ class ClassifiedHazardBuildingImpactFunction(FunctionProvider):
     :author ESSC
     :rating 3
     :param requires category=='hazard' and \
-                    unit=='categorised' and \
+                    data_type=='classified' and \
                     layertype=='raster'
 
     :param requires category=='exposure' and \
```

**Comment by akbargumbira** [comment]
Hi @assefay, yes thanks, just fixed it here https://github.com/AIFDR/inasafe/pull/1591/files (note: for the unit of the classified data_type is classes, not 'categorised')

**Comment by akbargumbira** [comment]
@assefay we are still using docstring for 3.0 to load the IF definition and all the parameters needed. @timlinux is working on it for 3.1 I think

**Comment by akbargumbira** [comment]
@assefay:
> I also saw in the key editor something like generic [categorized]: should that be removed ?

Yes. But this is quite problematic though as now using this keywords dialog, it will only assign subcategory and the unit. Right now we need to know the data_type of the data (whether it's continuous or classified). Even if I change it to generic [classes], the dock will not recognise it

**Comment by ismailsunni** [comment]
Summary:
We change categorised and categorical IF to continuous and classified IF, and also change the metadata.

Can we close this now?

@Charlotte-Morgan @timlinux @akbargumbira @dichapabe @maning @assefay

**Comment by timlinux** [comment]
@assefay to confirm @akbargumbira 's comment above, correct in 3.1 we will have all docstrings stripped out

@ismailsunni I am ok to close this - we will open a new ticket for the merged IF's after it has been agreed by everyone on the way forward.

**Comment by assefay** [comment]
@akbargumbira : thanks for applying the changes. I do not have more comments on this issue.
