### ISSUE TITLE
[IFCW] - only displays results when data layers added from disk

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1472]
# problem
When the IFCW adds layers from disk these are not added to the display.

# solution
is this what the user would expect?

**Comment by borysiasty** [comment]
Oh, one question: is it just the input layers aren't automatically added to the map canvas, or something is wrong with the results?

**Comment by Charlotte-Morgan** [comment]
Oh, two answers:
- [ ] the layers are not added to the map canvas (exposure should be on top of hazard)
- [ ] the layers are not listed in the wizard when the user is asked to check the information is correct before they run the function
eg: 
![image](https://cloud.githubusercontent.com/assets/5743135/5701601/1c626b88-9a80-11e4-8c59-ae9b03719b0a.png)
- [ ] the results are hopefully independent of the wizard?

**Comment by borysiasty** [comment]
Ok, in PR #1525 layers selected in the browser are added to map canvas (if they didn't before). The missing names on the the summary tab was just a display bug, so the results were proper.
