### ISSUE TITLE
Pull out Code from Dock to AnalysisHandler

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1475]
Problem
----------
Currently, AnalysisHandler has duplicate code from Dock.

This ticket is for tracking (yes, of course it is :) )

Solution
-----------
The idea is, pull out duplicate code from Dock, and put it on AnalysisHandler. Ideally, Dock and Wizard will only handle UI-thing and user interaction. Both of them will import AnalysisHandler.

Expected Result
----------------------
No more duplicate code and neater architecture.

**Comment by borysiasty** [comment]
@ismailsunni, would you mind to take the dock part? Feel free to break the wizard.
