### ISSUE TITLE
[IFCW] Make Adding Layer from PostGIS Work

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1476]
Problem
----------
Currently, when we chose PostGIS, the next button is not enabled. And we can try to add layer from postgis.

Expected Result
----------------------
Make it works :)

**Comment by borysiasty** [comment]
I can't confirm it. Just made successful analyses loading postgis exposure from both sources: the canvas layer list and the browser. Could you provide any steps to reproduce?

**Comment by ismailsunni** [comment]
I use aifdr/develop


   1. Structure vs Volcano, next
   2. Polygon vs Polygon, next
   3. Choose the only IF, next
   4. Load from disk, next
   5. Choose PostGIS, but the next button is disabled, and there is no
   information related to it




On Mon, Feb 2, 2015 at 9:48 PM, Borys Jurgiel <notifications@github.com>
wrote:

> I can't confirm it. Just made successful analyses loading postgis exposure
> from both sources: the canvas layer list and the browser. Could you provide
> any steps to reproduce?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AIFDR/inasafe/issues/1476#issuecomment-72468835>.
>



-- 
Ismail Sunni
Junior Software Developer
kartoza.com
Open Source Geospatial Solution

**Comment by ismailsunni** [comment]
@borysiasty see below:
![inasafe_040](https://cloud.githubusercontent.com/assets/1421861/6003285/fd261720-ab2c-11e4-9022-ad436607abee.png)

I select postgis, but the next (lanjut) button is disabled.

**Comment by borysiasty** [comment]
Hmmm, the whole branch is empty...

**Comment by borysiasty** [comment]
Ok, if there is no configured connections, an information is displayed if the (empty) branch is selected:
![no_postgis_connections](https://cloud.githubusercontent.com/assets/1000043/6004839/1b104bc4-ab06-11e4-99e7-3ff1dca371ef.png)
