### ISSUE TITLE
We need to remove the IF browser in favour of in-wizard filtering

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1482]
Please refer to #439 - the IF browser has usability issues. On discussion in our Jan 7 2015 sprint the proposal is to:

- [x] completely remove the IF browser for 3.1
- [ ] add similar filtering options to the IF Centric wizard workflow for 3.1 see #1489 

# CC

@charlotte-morgan

**Comment by ismailsunni** [comment]
Perhaps the filtering options should be assigned to @borysiasty

**Comment by Charlotte-Morgan** [comment]
hi @timlinux & @ismailsunni  & @borysiasty 
I have discussed this issue with @timlinux and have a modification for this proposal.
I agree there are usability issues with the IF browser #439 and that filtering in the wizard is a good alternative. But i would like us to consider alternative solutions for the 'filtering'. Pls see #1489 for more.

**Comment by ismailsunni** [comment]
Closing this. The PR has been merged.
