### ISSUE TITLE
[BUG] Minimum Needs Manager

### ISSUE THREAD

**Issue by harrymahar** [AIFDR/inasafe#1491]
# Problem
There are errors in minimum needs manager tool 

# Details
When we try to change (Edit and Add) minimum needs using this tool there is python error when we want to save resources.

# System
Windows 8.1 64 bit
QGIS 2.6 Brighton
InaSAFE 2.2.0.dev-master
Python 2.7.5 (default, May 15 2013, 22:44:16)

# Screenshoot
![python error - minimum needs manager](https://cloud.githubusercontent.com/assets/2534179/5717509/64d90e44-9b34-11e4-8489-4ae36a377a34.PNG)

@timlinux @akbargumbira @iyan31

**Comment by timlinux** [comment]
@cchristelis please look at this as a priority

**Comment by timlinux** [comment]
+1 to merge this thanks

**Comment by cchristelis** [comment]
Unicode was not expected. This has been fixed.
