### ISSUE TITLE
Python Error when using keyword editor

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1492]
# Problem
Got python error code when tried to define new shapefile as hazard and exposure

# Detail
I tried to using keyword editor on new shapefile to define the shapefile as hazard layer. But when i click InaSAFE keyword editor, Python error window pop up and showed that i got an error while executing python code. 

When Harry, tried to using keyword editor to the hazard shapefile and exposure shapefile (Jakarta flood and building osm) he got an error also.

I think it's because our shapefile missing .keywords file so we can't run InaSAFE keyword editor to define the shapefiles as hazard or exposure.

# Screenshot
![inasafe_1](https://cloud.githubusercontent.com/assets/2520159/5717408/fb031452-9b32-11e4-9a80-a33b7be9e922.png)

# Platform
First device:
QGIS 2.4 and also 2.6 with InaSAFE 3 (2.2.dev-master) and with operating system Windows 7 64bit

Second device:
QGIS 2.6 with InaSAFE 3 (2.2.dev-master) and with operating system Windows 8.1 64

**Comment by ismailsunni** [comment]
Well, this is a regression. It works in previous InaSAFE. I tried with version 2.2

**Comment by ismailsunni** [comment]
After some debugging, this is quite strange (at least for me):

The reason is, in `plugin.py`, all modules are imported with `inasafe-dev` prefix. See image below for a better explnation:
![evaluate expression_027](https://cloud.githubusercontent.com/assets/1421861/5751876/59e15cf2-9c9d-11e4-9369-40a687bc21cb.png)

Both of them are `NoKeywordsFoundError`. But the first one is referenced by <class `inasafe-dev.safe.common.exceptions.NoKeywordsFoundError> and the second on is referenced by <class `safe.common.exceptions.NoKeywordsFoundError>. So, they are "different". And this makes the exception is not caught any more.

**Comment by akbargumbira** [comment]
The same kind of issue http://stackoverflow.com/questions/1988475/exception-not-getting-caught-when-not-in-the-right-package-in-python

**Comment by ismailsunni** [comment]
@akbargumbira I fixed it like this : https://github.com/AIFDR/inasafe/pull/1515/files#diff-66c71ea3faaa52c277917c951aa67921R41

What do you think?

**Comment by akbargumbira** [comment]
ouch that is ugly :p

As safe context is now should contain all the codes related to plugin, I think it's better if we move the plugin.py to safe package. It was in safe_qgis package.

**Comment by ismailsunni** [comment]
Why didn't you move it before? I thought you have some reason to not put it under safe.

**Comment by akbargumbira** [comment]
I didn't think of this case when I moved plugin.py, sorry :p It should belong to safe package anyway..

**Comment by ismailsunni** [comment]
@akbargumbira  Ok, I have moved it. Can you review the PR? :v

**Comment by Charlotte-Morgan** [comment]
@akbargumbira & @ismailsunni - this PR does not fix python error reported in #1507

**Comment by adissadis** [comment]
I just updated InaSAFE from github but now i can't define keyword for any data. Even, the data is already have .keyword file inside it.

![inasafe_3](https://cloud.githubusercontent.com/assets/2520159/5830657/5ebb9612-a156-11e4-973e-6da800664d90.png)

**Comment by akbargumbira** [comment]
Hi @adissadis, blame @ismailsunni who changed safe.utilities.utilities.read_file_keywords adding urlparse

**Comment by akbargumbira** [comment]
Hi @adissadis, I pushed a commit to fix this. Can you try to pull it again and re-open if it's still not fixed?

**Comment by adissadis** [comment]
@akbargumbira yup it works now. thanks! :D

**Comment by ismailsunni** [comment]
thanks @akbargumbira
