### ISSUE TITLE
Print Impact Report - Template Basic and Merged_Report Disorganized

### ISSUE THREAD

**Issue by dewisulistio** [AIFDR/inasafe#1493]
# Problem
When I try to print impact layer result and choose template basic, the maps and legend not appear in the layout. Then I try to print with template merged_report, the layout maps disorganized.

# Screenshot
 
![template basic](https://cloud.githubusercontent.com/assets/2524177/5717447/8fbe3964-9b33-11e4-95dc-f2e51039785f.jpg)
![template merged_report](https://cloud.githubusercontent.com/assets/2524177/5717448/8fc288b6-9b33-11e4-9d57-b90c5be158bb.jpg)

# Platfrom
I'm using QGIS 2.6 with InaSAFE version 2.2.0 dev clone from github and with operating system Windows 7 64bit

**Comment by timlinux** [comment]
Could you try generating the print in portrait page layout? (the template is designed to be used for portrait).

**Comment by dewisulistio** [comment]
Yes, already done to try print impact layer with portrait and landscape is work. But the problem it's only template basic and merged_report.

**Comment by timlinux** [comment]
OK thanks - we are going to remove the basic template and hide the merged_report (it is only intended to be used in the report merge tool's context).

**Comment by timlinux** [comment]
@akbargumbira will you go ahead and remove those please?

**Comment by akbargumbira** [comment]
Hi @dewisulistio, we just had a chitchat about the basic template and the a3 template. It was made for a test when we had this new feature (2.0). So for now I will delete those two templats.

For merged_report template, it is being used for Impact Merge Tools only. I will hide it when user wants to print impact layer..

**Comment by dewisulistio** [comment]
Ok, that's Good
Thanks

**Comment by akbargumbira** [comment]
Hi @dewisulistio, please pull inasafe develop and try it again. It should show you only a4 templates now. Thanks.
