### ISSUE TITLE
Python Error when run InaSAFE on Road Layer

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1494]
# Problem
Get python error when Run InaSAFE analysis with Road Layer

# Detail
We tried to run InaSAFE analysis on Road Layer with Flood Hazard but when we click RUN button, we got Python error showed that  NameError: global name 'tr'  is not defined

# Screenshot
![inasafe_2](https://cloud.githubusercontent.com/assets/2520159/5717955/e627e55a-9b3a-11e4-8bf4-e359c121b7c5.png)

# Platform
First device:
QGIS 2.4  with InaSAFE 3 (2.2.dev-master) and with operating system Windows 7 64bit

Second device:
QGIS 2.6 with InaSAFE 3 (2.2.dev-master) and with operating system Windows 8.1 64

Third device:
QGIS 2.6 with InaSAFE 3 (2.2.dev-master) and with operating system Windows 7 64bit

**Comment by akbargumbira** [comment]
Hi @adissadis, please pull inasafe develop and try it again. Thanks
