### ISSUE TITLE
Problem with plugin entry in QGIS Plugins

### ISSUE THREAD

**Issue by ozsolarwind** [AIFDR/inasafe#1500]
Please refer to -> http://gis.stackexchange.com/questions/130171/problems-with-plugin-installer-manager-in-qgis-2-6-1-debian/ 

The problem is caused by a plugin, inasafe, in the QGIS Python Plugins Repository that has a maximum version of 2.999.9999 which causes the error enountered.

The entry for the latest version of InaSAFE - 2.2.2 - has an invalid QGIS MAximum Version. Perhaps setting it to 2.99 as previously would be the thing to do.

Kind regards

AnGus

**Comment by timlinux** [comment]
Thanks for this issue report - I am pushing up 2.2.3 which will fix this.
