### ISSUE TITLE
KeywordNotFoundError vs NoKeywordsFoundError

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1510]
Problem
----------
If found two similar exception class:

```python
class KeywordNotFoundError(Exception):
    """Custom exception for when a no keyword can be found."""
    pass

class NoKeywordsFoundError(Exception):
    """Custom exception for when no keywords exist for a layer.
    """
    pass
```

Based on the docstring, they are similar.

But there is a usage in impact_merge_dialog.py
```python

        if not self.entire_area_mode:
            try:
                # noinspection PyTypeChecker
                self.aggregation['aggregation_attribute'] = \
                    self.keyword_io.read_keywords(
                        self.aggregation['layer'], 'aggregation attribute')
            except NoKeywordsFoundError:
                raise NoKeywordsFoundError(
                    self.tr('No keywords exist in aggregation layer.'))
            except KeywordNotFoundError:
                raise KeywordNotFoundError(
                    self.tr(
                        'Keyword aggregation attribute not found for '
                        'aggregation layer.'))
```
So, apparently, they are quite different.
- NoKeywordsFoundError means no keyword file (or xml) or no keyword at all
- KeywordNotFoundError means there is keyword file (or xml) but the keyword (e.g. aggregation) is not found.

I just need to confirm this. While I am working on keyword things. 

What do you think @timlinux @akbargumbira ? 
Should I:
- Rename to one exception class, or
- Write new docstring for one of them

**Comment by akbargumbira** [comment]
It was there when I used it on Impact Merge tools. I think it doesn't hurt to be specific. I vote to have both Exception
