### ISSUE TITLE
Error while executing Python code 

### ISSUE THREAD

**Issue by Winston88** [AIFDR/inasafe#1511]
Hi there, I am very new to Inasafe, pythons, etc. I am trying to get flooding data in Jakarta for my thesis for my Master of Architecture. I am at the beginning and just trying to open a project and look for my InaSAFE_project folder to select Jakarta_floods.qgs. I can't find it, so then I tried to open Inasafe Options but got this message: 

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/Ashley88/.qgis2/python/plugins\inasafe\safe_qgis\plugin.py", line 574, in show_options
    from safe_qgis.tools.options_dialog import OptionsDialog
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Ashley88\.qgis2\python\plugins\inasafe\safe_qgis\tools\options_dialog.py", line 28, in 
    from safe_qgis.utilities.defaults import (
ImportError: cannot import name get_defaults

Please help!

**Comment by ismailsunni** [comment]
Hi @Winston88 

Thanks for the issue.

Did you get InaSAFE from QGIS plugin repository? If so, which version? 
Or from github?

We got similar problem before, but it's been fixed in the current version of InaSAFE. Perhaps you can update your InaSAFE to the latest version (2.2.3)

**Comment by akbargumbira** [comment]
This issue won't happen again in InaSAFE 3.0. I am closing it
