### ISSUE TITLE
Supporter Logo - distorted

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1533]
# problem
The kangaroo has been run over

**Comment by timlinux** [comment]
Can you share a screenie? Here is what my roo looks like:

![selection_145](https://cloud.githubusercontent.com/assets/178003/5946244/e97cd978-a73c-11e4-83dc-4517aa1aa674.png)

**Comment by Charlotte-Morgan** [comment]
Sorry. Thought I had put in a picture. Mine is the same as yours. The logo block is too short for its width. BNPB circle should be round. If you view logos elsewhere you can see the difference.
Also. This is a partner logo not supporters. :)

Sent from my iPhone

On 29 Jan 2015, at 3:28 am, Tim Sutton <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you share a screenie? Here is what my roo looks like:

[selection_145]<https://cloud.githubusercontent.com/assets/178003/5946244/e97cd978-a73c-11e4-83dc-4517aa1aa674.png>

—
Reply to this email directly or view it on GitHub<https://github.com/AIFDR/inasafe/issues/1533#issuecomment-71909483>.

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
-------------------------------------------------------------------------------------------------------------------------

**Comment by timlinux** [comment]
Hmm ok that does in deed look a bit squashy. I think someone asked for it to be called 'supporters' back in the mists of time. @MariaSolovyeva can you do a better job with this logo? Its here: 

https://github.com/AIFDR/inasafe/blob/develop/resources/img/logos/supporters.png

And the various consitiuent images are there too:

https://github.com/AIFDR/inasafe/blob/develop/resources/img/logos/

@Charlotte-Morgan the image in the logos folder is not squashed so it is in the code that is allowing the proportions to be list. We can get Maria to make something more balanced and change the wording to 'InaSAFE Partners' and perhaps change the orange of that text to something better....

**Comment by Charlotte-Morgan** [comment]
+1 for Maria to make it happy.
Kate explained partners and supporters to me last visit. what we have in that combo is partners. But happy to leave wording if there is a previous decision. @assefa and thoughts?

Sent from my iPhone

On 29 Jan 2015, at 5:11 am, Tim Sutton <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm ok that does in deed look a bit squashy. I think someone asked for it to be called 'supporters' back in the mists of time. @MariaSolovyeva<https://github.com/MariaSolovyeva> can you do a better job with this logo? Its here:

https://github.com/AIFDR/inasafe/blob/develop/resources/img/logos/supporters.png

And the various consitiuent images are there too:

https://github.com/AIFDR/inasafe/blob/develop/resources/img/logos/

@Charlotte-Morgan<https://github.com/Charlotte-Morgan> the image in the logos folder is not squashed so it is in the code that is allowing the proportions to be list. We can get Maria to make something more balanced and change the wording to 'InaSAFE Partners' and perhaps change the orange of that text to something better....

—
Reply to this email directly or view it on GitHub<https://github.com/AIFDR/inasafe/issues/1533#issuecomment-71927365>.

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
-------------------------------------------------------------------------------------------------------------------------

**Comment by timlinux** [comment]
I changed the code to ensure that aspect ratio is preserved. I think we should probably make a dedicated smaller one since the logo has some fuzzy buts like this:

![selection_146](https://cloud.githubusercontent.com/assets/178003/5967221/9ec7269a-a813-11e4-83c5-fe14724b85f6.png)



https://github.com/AIFDR/inasafe/pull/1545

**Comment by Charlotte-Morgan** [comment]
ouch - i think its been hit by a bit truck now

**Comment by timlinux** [comment]
Pic of desquashed skippy:

![selection_140](https://cloud.githubusercontent.com/assets/178003/6455824/0b825354-c18c-11e4-9670-8725abbb0168.png)

**Comment by Charlotte-Morgan** [comment]
ooh - very juicy
