### ISSUE TITLE
Please update Indonesian application translation

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1535]
@ismailsunni can you make sure the plugin is updated - especially wizard pages?

**Comment by ismailsunni** [comment]
Do we still use the same transifex project for inasafe 3.0?
IIRC, you want to separate the application and documentation translation.

**Comment by Charlotte-Morgan** [comment]
@ismailsunni: do you need help with this? @dika is on leave this week.

**Comment by ismailsunni** [comment]
@Charlotte-Morgan no problem, I have done translating all string for the last commit last week. It should only need to update some strings before the release.
