### ISSUE TITLE
[IFCW] Add Keywords Continouous or Classified For Raster

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1548]
Problem
-----------
There are two types of `layer_constraint` for raster layer, `layer_raster_continuous` and `layer_raster_classified`.
We need a keyword to differentiate this two by looking at the keywords file.

Proposed Solution
------------------------
Add new extra keyword `data_type` in Keyword Wizard, and ask the user to fill it. It will only come out when the layer is raster.
The option would be `continuous` and `classified`. The default value is `continuous`. So, if there is no keywords, it will use `continuous` by default. To make it backward compatibility 

Notes
-------
Please update to develop first, since the new layer_constraint are in develop branch.

**Comment by borysiasty** [comment]
Done as a separate step between subcategory and unit. (in my repo, the PR will be ready tomorrow).

Please note this way categories and subcategories are not filtered by this constraint. I guess it's better than putting this step as the very first ;) If there is no unit for the selected category, subcategory and data type, the unit step is not displayed of course, so the next step is directly the layer source. 

There is one side effect: I had to put the two raster hazard datatypes to the IFCW matrix (currently there is no classified exposure, so I didn't create such row): 
![datatypes](https://cloud.githubusercontent.com/assets/1000043/5990267/2f6502bc-a9a9-11e4-8bf9-40716bba5a02.png)

**Comment by borysiasty** [comment]
@Charlotte-Morgan - hope it's ok how it works. Please let me know if something in the matrix should be changed.

**Comment by borysiasty** [comment]
@ismailsunni: in the future, maybe we should add a get_datatypes_for_layer method to the API? Now it's possible to set both data_types to any raster. Maybe it's better, as future functions may use categorised exposures.

Btw. The list of available units in the keyword wizard is populated with all available units (for category, subcategory, layer_type and data_type) except those with `constraint` = `categorical`. This condition doesn't work for the `unit_classes` unit, as it doesn't have the `constraint` key at all. I don't know if it's good or not.

**Comment by borysiasty** [comment]
@Charlotte-Morgan: when filtering layers matching the matrix selection, layers without the 'data_type' keyword will be shown for both continuous and classified functions. Is it ok?

Another option is to make an assumption the data is continuous if not strictly marked as categorical, and hide it from categorical functions. It will force users to update the keywords prior to using the wizard.

**Comment by Charlotte-Morgan** [comment]
@borysiasty 
I like @ismailsunni original suggestion that continuous data are the default, but I see your issue here.
I'm thinking an assumption of continuous is probably the best approach and another place for @cchristelis to warn / advise users "your data have no key words. they are assumed to be in the default format of continuous data"

**Comment by borysiasty** [comment]
@Charlotte-Morgan: I applied Ismail's suggestion to the keyword wizard - if you set the keywords, you have to select one of them (continuous by default). For the IFCW the main problem is user is not informed why his layer is not listed. Some reasons are obvious, like wrong category or subcategory, but some other are more subtle - like the continuous/classified data type doesn't match, or the unit is not accepted by the selected function.

Maybe we should put those rejected layers at the end of the list, paint them gray, and once clicked, the description on the right would be 'This is not hazard layer', 'This is not flood layer', 'This is not point layer',  'this is not continuous data' ?

**Comment by Charlotte-Morgan** [comment]
@borysiasty : I don't have dev code on machine at home ... so I am not able to look at the wizard, but don't you bounce out at some stage to the "assign key words wizard"?

**Comment by borysiasty** [comment]
Strictly speaking, this issue is about adding this keyword to the (Assign) Keywords Wizard. I finished it yesterday and then started to talk about implications for the IFCW :)

**Comment by Charlotte-Morgan** [comment]
:)

**Comment by borysiasty** [comment]
@Charlotte-Morgan, @cchristelis:
Ok, so every raster layer with keywords but not data_type set is now only shown on the list if the continuous type is selected in the second constraint matrix.

**Comment by Charlotte-Morgan** [comment]
Good choice.

Sent from my iPhone

On 1 Feb 2015, at 7:09 pm, Borys Jurgiel <notifications@github.com<mailto:notifications@github.com>> wrote:


@Charlotte-Morgan<https://github.com/Charlotte-Morgan>, @cchristelis<https://github.com/cchristelis>:
Ok, so every raster layer with keywords but not data_type set is now only shown on the list if the continuous type is selected in the second constraint matrix.

-
Reply to this email directly or view it on GitHub<https://github.com/AIFDR/inasafe/issues/1548#issuecomment-72362277>.

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
-------------------------------------------------------------------------------------------------------------------------
