### ISSUE TITLE
Keywords Wizard  - No Layer Category Shown

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1554]
![no category](https://cloud.githubusercontent.com/assets/992519/5990195/c11072a4-a9d7-11e4-8e2c-1bb8f81b1267.png)

When I choose raster population (has existing keywords), this step does not show any category at all. It shows the categories (exposure, hazard, or aggregation) though when I choose other data with existing keywords (building, volcano point, volcano polygon)

**Comment by borysiasty** [comment]
It's broken by the recent changes in raster data types. Should be working in my repo (and in upcoming PR)

**Comment by timlinux** [comment]
Note that this is still a problem in develop as of 1 Feb
