### ISSUE TITLE
Key words wizard - no longer shows categories

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1562]
Key words wizard no longer shows category options on screen 1
![image](https://cloud.githubusercontent.com/assets/5743135/5995052/0ac37660-aabb-11e4-9b5d-9ea151ed4b21.png)

**Comment by akbargumbira** [comment]
Have you updated your inasafe @Charlotte-Morgan? Last night, @timlinux closed the same ticket that I issued https://github.com/AIFDR/inasafe/issues/1554

**Comment by Charlotte-Morgan** [comment]
yes @akbargumbira - I have. Thanks for checking :)

**Comment by ismailsunni** [comment]
Fixed in #1567
