### ISSUE TITLE
We need a default style for flood polygon hazard data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1565]
# problem
When the IFCW loads data from disk (when the users selects data from disk) the symbology needs to reflect values in the affected column.
This is a visualization problem only, the IF still runs using the flood polygon units.

# proposed solution
define a symbology for this type of data
add the symbology to the data

**Comment by timlinux** [comment]
We should only do this if the user has not already defined a style. This might be a nice starter task for Rizky.
