### ISSUE TITLE
Please make an icon for Volcanic Ash

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1628]
In the wizard we have 'volcanic ash' but it needs an icon in the same style as the other icons in the UN OCHA set.

![inasafe_004](https://cloud.githubusercontent.com/assets/178003/6124142/7ed7ea8c-b113-11e4-96c8-568c62d85fb0.png)

It should replace the one in the square box in the image above.

**Comment by Charlotte-Morgan** [comment]
hi @maria. 
There are 2 hazards; volcano and volcanic ash (apologies if you already know all this). 
Volcanoes have rocks and lava that impact the immediate area & volcanic ash can be dispersed for huge distances.
so an icon for a volcano with an ash cloud and an icon for a volcano throwing out rocks may work. ie the current volcano icon could do for the volcanic ash and something new for volcano with rocks coming out might work.

**Comment by MariaSolovyeva** [comment]
Alright,  what is the necessary size of the icons?
