### ISSUE TITLE
We need a developer button to load standard layers

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1630]
A common workflow I use is to do 

```python
from safe.test.utilities import load_standard_layers
load_standard_layers()
```

in the QGIS python console. That will load the standard testing layers.

Please add a button to the InaSAFE toolbar that runs the above code. The button should only be visible if InaSAFE options -> advanced -> developer mode is enabled. Also change the options checkbox text for this to something  more appropriate.

Please ask @MariaSolovyeva  to make a nice icon (in svg) for the button.

**Comment by maria** [comment]
hi, I think you wanted to mentio @ MariaSolovyeva not @ maria who is me. :)

**Comment by Charlotte-Morgan** [comment]
Sorry @maria we have a new InaSAFE team member - it will probably happen again :(

**Comment by maria** [comment]
No problem.

**Comment by akbargumbira** [comment]
This only needs a one-line command. I don't see any importance to have this button in the toolbar :)

**Comment by timlinux** [comment]
@akbargumbira it will still be convenient especially for developers and power users not familiar with the procedure to do it manually.
