### ISSUE TITLE
New icon about loading standard layers

### ISSUE THREAD

**Issue by Gustry** [AIFDR/inasafe#1632]
I've started a new icon visible here : https://github.com/Gustry/inasafe/blob/4c77337357005e361a92ccb632efd9372cf35567/resources/img/icons/add-test-layers.svg
however, I'm not a designer :)

This icon is usefull for developers. It allows loading a lot of standard layers quickly.

**Comment by Gustry** [comment]
#1630

**Comment by MariaSolovyeva** [comment]
Hi Gustry, the icon is ready, but I don't manage to understand how to upload it to the GitHub, I am new to it. Could you give me a hint please? Thank you!

**Comment by Gustry** [comment]
Thanks. Hum, unfortunately github is not very convenient for that, sorry ;-)
Maybe send me the file by email : etienne at kartoza dot com
