### ISSUE TITLE
We need to allow the user to save impact layer to their own designated directory

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1648]
# Problem

Impact layers are save to the user's temporary directory (that varies according to Operating System). Under unix-like OS's these products get destroyed on system reboot. In all cases the file name and path is non-intuitive to the user.

# Proposed solution

For this issue I am proposing a new option in the InaSAFE options dialog that allows the user to designate their preferred output directory for impact layers so that they may be organised and persistent. Note I am *not* proposing that all derivative products (e.g. clip layers) are saved there, only the final impact layer.

The expected behaviour will be:

* when an impact layer is saved it is named according to this convention: ``EXP + On + Haz + DDMMMMYYYY + HHhMM.SS.EXT`` so a preactical example may be: ``FloodOnBuildings_12March2015_10h22.04.shp``
* if the user has designated an impact layer output directory, the layer and its attendant metadata files should be saved there, otherwise the existing behaviour should continue (though using the new impact layer naming scheme).

# Expected outcomes

* Users should be able to collate and browse the output layers produced by InaSAFE in an intuitive manner
* Users should be able to persist Impact Function outputs across system reboots

# CC

@Charlotte-Morgan 

# See also

I know there was a similar ticket filed but I can't find it at the moment, please add any references to related tickets to this section.

**Comment by Gustry** [comment]
You will get a file like this : 
``Haz + On + Exp + DDMMMMYYYY + HHhMM.SS-UNIQUE.EXT``
instead of above : 
``EXP + On + Haz + DDMMMMYYYY + HHhMM.SS.EXT``

Do we need to replace accentuated characters ?

**Comment by Gustry** [comment]
When the @akbargumbira 's work about unicode will be merged, I will fix if the user directory contains an accent.
