### ISSUE TITLE
InaSAFE needs a 'postcard'

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1659]
# the idea
We need a snappy way of promoting InaSAFE at conferences.

# the design
- [x] A5 double sided
- [x] Something that explains InaSAFE - a picture
- [x] includes links to web sites &  
- [x] has info on how to get in touch if someone wants more info.
- [x] will not be easily out dated

# time frame
We will start working on this tomorrow
We want to have something ready for the 3rd WCDRR in Sendai 14-18th March 2015.

# input welcome
If you want to contribute to the design, concept, content. 
If you have already done something similar
Please contribute through this ticket.

# cc
@MariaSolovyeva @iyan31 @fredychandra @wonderchook @assefay @maning @vdeparday @timlinux @sindhu

**Comment by Sindhunata** [comment]
@Charlotte-Morgan Test, here is my github account.

**Comment by Charlotte-Morgan** [comment]
hi @sindhunata

Here are some new 'InaSAFE concept' diagrams I have been working on as we discussed this morning. I will email you these and the icons 

![image](https://cloud.githubusercontent.com/assets/5743135/6324984/0bc56e64-bb74-11e4-877c-c71a7a849160.png)

![image](https://cloud.githubusercontent.com/assets/5743135/6324992/260046aa-bb74-11e4-80c9-74aece174ca8.png)

**Comment by Sindhunata** [comment]
Hi all, here are two possible options for the A5 postcard. 
Open for critics and suggestions.

![1a](https://cloud.githubusercontent.com/assets/10645858/6409069/b8bec704-be90-11e4-94d1-88052b8abc62.png)
![1b](https://cloud.githubusercontent.com/assets/10645858/6409070/b99be8dc-be90-11e4-9939-241bf045b6bd.png)
![2a](https://cloud.githubusercontent.com/assets/10645858/6409071/ba5f9ce6-be90-11e4-9446-2283e917d7ed.png)
![2b](https://cloud.githubusercontent.com/assets/10645858/6409072/bbacb872-be90-11e4-99ac-10f943f4b5a8.png)

About the CD/DVD, we are thinking of putting the existing InaSAFE videos and the offline installation files of QGIS and InaSAFE plugin. 
By the way, @Charlotte-Morgan, should we use"Better Map Templates"? If it is a generic publication material, I'd suggest to change the word "better" to "variety of" since the former implies a previous condition. What do you think?

**Comment by Charlotte-Morgan** [comment]
hi @Sindhunata - thanks for this. +1 to not use "better". how about saying "More map templates"
Hi @MariaSolovyeva - this ticket is for HOT to do as it is part of their contract.  We are just seeking input from everyone who is interested. I will assign it back to Sindhu :)

**Comment by MariaSolovyeva** [comment]
@Charlotte-Morgan, thank you :) 
It can be a good visual to incorporate in the about section of the website, will keep the idea!
@Sindhunata, just to let you know, you can already start using new visuals of InaSAFE, to keep consistency of all communication materials, you can find them here https://github.com/AIFDR/inasafe-graphics and the style guide here https://github.com/AIFDR/inasafe-graphics/blob/master/inasafe-visual-language-guide.pdf?raw=true 
Good luck

**Comment by Charlotte-Morgan** [comment]
Hi @MariaSolovyeva 
Thanks for the reminder to have a look at the work you have done. It's great to have a 'style guide' to help us. I like everything. My only concerns are 
- [ ] can we change the logo - ie was the existing one ever approved & if so we need to take the new one through an official approval process?
- [ ] the new logo looks a little out of proportion (a bit short) compared to other Gunungan images i can find - eg https://www.google.com/search?q=gunungan&sa=X&rlz=1C1GGGE___AU567AU568&espv=2&biw=1242&bih=594&tbm=isch&tbo=u&source=univ&ei=liLxVK_yC42RuATv_YHADA&ved=0CBwQsAQ 
Maybe some of our Indonesian friends can comment on this?

Other things - @MariaSolovyeva - are you working on updating visuals for the InaSAFE concept diagram as used  here (http://inasafe.org/en/training/socialisation/overview.html) - because that is where I have started as I need to give many presentations explaining InaSAFE and I'm slowly tweaking the diagram to help me explain things. I will happily start using the colours etc in the style guide. However we also have corporate styles to use that are different :)

@Sindhunata - have you shared other HOT materials for InaSAFE with Maria so that she knows what else has been done - i'm thinking of the stickers & the other Gunungan we already have.

**Comment by Charlotte-Morgan** [comment]
Hi @Sindhunata - more specific comments on the postcard.
Thanks for working up this design. I realise that my original design idea is missing one element :(
it should have said - picture on one side and text on the other. Do you think we need to add a bit of text about the project (i'm thinking of existing text that we already use in many places. ie text that has been approved and used by AIFDR and World Bank.
Regarding graphics - please use the icons that are already used in the software and I think maybe make the icons bigger and the text smaller. i also prefer 'straight' text :)
The words "InSAFE Reality" are mine for my presentations - i dont think they belong on the diagram.

Have you discussed printing with anyone? Are there any restrictions on the number of colours used?

**Comment by timlinux** [comment]
Hi

Also note that I will be presenting about InaSAFE at FOSSASIA and would probably like to give the same core presentation - the conference is over 13/14/15 March 2015.

And yes please use @MariaSolovyeva 's style guide if at all possible and store newly created graphics in the http://github.com/AIFDR/inasafe-graphics repository.

Regards

Tim

**Comment by Sindhunata** [comment]
Hi @MariaSolovyeva and @timlinux, sorry I did not know there was a style-guide for InaSAFE.
Here, I have created some modifications, based on the InaSAFE style-guide. I also used the new logo. 

@MariaSolovyeva I am about to send you email consisting the swags that Wulan (HOT Trainer) had made before.

@Charlotte-Morgan I decided to mix the concept and reality in one picture, and change the term "reality" into "operationalisation." However,  there are also other possible options:
1. Method
2. Practical Use
3. Implementation
About the printing, I haven't discussed it with anyone, but based on my experience, number of colours used will not be a problem. 

@all: Perhaps, any other idea for the title?
The modified design options are stored in this google drive link:  
https://drive.google.com/folderview?id=0B1uQn6MUQ1TBfkhDMm1wQlZfWlpRWFBtYW9hSXA1elgzaFhjcWQ1eEtvRW1EUDI3UE9qUEE&usp=sharing

Let me know what do you think about them.


Best,
Sindhu

**Comment by Charlotte-Morgan** [comment]
Hi @Sindhunata - thank you so much for working up these ideas. I hope we get some feedback @assefay @vdeparday @fredychandra etc
@MariaSolovyeva - i wonder if you could also come up with a design to show us how you would use the style guide. ie can we use a pale background & stay within the guide? Just put dummy text in for now but give us an idea of how much text is relevant on this type of product and then we can find some words to use. I have also done some more work on the concept diagrams using your style guide. Is there some way that I can share the powerpoint slides with you?

**Comment by Charlotte-Morgan** [comment]
@Sindhunata - i think the designs look a bit dark and might be hard to read. I prefer the 2 columns of text but it looks like a lot of text. 
Here is the postcard for RASOR which was the reason I thought that we could do a postcard for InaSAFE
![image](https://cloud.githubusercontent.com/assets/5743135/6438306/72ed93ec-c0fa-11e4-8973-8ddc15a47708.png)

**Comment by fredychandra** [comment]
Hi, 
I'm just thinking possibility to breakdown or describe what kind of MAPs? What REPORTS are? and Lists of ACTIONS? as results after run InaSAFE. It might be a symbol (picture) or texts. 

@Charlotte-Morgan @Sindhunata

**Comment by wonderchook** [comment]
@Sindhunata Looking through this now. Here are some comments:

1. Don't put dark colors on top of other dark colors. You can use light colors, look at the flyer Charlotte shared above. It is fine to put it on top of white or an off-white color.

2. Using non-style guide colors where appropriate is fine. I think especially for illustrations of thinks like the impact it makes sense to use more "real world colors".

3. There needs to be clear contact information somewhere on the card as well. Where to get InaSAFE, how to get help, etc....

4. The text on the back is too long. I'd say the RASOR postcard has too much text as well, we want people to glance and know what InaSAFE is in 30 seconds. I'd suggest pulling some of the text from here: http://data.inasafe.org/Flyers/1_InaSAFE_Concept_EN.pdf

If it would be helpful to have a brief chat let me know.

**Comment by Charlotte-Morgan** [comment]
hi @wonderchook  +1 for all the above.
I have the text you refer to in 4 above that i can share

**Comment by Sindhunata** [comment]
@fredychandra that would be great, can you help me to specify each items, then I will try to conceive perfect symbol for each item.
@wonderchook thank you for the thorough feedback Kate, I will consider them on the next design, especially point number 4.
@Charlotte-Morgan sure, I will use lighter colour for the background.

Be right back.

**Comment by MariaSolovyeva** [comment]
Hi @Charlotte-Morgan  and @Sindhunata, here is an example of use the guide colors. I used the dumyy icons though
@Sindhunata, do you work in Photoshop? I can send you the .psd file so you can use and modify the layout
![postard2-preview](https://cloud.githubusercontent.com/assets/10400420/6482955/cb1da9d4-c27c-11e4-9bc4-f8df6484260c.jpg)

**Comment by MariaSolovyeva** [comment]
And here is a variant of the other side, with the icons use example
![postard1b-preview](https://cloud.githubusercontent.com/assets/10400420/6483233/9a3cd292-c27f-11e4-90ef-43c5f3dd22f4.jpg)

**Comment by MariaSolovyeva** [comment]
Another side, with images
![postard1b-preview](https://cloud.githubusercontent.com/assets/10400420/6483247/d134e776-c27f-11e4-862a-4f7c8447af06.jpg)

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva - thank you!
These look great - certainly starting to get some of the 'snappy' covered. I really like the wavy lines and the simple design of the back with less text.
Some comments:
- [ ] replace the "concept and operationalisation" text - with a big logo with web link 
- [ ] we need to include the web site links etc - how to get in touch
- [ ] the keywords wizard (typo) is relevant to hazard and exposure data
- [ ] user defined minimum needs probably belongs with the reports like the other tools have been attached to the data
- [ ] can we add a people icon for exposure data.
- [ ] there are two misconceptions i hope to communicate
1. the data are included in insafe (hence my use of a different colour to try to indicate the separation) but i'm sure there is a better way to do it
2. that the World Bank affiliation means that users need to repay a debt, so we need to promote the "free open source" as much as possible
- [ ] we can supply separate logos that can be spread across the width of the bottom panel

**Comment by wonderchook** [comment]
@MariaSolovyeva I agree that these look great. One of the common misconceptions about InaSAFE is that it comes with the data. As Charlotte said there needs to be at something visual or in text that suggests "you take your own data and run an impact analysis".  Maybe it could say "InaSAFE combines your hazard data and your exposure data". Probably too complicated to suggest where people get the data from?  If not here are some suggestions on where people would get that data.

Hazard:
-government science agencies
-university research agencies

Exposure:
-OpenStreetMap
-Census Information
-WorldPop
-Government GIS Departments

**Comment by Charlotte-Morgan** [comment]
i prefer a visual que if possible rather than changing the very standard words that we use everywhere

**Comment by Charlotte-Morgan** [comment]
hi everyone - this is progressing well. like all the chat in hip chat.
Just a reminder - we need this finished and printed on Monday :)
keep up the good work

**Comment by timlinux** [comment]
Just for the record, here is the log from our hipchat:

TS: but I have a few comments too
MS: ok
TS: so those would be front side and back side right for the same card?
for the front side
I think the orange is a little too much
MS: yes, I should try with other colors as well
TS: yes that would be great
the wavey lines are great
MS:
maybe blue or green with little orange accent
TS:
the minimimalistic icons are great
yes
I leave it to you to come up with something
I sent you an email this morning with a few requests
some of which come out into the postcard
e.g. having logo with url use lower case letters so www.inasafe.org not www.INASAFE.org
MS:
yes I see
TS:
also the logos at the bottom
if you can separate them out so they are spaced more across the bottom
MS:
yes ok
TS:
MS:
maybe still leaving some nice visual whitespace boxing around the inasage logo
and then fill the remaining space evenly with the logos
other items charlotte mentioned too:
Ill just remention some important ones:
1) Wizard should be spelled with a 'z'
MS:
oops
TS:
2) The keywords wizard needs to be used on both hazard and exposure data
so somehow the diagram should reflect that
MS:
ok
MS:
and OSM downloader only for Exposure, right?
TS:
I love the way you have done the sub icons under the hazard and exposure boxes so keep that
correct
just the exposure one needs also a subicon for population / people
MS:
ok
TS:
3) the text in the center box "InaSAFE produces maps, records & and action list"
I think instead of that it should say:
"InaSAFE produces maps, reports & action lists"
TS:
4) The top title "The concept and operationalisation of InaSAFE"
we need to get rid of that
as per @charlotte's checklist item
MS:
ok
TS:
did @charlotte's other comments make sense?
User defined minimum needs box goes as a sub box of reports
same way you have sub boxes in hazard and exposure
MS:
ok, I think I got it all
MS:
will be modifying it tomorrow morning, if there is something, I will ask
TS:
ok
cool
the back page is absolutely gorgeous
not much to comment on it
other than to emphasise that the software is Free and Open Source software
MS:
ok, will remember
TS:
great stuff
MS:
thank you!
MS:
ah, I had a question
TS:
ok
MS:
there is a box "set analysis extent"
MS:
what kind of icon i can put for it
MS:
and is it connected directly to InaSAFE logo
TS:
perhaps a marquee
or a magnifying glass
MS:
ok
TS:
you could perhaps move it as a box attached to the central box
then move teh impact wizard box into the center
1 sec let me make a rough pen sketch
MS:
ok
TS:
just give me 2 mins

![photo](https://cloud.githubusercontent.com/assets/178003/6497615/a3d2f580-c314-11e4-8160-e2defb3c97a4.jpg)

sorry its a terrible drawing
@Maria but hopefully it gives an idea
of what I am suggesting
MS:
yes, very clear
so I remove the InaSAFE logo from the center
TS:
hopefully you can make it clear and beautiful :-)
I think so
we have it in several other places
MS:
ok
MS:
tomorrow will send the result

**Comment by MariaSolovyeva** [comment]
Hi @all,

Here is modified front-side, few colors examples.
What about the texts for the back-side? Is there anybody who is preparing it? All the blocks of the template I shared are adjustable, so we can adapt it to differents text blocks, change their amount, etc.

![postard2-preview](https://cloud.githubusercontent.com/assets/10400420/6501615/aa09d420-c32b-11e4-836d-c77aec3cab98.jpg)
![postard2b](https://cloud.githubusercontent.com/assets/10400420/6501616/ab6bec90-c32b-11e4-85a9-a5385dce286d.jpg)
![postard2c](https://cloud.githubusercontent.com/assets/10400420/6501617/adf39526-c32b-11e4-83f2-934b1ea30069.jpg)

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva 
Wow - this looks good.
let me find you some text for the back-side !!

there is still a wizard typo :)

**Comment by MariaSolovyeva** [comment]
@Charlotte-Morgan 

OOps, will fix it!

I would need also the typography requirements, like
- margins and bleeds sizes
- resolution
- file format

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva 
Here is some backside text, taken from existing brochures and other relevant sources (@vdeparday - plagarism alert). I expect there is too much but lets give it a go.
As for typography - sorry, I'm sure others can help with that.


What is InaSAFE?
InaSAFE is free software that produces realistic natural hazard impact scenarios for better planning, preparedness and response activities. 

How does it work?
InaSAFE provides a simple but rigorous way to combine data from scientists, local governments and communities to assess the possible impact of future disaster events. The software allows the user to assess the impact a single hazard would have on vulnerable people, assets and infrastructure; and can calculate the resources required to support the affected population.

Who can use it?
Anyone with basic computer skills will quickly learn how to use InaSAFE to explore the potential impact of a disaster event and to produce maps and reports. The InaSAFE wizards lead a user through the process of locating their data, choosing an impact function and assessing the likely damage that a hazard will cause to vulnerable people, assets and infrastructure.

Where does the data come from?
InaSAFE is designed to use and combine existing data from science agencies, local governments, and communities. Normally, information on the location of people and important assets are provided by local communities and government departments responsible for each sector, often through facilitated disaster preparedness and planning exercise. Where spatial data doesn’t exist, external tools such as OpenStreetMap (www.LearnOSM.org) are available for governments and communities to map assets that are important to them.

How much does it cost?
InaSAFE is free. InaSAFE was initially developed through collaboration between the Indonesian and Australian Governments and the WB-GFDRR. It has now been used in a number of countries around the world and there is growing demand from governments around the world to use InaSAFE for a range of DRM applications.

Where do I get more information?
The InaSAFE website (www.inasafe.org) has more information and instructions for installing InaSAFE.

**Comment by timlinux** [comment]
Maybe we should unpack the DRM acronym too - Disaster and Risk Management ?

@Charlotte-Morgan wrote:

>  what do you think about icons for food, water and shelter under the reports?

Yes that would be good!

**Comment by timlinux** [comment]
and @MariaSolovyeva this is looking fantastic!

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva - just showed my text to Dom & the design to the logo police.
Let me edit text and get back to you.
I also need to change 1 logo :)
@timlinux

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva 
take 2 on the text .....

What is InaSAFE and how much does it cost?
InaSAFE is free.  InaSAFE, developed jointly by Australia, the World Bank and Indonesia is free software that produces natural hazard impact scenarios for better planning, preparedness and response activities - it uses innovative science and crowd sourcing techniques (OpenStreetMap, OSM) to create realistic disaster scenarios and is in demand by disaster managers across Indonesia and around the world.
How does it work?
InaSAFE provides a simple but rigorous way to combine data from communities, local governments and scientists to assess the possible impact of future disaster events. The software allows the user to assess the impact a disaster would have on a community, its assets and infrastructure; and can calculate the resources required to support affected populations.

Who can use it?
Anyone with basic computer skills can learn to use InaSAFE. The software leads the user through the process of locating their data, choosing an impact function and assessing the likely damage that a disaster will cause to a selected community.

Where does the data come from?
InaSAFE is designed to use and combine existing data from communities, local governments and science agencies. The location of people and important assets are often provided by communities. Where spatial data doesn’t exist, external tools such as OpenStreetMap (www.LearnOSM.org) are available for governments and communities to map assets that are important to them.

Where do I get more information?
The InaSAFE website (www.inasafe.org) has more information and instructions for installing InaSAFE.

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva - i've sent you email with Logos and DFAT branding requirements.

We need to use 
![image](https://cloud.githubusercontent.com/assets/5743135/6503738/5bf27c1a-c362-11e4-9f37-5dfd502632cd.png)

**Comment by MariaSolovyeva** [comment]
Thank you for the feedback, @Charlotte-Morgan and @timlinux 

Here is the version with icons for the reports and modifies logos.
BTW, which color variant do you prefer, so I continue with the one?

![postard2b](https://cloud.githubusercontent.com/assets/10400420/6504926/9ba77136-c34d-11e4-87c4-0f10481331a3.jpg)

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva 
Looking good & thank you so much for pitching in with your expertise. 
Lets stick with the orange one as that is the DM colour (so i've been told)
- [ ] Logos - please use the Australian government crest (not the AIFDR / Australian Aid part), and make BNPB logo bigger and use the stacked WorldBank GFDRR logos.
- [ ] please look at consistency of capitalisation. eg Keywords Wizard vs Impact function wizard etc etc
- [ ] typo minimum needs
- [ ] please check centering of the reports box
- [ ] i'm wondering about centering text for the two lines that wrap (user defined minimum needs & impact function wizard)

Happy to know how the backside is holding up. let me know if there is too much text.
Thank you again.

**Comment by timsutton** [comment]
@Charlotte-Morgan I think you meant @timlinux :)

**Comment by fredychandra** [comment]
@MariaSolovyeva and @Charlotte-Morgan  I suggest we add health symbol (Logo) also under REPORT. In Sphere Project MInimum Standard -http://www.sphereproject.org/about/ there are 4 main sector for minimum needs standard sector : 1) Water and  Sanitation ; 2) Food Security, Nutriment and food item; 3) Shelter / non-food item and 4) Health.

**Comment by fredychandra** [comment]
@MariaSolovyeva @Sindhunata 

Text for the ACTION (back side)  we can use based on InaSAFE Checlist Action : 

-[ ] How will warnings be disseminated ?
-[ ] How will we reach stranded people ?
-[ ] Do we have enough relief items?
-[ ] If yes, Where can we obtain additional relief items from and how will we transport them to there?
-[ ] If No, Where can we obtrain additional relief items from and how will we transport them to here?

It would be nice if we can transform it into symbol and put some under ACTION. In my mind like Early Warning System symbol, perhaps you have it?

**Comment by Sindhunata** [comment]
@MariaSolovyeva I can work with .PSD through GIMP. Can you send me the .PSD through email?

**Comment by MariaSolovyeva** [comment]
Hi @Charlotte-Morgan, @timlinux, @fredychandra,

Here is what I currently have:
need to think how to tweak the layout to add the text for action

![postard1b](https://cloud.githubusercontent.com/assets/10400420/6521300/14da5e44-c3e7-11e4-8bbb-c189bf7b9b14.jpg)
![postard2b](https://cloud.githubusercontent.com/assets/10400420/6521301/14f271dc-c3e7-11e4-81b9-c5f95249b767.jpg)

**Comment by MariaSolovyeva** [comment]
@fredychandra , could you share with me the Early Warning System symbol, how it looks like?

**Comment by Charlotte-Morgan** [comment]
Hi @MariaSolovyeva  - thanks for latest.
@fredychandra & i are discussing any final edits and will get back to you soon.
The logo police and DFAT clearance have some more comments :( but then we are done :)

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva - here is the latest re logos. please use 4 and in the order as supplied.
have also been asked if we need logos front and back.
I like them centered on the back.
should we take them off the front (what would go in the place?)
![image](https://cloud.githubusercontent.com/assets/5743135/6521865/64c657c8-c40f-11e4-9a9d-9ff1ed0ba13b.png)

**Comment by MariaSolovyeva** [comment]
@Charlotte-Morgan, if we remove them in the front, we can center the small InaSAFE logo and maybe add some tagline. Like the one which @timlinux proposed for the t-shirt "Better planning saves lives" ?

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva 

here is the final text

What is InaSAFE?
InaSAFE is free software and was developed jointly by Indonesia, Australia and the World Bank. It uses innovative science and crowd sourcing techniques (OpenStreetMap, OSM) to create realistic disaster and hazard impact scenarios for better planning, preparedness and response activities. It is in demand by disaster managers across Indonesia and around the world.
How does it work?
InaSAFE provides a simple but rigorous way to combine data from communities, local governments and scientists to help assess the possible impact of future disaster events on communities, assets and infrastructure. It also calculates the resources required to support affected populations.

Who can use it?
Anyone with basic computer skills can learn to use InaSAFE. The software leads the user through the process of locating their data, choosing an impact function and assessing the likely impact that a disaster will have on a selected community.

Where does the data come from?
InaSAFE is designed to use and combine existing and new data from communities, local governments and science agencies. Where spatial data doesn’t exist, external tools such as OpenStreetMap (www.learnOSM.org) are available for communities and disaster managers to map assets that are important to them.

Where do I get more information?
Visit the InaSAFE website @ www.inasafe.org

**Comment by Charlotte-Morgan** [comment]
Hi @MariaSolovyeva 

Fredy & I agree to skip the action lists - ie no new action text required

**Comment by fredychandra** [comment]
sorry @MariaSolovyeva  I just want to clarify and revise what I mean is not exactly the EWS itself but more sound like "How will an analysis output of InaSAFE could disseminate. This is to avoid bias information about InaSAFE function. As agree with Charlotte, we skip also for the EWS or evacution symbol :). Thanks

**Comment by Charlotte-Morgan** [comment]
ok - sounds like we are done!!
thanks @fredychandra

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva - when you are done. 
Please post for final checks then we need to go to production: 
 - [ ] AIFDR to approve final version.
- [ ] Maria to send materials to @Sindhunata 
- [ ] Sindhunata to arrange printing - please recommend how many (maybe find out from printer what job sizes are available)
- [ ] @timlinux takes some to FOSSASIA
- [ ] @fredychandra takes some to Sendai
- [ ] Charlotte goes on holiday :)

Thanks everyone!!

**Comment by MariaSolovyeva** [comment]
Here are the final versions:

![postard1b](https://cloud.githubusercontent.com/assets/10400420/6522825/95678e52-c3fa-11e4-8f04-b8d03db03f81.jpg)
![postard2b](https://cloud.githubusercontent.com/assets/10400420/6522828/98f5cfde-c3fa-11e4-8314-1c790b54b86b.jpg)

**Comment by Charlotte-Morgan** [comment]
looking

**Comment by Charlotte-Morgan** [comment]
@ Maria - tweaks please.
Front: remove logo from bottom and center the "Better Planning Save Lives" text
Back: please reorder logos left to right as per the image attached
https://cloud.githubusercontent.com/assets/5743135/6521865/64c657c8-c40f-11e4-9a9d-9ff1ed0ba13b.png

Text edits - by section:
What is InaSAFE - change "software and was" to "software that was"
Where does the data ... - change url from "www.learnOSM.org" to "www.openstreetmap.org"
... more information - remove "@"
how does it work - do not allow hyphenation "disaster"

:) thanks !!

**Comment by MariaSolovyeva** [comment]
@Charlotte-Morgan , here are the latest changes :)
![postard1b](https://cloud.githubusercontent.com/assets/10400420/6523498/7f14b790-c401-11e4-8def-4e06cb588aad.jpg)
![postard2b](https://cloud.githubusercontent.com/assets/10400420/6523499/7f157504-c401-11e4-9464-d7f692406a74.jpg)

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva - you are a star.
LGTM
+1 approved

**Comment by timlinux** [comment]
That looks awesome - thanks @MariaSolovyeva

**Comment by MariaSolovyeva** [comment]
Thank you, @Charlotte-Morgan  and @timlinux!

@Sindhunata, the files just went to you with e-mail.

**Comment by Sindhunata** [comment]
Dear all. 
I am going to print the post card at 2PM. I am planning to print it 500 pieces on Art Carton 230gr.
Let me know if someone has any thought about it. The post card will be sent directly to AIFDR office.

**Comment by Sindhunata** [comment]
The postcards are being printed, and we can expect those to arrive at AIFDR office by Monday.
As for now, I have spoken with @fredychandra, and we are going to produce 100 CDs.
@fredychandra came up with the idea to put a little bit of Makassar's cultural ornament to the design.
So I added their wood carving style.

So here is the design, 50 CDs be produced with the upper one, vice versa. 
It will be produced starting from tomorrow, let's hope the CDs will be done on Monday.
Let me know if someone has any thought about it.

![final](https://cloud.githubusercontent.com/assets/10645858/6540801/f194c78c-c4e3-11e4-9a8e-a6d0a4a2e2ed.png)

**Comment by Charlotte-Morgan** [comment]
Hi Sindhu
This looks great. Is it possible to change the InaSAFE web address to all lower case as per feedback to Maria for postcard? If not, please proceed as it is.
Also AIFDR office is closed Monday for a public holiday. Maybe deliver to AIFDR Tuesday or HOT Monday as Tim and Akbar will be at there on Monday.
Regards
Charlotte

Sent from my iPhone

On 7 Mar 2015, at 4:10 pm, Sindhunata <notifications@github.com<mailto:notifications@github.com>> wrote:


The postcards are being printed, and we can expect those to arrive at AIFDR office by Monday.
As for now, I have spoken with @fredychandra<https://github.com/fredychandra>, and we are going to produce 100 CDs.
@fredychandra<https://github.com/fredychandra> came up with the idea to put a little bit of Makassar's cultural ornament to the design.
So I added their wood carving style.

So here is the design, 50 CDs be produced with the upper one, vice versa.
It will be produced starting from tomorrow, let's hope the CDs will be done on Monday.
Let me know if someone has any thought about it.

[final]<https://cloud.githubusercontent.com/assets/10645858/6540801/f194c78c-c4e3-11e4-9a8e-a6d0a4a2e2ed.png>

—
Reply to this email directly or view it on GitHub<https://github.com/AIFDR/inasafe/issues/1659#issuecomment-77680572>.

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
-------------------------------------------------------------------------------------------------------------------------

**Comment by Sindhunata** [comment]
Yes it is possible. 
I think it would be better if we send all the materials to the AIFDR office on Tuesday. 
Unless @timlinux wants it the other way, let me know your preference @timlinux.

Best,
Sindhu 

![inasafe cd](https://cloud.githubusercontent.com/assets/10645858/6541242/8bff4270-c4f8-11e4-901a-b4e9665730ad.png)

**Comment by timlinux** [comment]
Hi

@Sindhunata yes sending on Tuesday would be good. A few comments on your CD designs:

-[ ] 'A free software' -> this is not good english and also not a good way to represent it as open source, can you rather say 'InaSAFE is free and open source software that produces realistic natural hazard impact scenarios for better planning, preparedness and response activities'
-[ ] We should really include the 'Better planning saves lives!' tag line on all materials
-[ ] For the CD sticker, the hole cut out is going to make the text pretty much unreadable - can you please move it so that it is up above the hole and then below the hole add the tag line?
- [ ] We want to achieve visual consistency, so using the same background orange as the postcard would be best, and perhaps you can use the same wavey line on the orange / white separation line?

**Comment by Sindhunata** [comment]
@timlinux have a quick look Tim, and let me know ASAP so that I can send it to the printing+burning guy.
![cd fin](https://cloud.githubusercontent.com/assets/10645858/6545000/5651c7be-c59e-11e4-904d-795e18d4a548.png)

**Comment by timlinux** [comment]
Sindhu that looks brilliant! +1 to go with it.  I suggest to use the lighter orange, but either colour variety will be great I think.

**Comment by timlinux** [comment]
@Sindhunata Could you please provide me with the final source documents (gimp xcf / photoshop psd or whatever it is) so I can add it to the inasafe-graphics repo?

Thanks

Tim

**Comment by Sindhunata** [comment]
Sure, it is .svg, I will send it to your email as it is unsupported in here. 
By the way, all of the materials are already in the printing agency. Expect them to arrive at AIFDR office by Tuesday.

Best,
Sindhu
