### ISSUE TITLE
Bug: Error with Tsunami Impact on Population

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1688]
# Problem
Two errors reported when IFW completes processing Maumere tsunami impact on population.

# Type Error
```
Problem

The following problem(s) were encountered whilst running the analysis.

TypeError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

disconnect() failed between 'loadFinished' and 'unislot'
Diagnostics (click for details)

In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\dock.py", line 1413, in layer_changed self.wvResults.impact_path = layer.source()
In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\message_viewer.py", line 110, in impact_path self.show_report()
In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\message_viewer.py", line 314, in show_report self.load_html_file(self.report_path)
In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\message_viewer.py", line 340, in load_html_file self.load_html(HTML_FILE_MODE, file_path)
In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\gui\widgets\message_viewer.py", line 379, in load_html self.loadFinished.disconnect(self.html_loaded_slot)
```
# Attribute Error
Problem

The following problem(s) were encountered whilst running the analysis.

AttributeError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

Error loading impact layer.
'WizardDialog' object has no attribute 'get_exposure_layer'
Diagnostics (click for details)

In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\utilities\analysis_handler.py", line 401, in completed qgis_impact_layer, engine_impact_layer)
In file "C:/Users/localadmin/.qgis2/python/plugins\inasafe-dev\safe\utilities\analysis_handler.py", line 500, in show_results exposure_layer = self.parent.get_exposure_layer()
```

# proposed solution
make it happy

**Comment by akbargumbira** [comment]
For the Attribute Error part, fixed here in develop: https://github.com/AIFDR/inasafe/pull/1696, here in master: https://github.com/AIFDR/inasafe/pull/1701
