### ISSUE TITLE
Bug: IFW fails to complete Flood impact on roads

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1690]
# problem
InaSAFE causes QGIS crash dump when  Flood Raster impact on roads.

**Comment by akbargumbira** [comment]
Hi @Charlotte-Morgan, can you copy the error log here? It's fine in my computer from develop and master branch:
![flood_roads](https://cloud.githubusercontent.com/assets/992519/6455406/49f01ad2-c186-11e4-8c2e-ef96775dcb78.png)

**Comment by timlinux** [comment]
I'm assigning this to you @cchristelis

**Comment by cchristelis** [comment]
I am also running this IF successfully on my machine. Am I missing anything @Charlotte-Morgan? Is there perhaps any additional information that could help me reproduce this problem?

![screenshot from 2015-03-11 23 45 23](https://cloud.githubusercontent.com/assets/2319504/6607603/bd9ecd0c-c848-11e4-9745-5a373df5bed1.png)
