### ISSUE TITLE
InaSAFE 3.0: we need to update the training data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1695]
# problem
we need to update the InaSAFE training data & reflect this in the updated training docs

# why
we are building a geonode to share InaSAFE training data and want to ensure that the data are current and match the latest training materials

# proposed solution
- [ ] update data and add new data so that results are more up to date
- [ ] ensure data are available for the new impact functions that have been developed
- [ ] use data for which we have known metadata

# action
- [ ] @fredychandra will download new OSM buildings and roads for the following areas
* Jakarta
* Padang
* Maumere
* Merapi
- [ ] we will continue to use the same hazard data
- [ ] we will use newly modelled popmap data with metadata

- [ ] @iyan31 @adissadis to suggest other changes to the above proposal or additional data that should be included in a standard training pack.

# cc
@gavin @timlinux

**Comment by fredychandra** [comment]
@Charlotte-Morgan I am on progress downloading the OSM data.

**Comment by Charlotte-Morgan** [comment]
i think this is done - we are working on data for 3.2 now :)
