### ISSUE TITLE
Selecting analysis area leaves blue box covering whole map

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1746]
# Problem

When I select the analysis area in master, the background in covered in a blue box which is not removed when I make my selections.

This is a regression and there was a previous ticket about this.

# Proposed solution

Investigate why the issue happens, fix and apply to master and develop

**Comment by timlinux** [comment]
See also #1417

**Comment by timlinux** [comment]
@Gustry can you take a look at this please?

**Comment by Gustry** [comment]
@timlinux  I can't replicate it. Both on master and develop, the blue background is removed when the windows is being closed.
I tried with the cancel button, the selection on the map, manual selection.
I get only the blue edges, which seems to be normal, I can toggle rubber bands from the toolbar.

**Comment by Gustry** [comment]
According to @akbargumbira on hipchat, I should try projects which are in inasafe_data. I tried all of them, but I can't still replicate.
The blue background is removed each time.
However, I noticed this little bug : https://github.com/AIFDR/inasafe/issues/1752

**Comment by timlinux** [comment]
One theory I have about this is that it could be a side effect of having both InaSAFE master and InaSAFE develop loaded at the same time and double slot calls taking place. It would be good if the next time this issue raises its head that we check that there is only one InaSAFE copied into the QGIS plugins dir.

I am going to close out this issue as it is hard to replicate.
