### ISSUE TITLE
We need an InaSAFE skin for geonode

### ISSUE THREAD

**Issue by gubuntu** [AIFDR/inasafe#1753]
IsaSAFE's GeoNode instance, which is (will be) at http://geonode.inasafe.org needs to be themed to fit in with the rest of the InaSAFE ecosystem. 

See 'Bootstrap and JQuery' section at http://geonode.org/dev_features.html for an overview of the technologies GeoNode uses. Most of the files to work on are probably here: https://github.com/GeoNode/geonode/tree/master/geonode/static/geonode.

I've saved a static copy of the geonode home page, let me know if you need it and I'll email it.

**Comment by MariaSolovyeva** [comment]
Hello @gubuntu and @timlinux ,

Here is a mockup of the InaSAFE's GeoNode homepage. I hope the menu is not too complicated. As the link to the GeoNode will go from  InaSAFE > Users > Data, I kept the same structure and added the sublinks of the page here. We will just have to change the intro text, and the blocks intros as well.


![data2](https://cloud.githubusercontent.com/assets/10400420/7586368/ea4a5942-f8b4-11e4-967a-2b9079d774d6.png)

**Comment by gubuntu** [comment]
Nice @MariaSolovyeva ! ...seeing it deployed now at http://geonode.inasafe.org. Please note where the style is and how to deploy it.

**Comment by MariaSolovyeva** [comment]
We need to edit the intro text on the main page of geonode.
