### ISSUE TITLE
Impact Report Mixin

### ISSUE THREAD

**Issue by cchristelis** [AIFDR/inasafe#1765]
# Problem

The current IF inheritance architecture follows the commonality of layer types interacting. This is helping consolidate the impact function calculations. The reports have commonality along a different level. This is mainly along the exposure type. 

# Proposed Solution

Factor the report commonality into a Mixin class. This class will provide the IF with the reporting methods as well as specific methods that can be overwritten in the case of specialization.

**Comment by cchristelis** [comment]
Hi @akbargumbira,

I had a bit of a think about the above issue and have made a first order prototype. Have a look at the pull request and tell me what you think.

**Comment by cchristelis** [comment]
The nice thing about using the same functionality is there is now uniformity throughout the reports.

NEW:

![new_building_affected_by_earthquake_nexis_table pdf-0](https://cloud.githubusercontent.com/assets/2319504/6965686/cb95a4aa-d953-11e4-8465-d09f8e966597.jpg)
![new_building_affected_by_earthquake_nexis_table pdf-1](https://cloud.githubusercontent.com/assets/2319504/6965687/cb9e50c8-d953-11e4-9b6e-eb437c93e0d4.jpg)
![new_building_affected_by_earthquake_table pdf-0](https://cloud.githubusercontent.com/assets/2319504/6965688/cba77f54-d953-11e4-8120-db44f4d752bd.jpg)
![new_building_affected_by_earthquake_table pdf-1](https://cloud.githubusercontent.com/assets/2319504/6965689/cbac5cb8-d953-11e4-8103-da8e1b1adce3.jpg)
![new_buildings_affected_by_volcanic_buffered_point_table pdf-0](https://cloud.githubusercontent.com/assets/2319504/6965690/cbaf9de2-d953-11e4-9111-4963fae2d693.jpg)
![new_buildings_affected_by_volcanic_buffered_point_table pdf-1](https://cloud.githubusercontent.com/assets/2319504/6965691/cbbbeec6-d953-11e4-8224-968d5434309a.jpg)
![new_buildings_affected_by_volcanic_hazard_zone_table pdf-0](https://cloud.githubusercontent.com/assets/2319504/6965692/cbe0a310-d953-11e4-9257-3ed5aa1eeba9.jpg)
![new_buildings_affected_by_volcanic_hazard_zone_table pdf-1](https://cloud.githubusercontent.com/assets/2319504/6965693/cbe7f8cc-d953-11e4-8862-b6cc8c30ff3c.jpg)
![new_buildings_affected_generic_table pdf-0](https://cloud.githubusercontent.com/assets/2319504/6965694/cbed09f2-d953-11e4-8b8d-5d23d46e1c1a.jpg)
![new_buildings_affected_generic_table pdf-1](https://cloud.githubusercontent.com/assets/2319504/6965695/cbf46256-d953-11e4-8bfc-979d5d43afdc.jpg)
![new_buildings_inundated_raster_continuous_table pdf-0](https://cloud.githubusercontent.com/assets/2319504/6965696/cbfa0026-d953-11e4-8ce3-6109decb5c0b.jpg)
![new_buildings_inundated_raster_continuous_table pdf-1](https://cloud.githubusercontent.com/assets/2319504/6965697/cc0b637a-d953-11e4-8637-6b65f00d4112.jpg)
![new_buildings_inundated_vector_osm_table pdf-0](https://cloud.githubusercontent.com/assets/2319504/6965698/cc173dbc-d953-11e4-840f-d38f423d65ac.jpg)
![new_buildings_inundated_vector_osm_table pdf-1](https://cloud.githubusercontent.com/assets/2319504/6965699/cc1fa286-d953-11e4-9b88-11cd0424e977.jpg)
![new_buildings_inundated_vector_qgis_table pdf-0](https://cloud.githubusercontent.com/assets/2319504/6965700/cc237802-d953-11e4-8512-ee89a5b2e664.jpg)
![new_buildings_inundated_vector_qgis_table pdf-1](https://cloud.githubusercontent.com/assets/2319504/6965701/cc2a75c6-d953-11e4-867b-6c9e7a435c97.jpg)

OLD:
![old_affected_by_volcanic_buffered_point_table pdf](https://cloud.githubusercontent.com/assets/2319504/6965702/cc30554a-d953-11e4-8a47-e7fadced5e74.jpg)
![old_buildings_affected_by_volcanic_hazard_zone_table pdf](https://cloud.githubusercontent.com/assets/2319504/6965703/cc3ed1e2-d953-11e4-8806-046dbb634a16.jpg)
![old_buildings_affected_generic_table pdf](https://cloud.githubusercontent.com/assets/2319504/6965704/cc491c38-d953-11e4-8dae-7febb3466caf.jpg)
![old_buildings_inundated_raster_continuous_table pdf](https://cloud.githubusercontent.com/assets/2319504/6965705/cc53c23c-d953-11e4-924a-1d1028e7c697.jpg)
![old_buildings_inundated_vector_qgis_table pdf](https://cloud.githubusercontent.com/assets/2319504/6965706/cc60e0de-d953-11e4-99a0-15bbe6b37161.jpg)

**Comment by akbargumbira** [comment]
hi @cchristelis, from looking at the uniformity of the report, this is very nice! Thanks, I will look further tomorrow.

**Comment by cchristelis** [comment]
The mixin for buildings hazard has been merged and is in the current release. We should continue with the population as well as the roads reports.
I am working on the population mixin now.

**Comment by lucernae** [comment]
Hi @akbargumbira @cchristelis , I'm trying to create the new 12 IF base classes, then I found out that the roads and buildings have different reports. I'm not sure what to do until I read this. 

So, CMIIW, we will have a group of IF base classes  and a group of ReportMixin, and then we will pair each other for specific IF? This is just to make sure that I'm in the right track.

**Comment by cchristelis** [comment]
Hi @lucernae, 
I've started with the work on the population report mixin and both that and the roads one will be done by 3.2. 

In principle yes, the specific IF will be a combination between Report Mixin and IF calculation.

**Comment by akbargumbira** [comment]
@lucernae report mixin should be used in the implementation of an IF, not in the base class or 12 generic classes.

**Comment by cchristelis** [comment]
Making the Population reports uniform required a bit of redesign, since the concepts are displayed quite differently as these where each developed in semi-isolation. I will attach some to give examples. 

In order to unify the look, feel and experience of the reports, the following changes are made to the impact summary: 

The concept that seems to be most important in most of the reports is the concept of evacuated population. This is the number of people that need to be planned for. Planning may include food, shelter, water etc. So this will be the first number shown on the report.

Then there is a concept of affected population breakdown. If the impact function has categorized impact levels or effect types then these are listed here. These may include affected by impact category, fatalities etc.

Then finally an informative number of unaffected population is given.

The rest of the elements in the report, minimum needs for evacuated population, action checklist and notes are only slightly tweaked where necessary.

Current population impact reports:
[Earthquake_impact_to_population2_table.pdf](https://github.com/AIFDR/inasafe/files/507/Earthquake_impact_to_population2_table.pdf)
[Earthquake_impact_to_population_table.pdf](https://github.com/AIFDR/inasafe/files/508/Earthquake_impact_to_population_table.pdf)
[People_affected_by_flood_prone_areas_table.pdf](https://github.com/AIFDR/inasafe/files/509/People_affected_by_flood_prone_areas_table.pdf)
[People_in_each_hazard_areas_(low,_medium,_high)2_table.pdf](https://github.com/AIFDR/inasafe/files/510/People_in_each_hazard_areas_.low._medium._high.2_table.pdf)
[People_in_each_hazard_areas_(low,_medium,_high)_table.pdf](https://github.com/AIFDR/inasafe/files/511/People_in_each_hazard_areas_.low._medium._high._table.pdf)
[People_in_need_of_evacuation2_table.pdf](https://github.com/AIFDR/inasafe/files/512/People_in_need_of_evacuation2_table.pdf)
[People_in_need_of_evacuation_table.pdf](https://github.com/AIFDR/inasafe/files/514/People_in_need_of_evacuation_table.pdf)
[Population_affected_by_each_class_table.pdf](https://github.com/AIFDR/inasafe/files/513/Population_affected_by_each_class_table.pdf)

Example of a new report:
[People_in_need_of_evacuation2_table.pdf](https://github.com/AIFDR/inasafe/files/515/People_in_need_of_evacuation2_table.pdf)
