### ISSUE TITLE
OSM Downloader should always use extent in EPSG:4326

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1770]
# Problem

Currently if I use e.g. EPSG:3857 and try to use the downloader, it displays coordinates in m based on the spherical mercator projection and the download fails.

![inasafe openstreetmap downloader_023](https://cloud.githubusercontent.com/assets/178003/6884315/e5a23c66-d5eb-11e4-9c85-c8b46d613570.png)

# Proposed solution

- [x] For the OSM Downloader ensure that the CRS for extent coordinates is always EPSG:4326
- [x] Ensure that for extent selector, existing behaviour is not broken

**Comment by Gustry** [comment]
The extent selector doesn't use the same method.
