### ISSUE TITLE
BUG: test not working

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1774]
this is a dummy ticket

**Comment by timlinux** [comment]
@Charlotte-Morgan can you provide a screenshot and some sample data please

(standing by for a picture of a dummy)

**Comment by Charlotte-Morgan** [comment]
hi @tim - can we add Iwan please. His github name is samnawi

**Comment by Charlotte-Morgan** [comment]
i have lots of tickets to assign to him :)

**Comment by timlinux** [comment]
Looks like @samnawi has already been sent an invite - he just needs to accept it
