### ISSUE TITLE
InaSAFE couldn't load at Startup (Python Error)

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1784]
# Problem
I cloned InaSAFE from Github and when i want to start QGIS, It showed python error like this
![inasafe_9](https://cloud.githubusercontent.com/assets/2520159/7109487/f4bf574a-e1c8-11e4-8146-035ff7fe9651.png)
This error only appeared in My Laptop and when i copied InaSAFE and gave to my friend, it didn't show an error like mine.

# Platform
I'm using QGIS 2.8.1 with Windows 64bit and InaSAFE copied from Github (branch develop)

cc:
@timlinux

**Comment by lucernae** [comment]
I think this is because of an old settings still persists in your computer, @adissadis .
I will look into it some more

**Comment by adissadis** [comment]
@lucernae What do you mean about old setting still persists? It is for InaSAFE or QGIS?

If i'm using InaSAFE from QGIS plugin repository, the problem won't appear. It only appear if i use InaSAFE from Github.

**Comment by lucernae** [comment]
@adissadis that is just a first guess. Does your friend also uses InaSAFE from Github?

**Comment by adissadis** [comment]
@lucernae yes it does. All of my friends use InaSAFE from Github and they didn't have any error like me.

**Comment by lucernae** [comment]
@adissadis can you look at the InaSAFE options and verify that the custom organization logo exists? (In the template options tab)

**Comment by adissadis** [comment]
@lucernae i assume you want me to download InaSAFE from QGIS repository first and then look at InaSAFE Options right?

Because i cant use InaSAFE from Github and whenever the error appear, InaSAFE doesn't appear in QGIS. If i disable and enable the plugin through Manage and Install plugin, the error still appear.

**Comment by lucernae** [comment]
@adissadis yes that's right, sorry for not pointing it out :). This is just to make sure that the issue is caused by non existent custom organization logo. If it really does, then I have to do some error handling in the code.

**Comment by akbargumbira** [comment]
@lucernae it could also be that the org logo path is still using the old
style resources path e.g :plugins/x/y/z. I thought @timlinux has fixed
that? Do the checking if the file exists and you can just use the default
logo if it doesn't exist

**Comment by lucernae** [comment]
@akbargumbira the old logo path is already fixed. File exist check doesn't exist yet (pardon the pun :p).

**Comment by akbargumbira** [comment]
@lucernae cool! Just double check with the value from Adis's logo path. If
the value is still using the old style resources path, we need to replace
it to the new one in qsettings

**Comment by adissadis** [comment]
I think the logo path is wrong, from InaSAFE Option, it pointed:

C:\Users\Sony\.qgis2\python\inasafe\resources\img\logos\supporters.png

But actually it must be like this:

C:\Users\Sony\.qgis2\python\plugins\inasafe\resources\img\logos

So, it missing "plugin" folder before reach InaSAFE folder.

**Comment by lucernae** [comment]
@adissadis @akbargumbira , noted. I will try to fix it by the end of the day

**Comment by adissadis** [comment]
The problem fixed now, i adding "plugin" in logo path and when i use the InaSAFE from Github, the problem doesn't appear again.

Thanks @lucernae and @akbargumbira !

**Comment by lucernae** [comment]
@adissadis I add some error handling in the code. You can pull the latest develop and try to replicate the error again. If it is fixed, we can close the ticket :)

**Comment by adissadis** [comment]
@lucernae It fixed now. Thanks for error handling in the code that you put into the script. 

We can closed the ticket now :)
