### ISSUE TITLE
Complete the postprocessors with the descriptions, help text, etc

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1792]
This doesn't look good for user
![postprocessing](https://cloud.githubusercontent.com/assets/992519/7152011/89e26fac-e35d-11e4-8a38-b354279e2e3d.png)

**Comment by timlinux** [comment]
Agreed, yes - @Jannes123 leave these for me and you focus on the parameters stuff. If you already did some descriptions for these in your branch please make a small PR for it and I will edit it.
