### ISSUE TITLE
Reverse the way we treat layers in IF

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#1797]
Right now, in the IF, we need to have the layers as safe layer and pass it to the IF (if it's QgsMapLayer we wrap it using QgsWrapper class before - in the impact calculator class).

The proposed solution is that we always pass QgsMapLayer to IF, and convert it to safe layer instead in the IF if the IF is the old style IF

**Comment by akbargumbira** [comment]
- [ ]  Remove packing unpacking layers. Thus remove functions like extract_layers, get_layer, etc in safe.enging.core
 - [ ] TBD

**Comment by timlinux** [comment]
Yes I also like the idea of expecting QgsMapLayers and then casting them off to read_layer (gotta change that name some time) if needed.

**Comment by timlinux** [comment]
Maybe this is already taken care of with the SafeLayer class we added-  @ismailsunni to check

**Comment by ismailsunni** [comment]
We somewhat have "covered" this in SafeLayer class.

In current version, all IF receive SafeLayer as input. When we want to use IF, we set the hazard, exposure, and aggregation attributes. This is where the conversion happened (in base class of IF)

All IFs accept all types of layer (SafeLayer, Layer, QgsMapLayer), then convert it to SafeLayer with match data type in layer attribute.

We don't have functions like extract_layers, get_layer, etc in safe.engine.core also.

+1 for closing this.

cc @timlinux
