### ISSUE TITLE
BUG: EQ categorical IF on population uses irrelevant default thresholds

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1807]
# problem
the default threshold values of 0.34, 0.67, 1 seem a little low for MMI values and return 0 impacted people.

I'm not sure what these defaults relate to.

# proposed solution
Generic impact functions should read key words and load different default values depending on the hazard type.

Users should be warned to check the thresholds and given some guidance on relevant values.

![Uploading image.png . . .]()

**Comment by timlinux** [comment]
These numbers make no sense for MMI - perhaps Hyeuk can help by suggesting sensible defaults.

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan @timlinux 
I am not sure this is the correct behavior. IIRC, we decided that categorical IF will accept hazard layer that has hazard value that has been normalized or categorized, not raw data like MMI or flood depth.
If we have hazard layer that has raw data (e.g. MMI or flood depth), we should use the EQ or Flood IF.

**Comment by timlinux** [comment]
Ah yes @ismailsunni you are right - but we should not be tagging MMI data as categorical, rather as continuous then right? In my view it **is** still continuous, but just with a constrained min max.

**Comment by ismailsunni** [comment]
@timlinux Yes, MMI data should not be tagged as categorical.

For EQ IF (MMI), we don't ask the user about the threshold. It's hardcoded in the IF.
For Flood IF (depth), we ask the user about the threshold (which range will will categorized as inundated area).

**Comment by timlinux** [comment]
@ismailsunni I more specifically was suggesting that we do not allow the user to set a categorical tag if the units are MMI

**Comment by ismailsunni** [comment]
@timlinux 
Yes, we have that constraint for it already.
```python
                'hazard': {
                    'layer_mode': layer_mode_continuous,
                    'layer_geometries': [layer_geometry_raster],
                    'hazard_categories': [
                        hazard_category_single_event,
                        hazard_category_multiple_event
                    ],
                    'hazard_types': [hazard_earthquake],
                    'continuous_hazard_units': [unit_mmi],
                    'vector_hazard_classifications': [],
                    'raster_hazard_classifications': [],
                    'additional_keywords': []
                },
```
For generic IF, they don't use `unit_mmi`. So, if the user set the unit keyword to mmi, InaSAFE will only show the ITB and Pager EQ IF.

It's different case if the hazard is in mmi, but the user set the keyword to not mmi.

**Comment by timlinux** [comment]
OK good thanks @ismailsunni I'm going to close this out. @Charlotte-Morgan feel free to re-open if you do not feel it is a fair treatment of the issue.
