### ISSUE TITLE
We need to manage rounding in the minimum needs dialogue - wizard

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1810]
# Problem
The minimum needs dialogue summary in the IF Wizard shows rounded values resulting in some values being zero. This is misleading.
# Proposed solution
These values should either be rounded to 1 decimal or rounded up to avoid presenting zero values. see the screenie below:
![image](https://cloud.githubusercontent.com/assets/5743135/7195356/72caa104-e4e8-11e4-946e-6140e95044a1.png)

# cc
@cchristelis @borysiasty @KathrynOwen

**Comment by lucernae** [comment]
What about the postprocessors's section?

Is that supposed to be presented like that? e.g.  --> Gender: []

**Comment by lucernae** [comment]
Does the fix looks good? I rounded the decimal to 1 decimal place
I need some suggestions for postprocessors tab, though.
I didn't realize that it was already assigned to @akbargumbira previously :O.

![wizard](https://cloud.githubusercontent.com/assets/831865/7239070/3a7df3be-e7d1-11e4-8fa1-c7ad3c64829d.png)
