### ISSUE TITLE
Error: Insufficient Overlap - new suggestion

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1811]
# Problem
the insufficient overlap error also results when the "set analysis extent" has been set and does not coincide with the extent of the current hazard and exposure data. It is easy for this to happen as the current analysis extent persists from the previous session.

# Proposed Solution's
1. Zoom to the current analysis extent when QGIS Opens & show the user that an extent is set.
2. add the following new suggestion to the top of the suggestions
"Check that the InaSAFE Analysis Area coincides with your data."

# Error Message
This analysis will calculate the impact of Flood like Jakarta - 18 Jan 2013 on Buildings .

The following postprocessors will be used:

Building type: Calculates building types related statistics.
Problem

The following problem(s) were encountered whilst running the analysis.

InsufficientOverlapError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

A problem was encountered when trying to determine the analysis extents.
There was insufficient overlap between the input layers and / or the layers and the viewable area. Please select two overlapping layers and zoom or pan to them or disable viewable area clipping in the options dialog. Full details follow:
Failed to obtain the optimal extent given:

Hazard: C:/WorkSpace/InaSAFE Materials/TrainingDataPackages/InaSAFEv2.0/InaSAFEv2.0/data/flood_osm_bpbd18113_Jakarta.shp
Exposure: C:/WorkSpace/InaSAFE Materials/TrainingDataPackages/InaSAFEv2.0/InaSAFEv2.0/data/buildings_osm_jakarta.shp
Viewable area Geo Extent: [106.3240125, -6.0805981, 106.4014095, -6.0093114]
Hazard Geo Extent: [106.68558699994026, -6.37262199980529, 106.97397499984652, -6.0888509996737525]
Exposure Geo Extent: [106.6873657556977, -6.384319156045584, 106.99007797401514, -6.0934352942912895]
Viewable area clipping enabled: True
Details: Bounding boxes of hazard data, exposure data and viewport did not overlap, so no computation was done. Please make sure you pan to where the data is and that hazard and exposure data overlaps.
Diagnostics (click for details)

In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1152, in accept self.analysis.setup_analysis()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 688, in setup_analysis raise e

**Comment by timlinux** [comment]
Hi

Part 1) of your solution is problematic in that QGIS has its own behaviour when opening an existing project - it zooms to the last used extent for that project. I think we might cause confusion if we override this behaviour.

For part 2 this is what I have come up with:

1) If no layers are loaded, show the normal getting started message
2) if layers are loaded and the extents overlap, show the message as per the screenshot below

![screen shot 2015-04-21 at 08 10 31](https://cloud.githubusercontent.com/assets/178003/7246545/4e92638e-e7ff-11e4-84c1-f6407253b0b0.png)


3) if layers are loaded and their extents, or the extents of the analysis area do not overlay, show the message as per the screenshot below.

![screen shot 2015-04-21 at 08 16 51](https://cloud.githubusercontent.com/assets/178003/7246550/5647be94-e7ff-11e4-8566-43b36fa36d8b.png)

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - that looks very neat and user friendly

**Comment by Charlotte-Morgan** [comment]
however - sometimes we get nice messages when we don't need them like:
- [ ] when an IF has finished running and you want to see the result panel
- [ ] when an IF has run and has turned the data off to show the result layer

**Comment by cchristelis** [comment]
@Charlotte-Morgan and @timlinux, 
If we keep the current behaviour, after running an IF, we could choose to run another, so then after the first run == before the next run.
Maybe we should only show this warning if the user attempts to hit run, because then we know they are attempting another run and need this info.

**Comment by timlinux** [comment]
Ok here is a fresh take on how we can manage the analysis behaviour - I think it will address all the various concerns and puts all the options relating to analysis extents in one place.

![screen shot 2015-04-24 at 20 34 18](https://cloud.githubusercontent.com/assets/178003/7326047/b2fe9f20-eac2-11e4-96c7-44665682dda5.png)

I made a short youtube clip to show how the warnings / notifications might work for extent issues / success.

https://www.youtube.com/watch?v=AQ92-eA_Cns

@Charlotte-Morgan I think that I can have this all working by the end of the weekend & would like to propose we do it for 3.1 as it will close this issue (and related issues to extents).

**Comment by timlinux** [comment]
Note to self: probably better to leave it for 3.2 as we discussed on our call and just roll back the messages for now so that we can do the minimal changeset to get the 3.1 release out.

**Comment by Charlotte-Morgan** [comment]
hi @timlinux 
+1 for roll back and just insert 1 line for 3.1 or do nothing.
+1 for new style warning that is in the top of the map window and not in the dock

**Comment by Charlotte-Morgan** [comment]
is 'intersection' a better word than union in this case - ie the common area not the combined area?
