### ISSUE TITLE
We need to get the geonode instance syled according to InaSAFE visual guidelines

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1817]
# Problem

We have http://geonode.inasafe.org now but it needs to be styled to look like the work @MariaSolovyeva has been doing on blogtest.inasafe.org

@gubuntu to assist with technical details as needed.

**Comment by gubuntu** [comment]
duplicate of #1753

**Comment by timlinux** [comment]
Closing as duplicate
