### ISSUE TITLE
We need to clean up the menu for InaSAFE

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1820]
# Problem

The menu for InaSAFE is not consistency in:

* standardisation of capitalisation
* ordering of items
* logical separation of items
* Redundant use of 'InaSAFE' throughout

![screen shot 2015-04-19 at 14 58 10](https://cloud.githubusercontent.com/assets/178003/7219572/c24c114e-e6a6-11e4-84fc-446442fe39e0.png)

# Proposed solution

* Standardise on mixed case capitliationan throughout
* Use ``QMenu::insertSeperator`` to logically separate items groups
* Order items by this scheme:

InaSAFE Menu
* General Options
* Minimum Needs Configuration
* -------------------- Separator -------
* Keyword Wizard
* Analysis Wizard
* -------------------- Separator -------
* Toggle Dock Window
* Toggle Scenario Outlines
* Define Analysis Area
* Save Current Scenario
* -------------------- Separator -------
* OSM Downloader
* Batch Runner
* Shakemap Gird Converter
* Minimum Needs Tool
* Impact Layer Merge Tool
* -------------------- Separator -------
* Add test Layers

# For comment

@AIFDR/doc-writers Please comment on how this proposed change will affect you. For now I am going to fix only the consistency of capitalisation and the ordering. If you agree, I will also change the menu entry names.

@Charlotte-Morgan please comment if proposed item ordering makes sense to you.

**Comment by timlinux** [comment]
![screen shot 2015-04-19 at 17 04 36](https://cloud.githubusercontent.com/assets/178003/7219915/3d0ff918-e6b6-11e4-8770-c3b8f1944fa7.png)

This is what my intermediate tweaked version looks like (for 3.1).

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux - this is a good move and in general makes sense.
In keeping with your proposal the "Add Some Test Layers" should be capitalised too.

Regarding ordering / grouping and separators; to me the logic goes something like this:
Configuration: Options, Min Needs
Wizards: Key Words, Analysis
Data: OSM, Shake Grid, Test data
Analysis: Scenario Outline, Set Analysis, batch runner
Merging / Saving: Merge, Save Scenario

I also like the idea of using consistent terms for buttons (Toggle) and tools & having the same terminology inside the tool windows. ie if you change the menu it should also be reflected in the window title.
My first reaction was that OSM downloader and Minimum Needs Tool were out of place (too low) and and that the Save Current Scenario was too  high ??

**Comment by adissadis** [comment]
+1 grouping idea

Based on grouping idea from Charlotee, I think for Scenario outline, set analysis and toggle dock window can be put into Configuration group. And also for analysis group we can put merging and save scenario there.

As far as i know, this changes maybe affected the screenshot and some step by step. But we don't have any problem for this idea.

Also, is it possible to put InaSAFE into the new menu bar? not under plugin but separate menu bar. Because it can useful for participant to find all the tools from InaSAFE plugin.

**Comment by Charlotte-Morgan** [comment]
+ 1 for these enhancements

**Comment by timlinux** [comment]
OK thanks for this feedback. @Charlotte-Morgan agreed getting the consistency carried through to the dialog titles and other used terminology. @adissadis ok your suggestions make sense. Putting InaSAFE into its own menu is possible - though maybe it would be better to put it into one of the established menus e.g. 'Analysis' since adding a new menu is often not desirable in terms of QGIS human interface guidelines.

**Comment by cchristelis** [comment]
Hi @Charlotte-Morgan, @adissadis and @timlinux:
For this release I've updated the PR to have the following behaviour (which is basically a merge of the ideas shared above.):
*Configuration*: General Options, Minimum Needs Configuration, Set Analysis, Toggle Dock Window, Toggle Scenario Outlines
*Wizards*: Keyword Wizard, Analysis Wizard
*Data*: OSM, Shake Grid, Minimum Needs Tool, Test data
*Analysis*: batch runner, Merge, Save Scenario

Or in a screenie:
![menureorder](https://cloud.githubusercontent.com/assets/2319504/7248836/43c7aede-e816-11e4-928c-2fb206488884.png)

**Comment by adissadis** [comment]
@timlinux oh ok if there're any guidelines for menubar, we stick under 'Pluggin' menu.


Hi @cchristelis In my opinion, i think it's better to create some grouping item, something like this:

Configuration -> General Options
                          Minimum Needs Configuration
                          Set InaSAFE Analysis Area
                          Toggle InaSAFE Dock
                          Toggle Scenario Outlines
Wizard -> InaSAFE Keyword Creation Wizard
                InaSAFE Impact Function Centric Wizard
Data -> InaSAFE OpenStreetMap Downloader
             InaSAFE Converter
             InaSAFE Minimum Needs Tool
             Add Some Test Layers
Analysis -> InaSAFE Batch Runner
                  InaSAFE Impact Layer Merge
                  Save Current Scenario
                  InaSAFE Keyword Editor

So, by adding some grouping, its looks more better I think. Not too long and more futureproof (if there any new feature added) Looks like this screenshot:
![Uploading Inasafe_13.png . . .]()

**Comment by cchristelis** [comment]
Hi @adissadis, 
Yeah, breaking it down is better and we should do that for 3.2. The screenie is just a partial implementation for 3.1.

**Comment by timlinux** [comment]
@timlinux to remove 'InaSAFE' prefix from each item

**Comment by timlinux** [comment]
![selection_008](https://cloud.githubusercontent.com/assets/178003/9276714/ea4adff8-42a5-11e5-91b5-e33d9e9b33bf.png)

We discussed using submenus vs separators - for now I have added submenus as it requires more work for the user to drop through many submenus. If our featureset grows a lot in the future we can go on to use submenus.
