### ISSUE TITLE
Parameters should not have nested scrollboxes

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1836]
# Problem

![scrollbox](https://cloud.githubusercontent.com/assets/178003/7233197/3835fe54-e780-11e4-8592-907a5effcd61.png)

We should avoid scrollboxes in scrollboxes...I feel like I am in Alice in Wonderland and they will take me down a rabbit hole :-)

# Proposed solution

@Jannes123 Please use only scrollbox for the top level parameters collection.

**Comment by lucernae** [comment]
Since this is a widget problem, I think you can assign it to me :)

**Comment by Jannes123** [comment]
@lucernae  did you get this sorted out or must I ?

**Comment by lucernae** [comment]
Not yet, but I will try to sort it out. Since it is for 3.2 we can focus on 3.1 release blocker first.
But, if you already fixed it, you can go on. 

I just realized that I changed the assigned. I was intending to ask first, previously.
