### ISSUE TITLE
We need to review the text for all impact function metadata.py files

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1843]
# Problem

Many of the phrases use incorrect grammar - we want our release to be filled with beautifully constructed sentances.

# Proposed solution

@timlinux to review all IF metadata files and make a PR with improved writing. @Charlotte-Morgan feel free to give my changes a once over when they are in.

**Comment by Charlotte-Morgan** [comment]
@timlinux - do you want me to look at any now?
