### ISSUE TITLE
We need to review the logic for classified raster population impact function

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1845]
# Problem

In ``safe/impact_functions/generic/classified_raster_population/impact_function.py`` we have logic like this:

```python
        # Calculate impact as population exposed to each class
        population = exposure_layer.get_data(nan=0.0, scaling=True)
        if high_t == 0:
            hi = numpy.where(0, population, 0)
        else:
            hi = numpy.where(data == high_t, population, 0)
        if medium_t == 0:
            med = numpy.where(0, population, 0)
        else:
            med = numpy.where(data == medium_t, population, 0)
        if low_t == 0:
            lo = numpy.where(0, population, 0)
        else:
            lo = numpy.where(data == low_t, population, 0)
        if high_t == 0:
            impact = numpy.where(
                (data == low_t) +
                (data == medium_t),
                population, 0)
        elif medium_t == 0:
            impact = numpy.where(
                (data == low_t) +
                (data == high_t),
                population, 0)
        elif low_t == 0:
            impact = numpy.where(
                (data == medium_t) +
                (data == high_t),
                population, 0)
        else:
            impact = numpy.where(
                (data == low_t) +
                (data == medium_t) +
                (data == high_t
```

The logic seems a little off to me - it makes assumptions about which thresholds may be undefined but does not check all the cross permutations. Perhaps I am not understanding the logic here.

# Proposed solution

@cchristelis please review the logic and tell me if I am daft.

**Comment by timlinux** [comment]
Note we should also check the other IF's that may be using derivative code.

**Comment by akbargumbira** [comment]
Agreed, the logic is a bit off and not direct.

**Comment by akbargumbira** [comment]
The flaw is for example if 0 is actually a classification of one of the 3 hazard areas (e.g 0 means low hazard area), this will only calculate the impact in the medium and high. That also happens for other permutation of the case one of the hazard areas is 0

**Comment by akbargumbira** [comment]
Fixed here https://github.com/AIFDR/inasafe/pull/1891
