### ISSUE TITLE
Philippine Minimum Needs profile break the options dialog.

### ISSUE THREAD

**Issue by cchristelis** [AIFDR/inasafe#1851]
When selecting the Philippine Minimum Needs profile and selecting "Earthquake Polygon" and "Population" exposure. Opening the Options dialog and closing it again via "OK" causes a python error.

**Comment by Jannes123** [comment]
Looks like there are still some old-style parameters hanging around or merged in.  Will fix those first I think that will solve most of the problems.

**Comment by Jannes123** [comment]
@lucernae it seems like the get_parameter function returns (0.0)  when called in function_options_dialog.py

**Comment by lucernae** [comment]
@Jannes123 I can't replicate the bug. But I do notices that I can't change Family Kits value. Is that also a bug? :v

**Comment by lucernae** [comment]
@Jannes123  I'm able to replicate it now. It seems dangerous because we can't modify some of the parameters because it already out of bounds.

**Comment by Jannes123** [comment]
@cchristelis seems like the precision of the nrs remaim fixed at 2 for resource parameters.  So when you put a nr like 0,04 in its fine but 0.0003 will create that bug.

**Comment by cchristelis** [comment]
Oh, so that is why we keep getting 0.00... I wonder whether we should increase the precision.

**Comment by Jannes123** [comment]
@cchristelis  #1868  PR contains that update

**Comment by Jannes123** [comment]
#1881 fixes this issue
