### ISSUE TITLE
An exception is being raised when running the Earthquake polygon on population test data.

### ISSUE THREAD

**Issue by cchristelis** [AIFDR/inasafe#1853]
The Earthquake Polygon hazard on the Population exposure test data causes the following exception.
```
Details

These additional details were reported when the problem occurred.

Error loading impact layer.
Input layer must be a InaSAFE spatial object. I got
Diagnostics (click for details)

In file "/home/christian/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1323, in completed qgis_impact_layer = read_impact_layer(engine_impact_layer)
In file "/home/christian/.qgis2/python/plugins/inasafe/safe/utilities/gis.py", line 348, in read_impact_layer raise Exception(message)
```

**Comment by lucernae** [comment]
I'm testing the same thing and InaSAFE doesn't spit any errors?

**Comment by cchristelis** [comment]
@lucernae, are you running this against develop with the latest commits included. It seems to be due to a recent commit. I'm assigning this to you @Jannes123.

**Comment by lucernae** [comment]
@cchristelis yes I'm running it against latest develop. @akbargumbira warns me about this #1854 though. I was trying to solve that issue actually.

**Comment by cchristelis** [comment]
@lucernae, I was looking to check the same problem, but when I ran it there was this problem. We were able to reproduce this on @Jannes123's machine.

**Comment by cchristelis** [comment]
The issue here is an overflow of #1851. The fact that that error prevents the user from selecting the correct name for the hazard_zone_attribute, causes the zones not to be found. This in turn leads to this problem. As you @lucernae, where using another profile you weren't able to reproduce.
