### ISSUE TITLE
Fix zero post processor in Earthquake Polygon + Population

### ISSUE THREAD

**Issue by lucernae** [AIFDR/inasafe#1854]
When we ran Earthquake Polygon Hazard and Population Exposure using the test data, the report succesfully computed but the postprocessor returns zero results.

**Comment by lucernae** [comment]
I have traced the problem and found that it is possible that it has the same root issue as #759.

# Problem

So, what happen is:
- The IF uses extent which is somewhat equal to the hazard extent, because it uses the hazard layer to put the population count. The IF runs normally and the impacted population is calculated correctly
- The aggregator uses optimal extent which is the same as the exposure extent. Unfortunately, the hazard extent is so big, that the centroid of the polygon is outside the extent. With the rule applied in issue #759, the polygon is excluded in the postprocessor calculations. This is what we expects to be in case of buildings. But, in this issue's case, this is not what we expects, the polygon should be included in the postprocessing part. Right now, it doesn't, because ALL of the polygons have centroid outside the aggregation extent.

Let me illustrate it with picture:

![image](https://cloud.githubusercontent.com/assets/831865/7259509/f0e86c44-e88d-11e4-9679-6ad38d1941a5.png)

That small box is our exposure layer, and effectively became the optimal extent. We can see that all the hazard polygons's centroid is outside the extent. With the same logic, this also applies to our Volcano KRB - Population dataset. 

Now, because this is a conflicting situation we need to discuss how are going to fix this?

- The issue in #759 says, we uses optimal extent to both the IF and aggregator to have a consistent count
- This issue now caused by optimal extent is used in aggregator. What we want instead is an extent that covers both the hazard and exposure extent.

# Suggestion

What I have in mind is to let the aggregator uses the resulting impact extent (the layer the IF produced). This way, Building IF still uses optimal extent for the aggregation, and Generic Classified Polygon Population IF will uses hazard extent (because the IF uses hazard layer to calculate the impact). That way everyone's happy. But, I think this still needs to be discussed to make sure that we didn't overlook things, or breaking other part of the systems.

# CC
@timlinux @akbargumbira @ismailsunni @cchristelis

**Comment by Charlotte-Morgan** [comment]
If the IF is counting the number of people affected inside the selected area, then the process should be either:
- [ ] clip the hazard raster to the analysis extent and write the output to the clipped polygon
or 
- [ ] write the output to a raster with the same cell size as the population data.

I'm thinking this should be the case for all polygon on raster analysis where hazard is polygon and exposure is raster.

It should not write the entire polygon and write that to the output.

**Comment by akbargumbira** [comment]
Agreed for both options (what you meant for the first option is  "clip the hazard POLY to the analysis extent..". Last night, I played around with the second option and it's working well. I will make a more comprehensive solution...
