### ISSUE TITLE
It is very unclear the different between the Flood (Experimental) and Flood

### ISSUE THREAD

**Issue by vdeparday** [AIFDR/inasafe#1860]
It is really confusing for the user to pick which one to use. I almost feel like we should not give the user two choices, we should just have only one and one that works.

There is also no description in the wizard:
![screen shot 2015-04-21 at 12 18 46 am](https://cloud.githubusercontent.com/assets/1036189/7257308/056a1084-e855-11e4-9000-dfdc63d5a8a9.png)

**Comment by timlinux** [comment]
Agreed - I would like to disable one for now - just want to test to see which works well in different scenarios

**Comment by akbargumbira** [comment]
I already removed it for 3.1
