### ISSUE TITLE
Warning about keywords missing even when no layer is selected

### ISSUE THREAD

**Issue by vdeparday** [AIFDR/inasafe#1861]
It is a little confusing as even when no layer is selected, the InaSAFE dialog is saying 'missing keyword' although all the layers have the proper keyword. Should be displayed only when a layer is selected

![screen shot 2015-04-22 at 2 08 39 am](https://cloud.githubusercontent.com/assets/1036189/7265092/8af630a4-e894-11e4-991c-ca4ddfb7f791.png)

**Comment by Charlotte-Morgan** [comment]
this is related to #1811 and some new error messages that need to be rolled back

**Comment by timlinux** [comment]
I'm actually curious to know what you did to get the legend to a state with no selected layers. For me even when I deselect all layers by clicking in the white space of the legend, I still have an active layer (as designated by the underlined font for the active layer in the legend.

**Comment by timlinux** [comment]
Ok I managed to replicate it here...working on a fix....

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - so this happens when you open an existing qgis project file. Is there a pull request for this? I think i have the latest dev and i't still getting the error
