### ISSUE TITLE
Flood polygon on population

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1883]
# Test environment:
Jakarta Flood Polygon
popmap10-all
jakarta districts
analysis run manually through doc.

Hey @akbar
thanks for adding this text to explain the analysis.

People are affected if in the area with the value of the affected field ("affected") equals to "1"

Can you please modify so that it reads
People are considered to be affected if they are within the area where the value of the hazard field ('affected') is "1".

I think this could be quite generic text for other impacts too??

**Comment by Charlotte-Morgan** [comment]
and can you move this up to the people affected area of the notes - if that is easy?

**Comment by Charlotte-Morgan** [comment]
Bug:there is a problem if i include aggregation to Jakarta districts.
it considers the district boundary as the hazard layer and counts all the people in jakarta

**Comment by Charlotte-Morgan** [comment]
re no data statement
current statement : "No data values in the exposure layer are treated as 0 when counting affected population or total population"

tweaked statement: "nodata" values in the exposure layer are treated as 0 when counting the affected or total population

**Comment by akbargumbira** [comment]
@Charlotte-Morgan what do you mean if you use aggregatin layer it will consider that layer as the hazard? I can't replicate it
