### ISSUE TITLE
We need to resolve the duplicate minimum needs text in Phillipines profile

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1888]
# Problem

The minimum needs IF options tab shows duplicate text:

![screen shot 2015-04-30 at 17 40 54](https://cloud.githubusercontent.com/assets/178003/7416503/1c89209a-ef60-11e4-9e2a-9ea6a3325f64.png)

This is because the Philippines profile contains the same entries for ``Resource description`` and ``Readable sentence``:

![screen shot 2015-04-30 at 17 43 43](https://cloud.githubusercontent.com/assets/178003/7416547/80e191ee-ef60-11e4-98a1-1d33dd1bf111.png)

(See ``resources/minimum_needs/Philippine Minimum Needs_en.json``)

# Proposed solution

I propose to fix this by simply editing the json file and using different descriptions between the resource description and readable sentance fields e.g.

![screen shot 2015-04-30 at 17 46 28](https://cloud.githubusercontent.com/assets/178003/7416601/e2b62718-ef60-11e4-8c57-ad3fc62f00b2.png)

**Comment by timlinux** [comment]
Note that users will need to remove their local profiles before they see the update.

**Comment by Jannes123** [comment]
PR #1894 contains the updated json file.  

git gave a warning :  CRLF will be replaced by LF in resources/minimum_needs/Philippine Minimum Needs_en.json

**Comment by Jannes123** [comment]
It seems like this issue was resolved either by me or @lucernae for master and develop branches. closing issue.
