### ISSUE TITLE
Create 12 intermediate base class

### ISSUE THREAD

**Issue by lucernae** [AIFDR/inasafe#1914]
This is a subtask of #1890 

List of 12 intermediate base classes:

- [x] ContinuousRasterHazardContinuousRasterExposure
- [x] ContinuousRasterHazardContinuousVectorExposure
- [x] ContinuousRasterHazardClassifiedVectorExposure
- [x] ClassifiedRasterHazardContinuousRasterExposure
- [x] ClassifiedRasterHazardContinuousVectorExposure
- [x] ClassifiedRasterHazardClassifiedVectorExposure
- [x] ContinuousVectorHazardContinuousRasterExposure
- [x] ContinuousVectorHazardContinuousVectorExposure
- [x] ContinuousVectorHazardClassifiedVectorExposure
- [x] ClassifiedVectorHazardContinuousRasterExposure
- [x] ClassifiedVectorHazardContinuousVectorExposure
- [x] ClassifiedVectorHazardClassifiedVectorExposure

**Comment by timlinux** [comment]
Please see also: https://www.lucidchart.com/invitations/accept/65997218-9953-474c-8905-0075638d128c

**Comment by lucernae** [comment]
Because we're not really sure on what to implement in the base class. Right now, I just put metadata checks and assign the base class to concrete IF implementations.

These are the lists:

## Inundation

### ClassifiedVHContinuousRE

- flood_polygon_population (FloodEvacuationVectorHazardFunction)

### ClassifiedVHClassifiedVE

- flood_polygon_roads (FloodVectorRoadsExperimentalFunction)
- flood_vector_building_impact (FloodPolygonBuildingFunction)

### ContinuousRHClassifiedVE

- flood_raster_osm_building_impact (FloodRasterBuildingFunction)
- flood_raster_road_qgis (FloodRasterRoadsQGISFunction)
- flood_raster_road_qgis_gdal (FloodRasterRoadsGdalFunction)

### ContinuousRHContinuousRE

- flood_raster_population (FloodEvacuationRasterHazardFunction)
- tsunami_population_evacuation_raster (TsunamiEvacuationFunction)

## Earthquake

### ContinuousRHClassifiedVE

- earthquake_building (EarthquakeBuildingFunction)

### ContinuousRHContinuousRE

- itb_earthquake_fatality_model (ITBFatalityFunction)
- pager_earthquake_fatality_model (PAGFatalityFunction)

## Volcano

### ClassifiedVHClassifiedVE

- volcano_point_building (VolcanoPointBuildingFunction)
- volcano_polygon_building (VolcanoPolygonBuildingFunction)

### ClassifiedVHContinuousRE

- volcano_point_population (VolcanoPointPopulationFunction)
- volcano_polygon_population (VolcanoPolygonPopulationFunction)

## Generic

### ClassifiedVHClassifiedVE

- classified_polygon_building (ClassifiedPolygonHazardBuildingFunction)

### ClassifiedVHContinuousRE

- classified_polygon_population (ClassifiedPolygonHazardPopulationFunction)

### ClassifiedRHClassifiedVE

- classified_raster_building (ClassifiedRasterHazardBuildingFunction)

### ClassifiedRHContinuousRE

- classified_raster_population (ClassifiedRasterHazardPopulationFunction)

### ContinuousRHContinuousRE

- continuous_hazard_population (ContinuousHazardPopulationFunction)

**Comment by timlinux** [comment]
Yes as a first pass the base classes should be ensuring that the inputs comply with the specified layer modes.

**Comment by lucernae** [comment]
First pass completed. Continue with retrieving IF parameters from layer keywords.

**Comment by ismailsunni** [comment]
Retrieving IF parameters from layer keywords has been done in PR #2080, not merged yet though.

**Comment by akbargumbira** [comment]
It would be nice to get the keywords in the 12 base classes like the design
we made. So getting hazard_value_attribute, hazard_class_mapping,
exposure_class_attribute etc is done in those 12 classes. The concrete
classes just need to use this property from the parent.

On Fri, Jul 10, 2015 at 9:59 AM, Ismail Sunni <notifications@github.com>
wrote:

> Retrieving IF parameters from layer keywords has been done in PR #2080
> <https://github.com/AIFDR/inasafe/pull/2080>, not merged yet though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AIFDR/inasafe/issues/1914#issuecomment-120200034>.
>



-- 

*-------------------*

*Akbar Gumbira*
*Software Engineer*
*Geospatial, NLP, Data Mining, Machine Learning, Artificial Intelligence*

**Comment by lucernae** [comment]
Thanks for the follow up, I should really continue this after it is merged to make sure the concrete class uses it.
