### ISSUE TITLE
BUG: Minimum Needs Manager Window - unable to resize

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#1926]
# Problem
the Minimum Needs Manager window height can not be resized & is bigger than a laptop screen size. This means that it is not possible to edit and save options or a new profile using this tool

# Environments
Windows
QGIS 2.8
InaSAFE 3.1 experimental (pre release version)

**Comment by lucernae** [comment]
I also encountered this and made some modification via #1878 earlier. I noticed that @timlinux 's PR in #1892 also includes it. So I expect it will solves this problem after it is merged
