### ISSUE TITLE
Minimum Needs Readable Sentence box needs more space

### ISSUE THREAD

**Issue by KathrynOwen** [AIFDR/inasafe#1930]
# Problem
It is quite hard to read and edit the sentence in this small field
![image](https://cloud.githubusercontent.com/assets/10971278/7578505/4c2ce65a-f899-11e4-8dc9-ce1099ee1bd0.png)

# Proposed solution
Make the box bigger so that the full sentence is visible all at the same time

**Comment by Jannes123** [comment]
Created new TextParameter and TextParameterWidget classes used them for Readable Sentence only
![text_widget](https://cloud.githubusercontent.com/assets/11268911/7610225/7931da6a-f97b-11e4-96e6-b1479037c3ab.png)
