### ISSUE TITLE
Minimum Needs Configuration - Provenance statement

### ISSUE THREAD

**Issue by KathrynOwen** [AIFDR/inasafe#1931]
# Problem
A user can modify a profile without updating the provenance statement

# Proposed Solution
- [ ] User needs to be prompted to check that the Provenance statement is still current when saving an updated or modified minimum needs profile.
- [ ] This is a potentially a good place for a user warning message

**Comment by Jannes123** [comment]
Hi @KathrynOwen what is the text message you would like to see after the Warning?
![profile_changed](https://cloud.githubusercontent.com/assets/11268911/7630034/5fe2a186-fa32-11e4-842b-d9a87997621e.png)

**Comment by KathrynOwen** [comment]
Hi @Jannes123 Perhaps 'Warning: Changes have been made to the above profile. Is the following provenance statement still correct?'

@Charlotte-Morgan what do you think?

**Comment by Charlotte-Morgan** [comment]
LGTM or if you want to keep it shorter.
Warning: profile changed. Please update the provenance statement.
