### ISSUE TITLE
We need a use cases section on the new web site

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1935]
For Maria:

We would like to have a section for use cases where we can put up stories of different institutions that are using InaSAFE and how. @Charlotte-Morgan and HOT team would need to collaborate on getting some initial content and maybe @maning and NOAH folks, as well as @vdeparday could contribute some content for us?

**Other things to convey:**
Examples of InaSAFE being used for contingency planning etc.
Usage stats
Impact of InaSAFE

**Comment by MariaSolovyeva** [comment]
@timlinux , should it go to About or Users section?

**Comment by timlinux** [comment]
I think in the about section

Thanks!

**Comment by MariaSolovyeva** [comment]
Here is the Case Uses page http://blogtest.inasafe.org/en/about-inasafe/cases/
@timlinux , let me know what fields I can add there, e.g.:

- institution logo
- goals
- maybe dates ?

Thank you

**Comment by maning** [comment]
Write-up/Case study for the PH on me.
