### ISSUE TITLE
Readable Sentence Text Formatting

### ISSUE THREAD

**Issue by Jannes123** [AIFDR/inasafe#1941]

**Comment by Jannes123** [comment]
enable string formatting {{ varname }} of TextParameters


![readable_sentence_format](https://cloud.githubusercontent.com/assets/11268911/7628022/59a5cf00-fa1e-11e4-95f4-89dafa803a07.png)

**Comment by Jannes123** [comment]
@cchristelis not a bug, perhaps we should add more help text for this widget used to format readable sentence.

**Comment by cchristelis** [comment]
Is there not enough information in the description text?
Here is the formatted description:
```
A <b>readable sentence</b> is a presentation of the resource that displays all pertinent information. If you are unsure then use the default. Properties should be included using double curly brackets '{{' '}}'. Including the resource name would be achieved by including e.g. {{ Resource name }}
```
What do you propose we add?
