### ISSUE TITLE
Python Error when select different profile from Global Minimum Needs Configuration

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1945]
# Problem
I encountered python error when i want to change different profile in Global Minimum Needs Configuration
![inasafe_1](https://cloud.githubusercontent.com/assets/2520159/7695028/a1587b2e-fe13-11e4-8db4-e9c4159ab30c.png)

## Step for producing this error
1. Open InaSAFE Global Minimum Needs
2. Try to modified some item in one profile (for example, modified Rice in BNPB_en profile)
3. Don't change anything in resource editor and click **Close** button in bottom side of the window
4. Try to move into another profile in profile selector
5. Boom! Error appear

# Operating System
I'm using windows 7 64bit and running InaSAFE 3.0.0 from QGIS Plugin Repository with 2.8.2 QGIS

# Proposed Solution
It need some mechanism to prompt user to save their edit in **resource editor** even tough the user didn't change anything. 

Because this python error appear when the user click the **Close** button instead of **save resource** if they didn't want to change anything in resource editor and tried to close the resource editor.

Or maybe we need to erase **Close** button, so it only have **Discard Changes**, **Save Resource** and **Help** buttons. Because some user may click the **Close** button instead of **Discard Changes** if they didn't changes anything in Resource Editor.

**Comment by lucernae** [comment]
I think it doesn't make sense that we had a close button. Perhaps we should hide the close button in the "edit resource" page.
But, we still have to handle the close action when triggered via escape button or quit [x] button
