### ISSUE TITLE
Wrong action for Export and Import Buttons in Global Minimum Needs Configuration Tool

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1946]
# Problem
I want to import BNPB_en minimum needs configuration to my own custom minimum needs in *InaSAFE Global Minimum Needs Configuration*'s Windows. 

Instead of import the file, it showed me *Save As..* action. Both **Export ...** and **Import ...** buttons act same behavior with **Save As** button.

![inasafe_2](https://cloud.githubusercontent.com/assets/2520159/7695629/71ba5c26-fe1c-11e4-8677-05ce4c42c460.png)

# Operating System
I'm using Windows 7 64bit with QGIS Wien 2.8.2 and InaSAFE 3.0.0 from QGIS repository

**Comment by lucernae** [comment]
After a bit browsing the codebase, it appears that the import button uses the wrong name. It should be "open"
