### ISSUE TITLE
Found several bugs in InaSAFE Minimum Needs Tool

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1947]
# Problem
I found several bug when I want use *InaSAFE Minimum Needs Tool*.

### First bug
The **Affected people field** in InaSAFE Minimum Needs Tool its didn't change if we change **Affected people layer**. It still showed field in previous layer. For example, in this image, i have several layer in my layer list (building, building-points, and district_osm_jakarta). 

![inasafe_1](https://cloud.githubusercontent.com/assets/2520159/7718906/c4b82082-fee1-11e4-8708-614d947a8e4f.png)
When the first time i opened *InaSAFE Minimum Needs Tool* it pointed to building-points in **Affected people layer** and all the field inside the building-points (BUILDING, AMENITY, CAPACITY, etc)

After i change the **Affected people layer**  into district_osm_jakarta, the **Affected people field** still showed the same field as before (BUILDING, AMENITY, CAPACITY, etc) and it should not like that because the exact field in district_osm_jakarta are (KAB_NAME, PEREMPUAN, displaced, etc)
![inasafe_2](https://cloud.githubusercontent.com/assets/2520159/7718936/5bbacd7c-fee2-11e4-8b79-11bccd29a12f.png)

### Second bug
The OK button in the bottom side of *InaSAFE Minimum Needs Tool* didn't react anything. It's clickable but nothing happen after you click that buttons.

# Operating System
Windows 7 64bit
QGIS 2.8.2 (Wien)
InaSAFE 3.0.0 from repository and InaSAFE 3.2.0.dev-master from github

**Comment by lucernae** [comment]
@adissadis could you try this again? :)
