### ISSUE TITLE
Remove Keyword Dialog

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1954]
Problems
------------
Due to metadata update, keywords dialog will be broken. We need to update it so that it can work as before.

Solution
-----------
Some needed updates:
- [ ] Change category to layer purpose
- [ ] Remove subcategory and change it to exposure_type or hazard_type, dynamically (using impact function manager)
- [ ] Make sure the dialog still works for aggregation layer

**Comment by timlinux** [comment]
Do you mean the keywords editor above? I think we have agreed to remove it and use only the wizard? Can we go ahead with this. CC @Charlotte-Morgan

**Comment by ismailsunni** [comment]
@timlinux yes

But, iirc @Charlotte-Morgan said that she has a case for it when we were in Jakarta.

*I hope I was wrong.

**Comment by akbargumbira** [comment]
The case was that to add allow resample option/not, which she also had
agreed to remove keyword editor as the wizard asks this in one of the steps
in wizard. But please check if this option is properly assigned from the
wizard.

**Comment by ismailsunni** [comment]
Ok, so we agree, if there the wizard does the job properly, we will remove the keywords dialog?

Another thing is, the dock still uses the keywords dialog to assign some keywords, if not exist. What about this?

**Comment by akbargumbira** [comment]
> Ok, so we agree, if there the wizard does the job properly, we will remove the keywords dialog?

Yes

> Another thing is, the dock still uses the keywords dialog to assign some keywords, if not exist. What about this?

Simply just remove keywords dialog with wizard. I see that the usage is only for when user uses aggregation layer but the keywords is not valid.

**Comment by ismailsunni** [comment]
Ok, then I will remove it, and pop up a message box if the user use invalid keywords for aggregation layer on dock.

**Comment by ismailsunni** [comment]
I will change to "remove the keywords dialog"

**Comment by akbargumbira** [comment]
Rather than popping up a message box, I thin it's better to instantiate a wizard dialog

**Comment by ismailsunni** [comment]
I had that idea also, but I prefer to do it after the wizard is finished. We will do it for sure.

**Comment by ismailsunni** [comment]
Done in PR #1809
