### ISSUE TITLE
Update Wizard Dialog with New Metadata Keywords

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1956]
Problems
-------------
Since we will have new metadata keywords, the wizard should be updated, so that it can work properly.

Current Status
-------------------
@borysiasty has made some initial work to do it, and will be merged to https://github.com/ismailsunni/inasafe/tree/new_metadata_keywords.

Solution
----------
Make it happy.

**Comment by ismailsunni** [comment]
From @borysiasty 's email:

Hi Ismail,

I made a PR for you. In separate commits there are some minor fixes for
new_definitions.py and impact_function_metadata.py

Thanks I will check it.

The wizard is alsmost working, however, it requires a few changes in the API
to finish the work:

1. The continuous_hazards_units_for_layer() always return all units (even
metres for earthquake). You can see it in the Keyword Wizard. It also makes
the test failing.

2. In the functions_for_constraint(h_key, e_key, ...) only two first
parameters should be mandatory. This way I can ask for functions for the first
table (just hazard x exposure). So:

functions_for_constraint(h_key, e_key, h_geom=None, e_geom=None, h_mode=None,
e_mode=None)

You can see it in the wizard_dialog.py :1829

For the second table, I pass all the constraints.

This method returns a list of function *classes*, however all I need is their
metadata - and it seems it previously returned it. Could you please either
return the metadata (strictly speaking I need the function name and compatible
layer mode & geometry) or point me how to get to the metadata from the
function class?

Gooodnight, I should wake up in ~8h and I can continue when the last question
is solved ;) The continuous_hazards_units_for_layer problem isn't any blocker
for me (thought it is for the test).

**Comment by ismailsunni** [comment]
Hi @borysiasty 
From your request above, I have done:
- Fix continuous_hazards_units_for_layer.
- Use default arguments for functions_for_constraint
- Return metadata for functions_for_constraint

I hope that's enough.

**Comment by borysiasty** [comment]
@ismailsunni Thanks a lot - the PR is waiting for you.

**Comment by ismailsunni** [comment]
Thanks @borysiasty for the wizards.

If anyone want to test it, please get it from https://github.com/ismailsunni/inasafe/tree/new_metadata_keywords.

cc: @Charlotte-Morgan @borysiasty @timlinux @akbargumbira @lucernae @cchristelis @Jannes123 @Gustry

**Comment by ismailsunni** [comment]
UI Things
- Click Load standards layers
- Choose Flood vs Structure
- Choose Raster vs Polygon
- Choose Flood raster building function
- Choose loaded from QGIS
- Got this UI. See the text in the right.
![inasafe_020](https://cloud.githubusercontent.com/assets/1421861/7814000/5f1fec66-03e9-11e5-8f7b-aa1e7f82bc0c.png)

**Comment by ismailsunni** [comment]
- UI Things
Better text for postprocessor (see green arrow)
![inasafe_021](https://cloud.githubusercontent.com/assets/1421861/7814086/f8907aa0-03e9-11e5-896e-25a8eacbaf0f.png)

**Comment by borysiasty** [comment]
Here is the workflow of the keyword creation mode: 
![wizard_workflow](https://cloud.githubusercontent.com/assets/1000043/7854710/3f7d55fe-051c-11e5-88f3-a6334b6d20b4.png)

**Comment by borysiasty** [comment]
As some of you may already know, Ismail and me realized that we need a third layer_mode. 
Besides 'continuous' and 'classified', we need a mode where every feature has the same value, e.g. for volcano_point.
We called it temporarily 'none', ideas for a better name highly welcome. 

On the diagram below, you can see the current imlementation of the wizard. At this moment, the full implementation is still in the PR: https://github.com/AIFDR/inasafe/pull/1984

It introduces quite strict relations between some keywords:

1. If `layer_mode` == **continuous**, the `unit` keyword is mandatory. For vectors, also the `field` keyword is mandatory.
 
2. If `layer_mode` == **classified**, the relevant classification type keyword (e.g. `vector_hazard_classification`) is mandatory. For vectors, also the `field` keyword is mandatory.

3. If `layer_mode` == **none**, no unit, classification or field keywords are assigned. Instead, the *additional_keywords* step allows to set keywords like `volcano_name_field` or `road_type_field`.

It means, that the `field` keyword is is either continuous or classified and is STRICTLY connected to either `unit` or classification type and mapping.
*Volcano_point* is neither continuous nor classified. Also roads are not classified!

The `volcano_name_field` and `road_type_field` has nothing to do with the classification, what is strictly connected to the "main" `field`.
This way we have some kind of "leading" value that is represented by continuous or classified `field` (or raster value) and some additional fields, like the road type, that doesn't affect the IF results, they are only for grouping etc.

I'm not sure what is purpose of the `hazard_zone_field` keyword. If it's the 'main' input to the IF, it should go rather to the 'main' `unit` keyword and has a mandatory `vector_hazard_classification`.

What do you think? Does it make any sense? Actually I can't imagine any way of mixing the additional keywords with classified `layer_mode`.

![wizard_workflow](https://cloud.githubusercontent.com/assets/1000043/7883658/6c7a65cc-0618-11e5-9a89-3a4ba1646ed6.png)

**Comment by Charlotte-Morgan** [comment]
Hi @borysiasty 
I agree that there is a third layer mode. have a look at the Data Model diagram in the metadata definitions hierarchy https://docs.google.com/document/d/1UMG5SklkLrF12-lO5sS8ROLmB7JXx3E3w8bamB4JMqo/edit
This shows that raster data can be continuous or classified and that vector data can be classified or 'footprint' (not sure that is the best word).

This data model only describes the hazard data and was prepared to show the difference between single event and multievent hazard scenarios so it does not describe the exposure data.

let me think some more on exposure data but i think roads can be classified and this field may need to be used in the future for things other than reporting - ie network analysis and routing

**Comment by borysiasty** [comment]
> i think roads can be classified and this field may need to be used in the future for things other than
> reporting - ie network analysis and routing

Well, all I need is just a set of unambigious rules how the wizard should behave. In the diagram above there is my proposition of a strictly organized rule. There can be either:
- LAYER_MODE=classified and CLASSIFICATION=road_classes and FIELD=something
- LAYER_MODE=none/footprint/however and ROAD_TYPE_FIELD=something

The former implies 'things other than reporting', but actually none of them neither forces nor forbids the impact function to use the field in this or that way. It's just a proposition of a rule to be implemented in the Wizard. If it's better to mix various field keywords with the classified mode and make the classification type keywords optional, I can implement anything, we just have to develop those rules so I can follow them. For example, what exactly the wizard should do if the user selects a volcano exposure for a point layer.

**Comment by borysiasty** [comment]
Ok, now I realized we're departing from simple keywords in favour of hierarchical ones (eg. we have *raster_hazard_classification*, *vector_hazard_classification* etc. instead of just one *classification*, so maybe the goal is to drop the simple *field* and only use the *road_type_field* etc? 

Anyway, I'm waiting for a final approval how it should work :)

**Comment by Charlotte-Morgan** [comment]
yeah - the lads are locked in a room working it out :)

**Comment by borysiasty** [comment]
Here is an editable version of the diagram: http://tmp.borysjurgiel.pl/wizard_workflow.svg

**Comment by timlinux** [comment]
Its giving a 404 borys

**Comment by borysiasty** [comment]
Strange... Not for me! :)

**Comment by timlinux** [comment]
See also the diagram we made during our discussion on skype with @borysiasty 

https://www.lucidchart.com/invitations/accept/6de7e7cb-9e48-42e4-b835-a00a0b566818

![keywordwizardworkflows - new page](https://cloud.githubusercontent.com/assets/178003/7978440/915aca0c-0abf-11e5-8dd2-d2df2f857fb9.png)

**Comment by borysiasty** [comment]
So here's the wizard updated to match the diagram above:
![wizard_workflow](https://cloud.githubusercontent.com/assets/1000043/8005593/2061a2da-0b8c-11e5-86a2-7fa42eeee232.png)

**Comment by timlinux** [comment]
Hi @borysiasty (cc @ismailsunni @Charlotte-Morgan)

What I am not so sure about from your diagram is volcano. For volcano we can have two attributes of concert:

```
        # Parameters
        hazard_zone_attribute = self.parameters['hazard zone attribute']
        name_attribute = self.parameters['volcano name attribute']
```

(from safe/impact_functions/volcanic/volcano_polygon_building/impact_function.py:93 )

So for the zone we should do the mappings for l, m, high. For the name we should have  a simple page that asks for the name of the field containing volcano names. Can you indicate if this is aligned with your thinking?

Other than that (and overlooking the fact that it is late on friday and my brain is chop-suey :-) ), it think it looks good to me!

**Comment by borysiasty** [comment]
Ok, so let's keep the `additional keywords` step for volcano_name_attribute.

If I understand correctly, the two fields are for polygon volcanos. For point volcanos, there is only volcano_name_attribute, isn't there? So for polygon volcanos the name field will be set in the `additional keywords` step, while for point volcanos the basic `field` step will be used. It's a small UX inconsistency but I hope it's ok.

![wizard_workflow](https://cloud.githubusercontent.com/assets/1000043/8006646/05fd1884-0b96-11e5-84bd-3eb8a05a7957.png)

**Comment by timlinux** [comment]
> If I understand correctly, the two fields are for polygon volcanos. For point volcanos, there is only volcano_name_attribute, am I right? 

yup!

> In this case, let's skip the FIELD step for point hazards, and use the ADDITIONAL KEYWORDS step for volcano_name_field for both point and polygon volcanos

Yes I think this works for me - @ismailsunni please add any comments if you can see any issue with the above layout!

Regards

Tim

**Comment by borysiasty** [comment]
@ismailsunni, one more question: For point buildings (the Building Centroids layer), should the structure_class_field be set or skipped?

**Comment by timlinux** [comment]
Hmmm Borys I think it should be kept... Will need to check in the code.

**Comment by ismailsunni** [comment]
>@ismailsunni, one more question: For point buildings (the Building Centroids layer), should the structure_class_field be added to the keywords or be skipped? Currently it's added.

Yes, it should be kept. It's needed to identify which field represent the structure_type

For the diagram, is it possible to choose the `classification (type)` first, then the `field or exposure class field`? It seems more natural that way.

I checked your PR, it looks great. But, before merging it, can you un-skip the unit tests for it? I skip them so that the tests will look good. Since, the wizard is ready, may be we can turn them on again.

**Comment by ismailsunni** [comment]
After some experiments with the wizard, I found something that need to be fixed:
- [ ] Set `allow_resample` option with current value in the layer's keyword file

**Comment by borysiasty** [comment]
> Set allow_resample option with current value in the layer's keyword file

@ismailsunni: If you tick the checkbox, it sets `allow_resample = false`. Otherwise, it doesn't set this keyword at all. It was a request from ~ half a year ago. Did it change? If it should always set the keyword, probably the checkbox label would need to be updated from "never resample" to just "don't resample".

**Comment by ismailsunni** [comment]
It's different thing. What I mean is, if I have a layer that has `allow_resample=false` in its keyword file, and open the keyword wizard for this layer. Go to the `allow_resample` step, and we will get the option unchecked. It should be checked, the same value as in the keyword file.

**Comment by borysiasty** [comment]
Ok, sorry, now I got it.

**Comment by borysiasty** [comment]
Diagram updated to recent change in step order: `Select classification` before `Field`
![wizard_workflow](https://cloud.githubusercontent.com/assets/1000043/8105781/80c21a9c-103c-11e5-94c3-9cdecd819c5c.png)

**Comment by ismailsunni** [comment]
Hi @borysiasty 
For set the value for `allow_resample` --> works

For UI Things Better text for postprocessor, it's much better. The only thing that I found is:
![inasafe_027](https://cloud.githubusercontent.com/assets/1421861/8123130/2f7926fa-10ee-11e5-82d0-1a73ea3625c8.png)
But when you click the little triangle, you will got the same text. So, there is double description
![inasafe_028](https://cloud.githubusercontent.com/assets/1421861/8123136/4439c95a-10ee-11e5-9d93-62b55e75626b.png)

For change the order of step in wizard to choosing class, choosing field, then value mapping., perfect.

**Comment by borysiasty** [comment]
I just import the safe.impact_statistics.function_options_dialog.FunctionOptionsDialog
@lucernae you were recently working on it, could you take a look please?
