### ISSUE TITLE
[Bug] There's no "Extent Selection" in Impact Function Centric Wizard

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#1957]
# Problem
I'm using Impact Function Centric Wizard (Building and Flood hazard) and didn't have any layer in my layer list. So after i select my hazard and exposure data from my directory, the next section is not the "Aggregation" and "Extent Selection" instead it appear Error message like this:
![image](https://cloud.githubusercontent.com/assets/2520159/7793262/e56f9d60-02e6-11e5-8900-627063f89c46.png)
Which is really strange because i'm using training data that already in same datum and already intersect/overlap each other.
This error only appear if you don't have any layer in layer list and you decide to pick from your computer directory. If you already load your layer and use that layer for wizard, it didn't appear that kind of bug/

## Step for producing this error
- Open InaSAFE Impact Function Centric Wizard
- Select Structure with Flood Hazard
- Select the data from disk/directory

# Operating System
I'm using QGIS 2.8 Wien and using both InaSAFE 3.0 (from repo) and InaSAFE 3.2 (from github)

**Comment by lucernae** [comment]
@adissadis can I have more specific information on what are the layer filenames which is used?

**Comment by adissadis** [comment]
@lucernae i'm using building_osm_jakarta with hazard data using both flood_hkv_current_jakarta and flood_osm_bpbd18113_Jakarta

**Comment by ismailsunni** [comment]
@borysiasty can you make sure that this won't happen in the new wizard?

The problem only occurs when the user select layer from disk. All is fine if the user select the layer from QGIS.
