### ISSUE TITLE
Wizard's Issues

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1961]
Problem
----------
These are known issues in the wizards. 
- [x] ~~Use `attribute` instead `field`~~ (we decided the `field` is ok)
- [x] Special case for volcano point. Currently, it doesn't make sense.
- [x] Don't hard coded option for continuous and classified (layer_mode step)
- [x] We should write layer_geometry to the keywords file
- [x] Generic IF makes the wizard able to assign un-matched hazard and unit/classifications. E.g. when I assign flood classfieid raster, after choosing flood, I still get option tsunami raster hazard classes in the classification step

**Comment by Charlotte-Morgan** [comment]
# Problem
Some additional observations on the wizard.
- [ ] Step 1. Radio buttons for Hazard Scenarios should read "Single Event" and "Multiple Event" 
- [ ] Step 1. Add text explaining what a single event and multiple event is here or it comes up on a later step. 
is the radio button still needed if the hazard data will also have a key word assigned for this, ie the wizard can read from the metadata

- [ ] Step 2. move the text describing classified and continuous data to step 3. Add text describing raster and vector data to step 2.
- [ ] Step 3. assumes the user knows what type of data they have and invites them to select the IF. as an IFCW it makes sense that this comes before choosing the data. However is our user more likely to know what data they have or what IF they want to use. if choosing the IF came after selecting the data the user would be given less choices in this screen. (just thinking aloud here).
- [ ] is there a reason why the wizard offers me all the available raster data loaded in QGIS and not just the ones that meet hazard kw when the data already have kw assigned?
- [ ] the text on the step about assigning key words needs tweaking. replace "you have selected a layer that has no keywords assigned" with "You have selected a layer that needs to have keywords assigned or updated"
- [ ] the step where users select classified or continuous is a great addition however the descriptions should be tweaked to be consistent. There is no need to describe classified data in the continuous description. The current description of classified data in the continuous option is better than the one in the classified option. - i can supply new text if required
- [ ] there is a step that asks about category of hazard. As above this needs to refer to single event or multiple events. Can we replace 'category of hazard" to 'hazard scenario"? That's a metadata definition change.
- [ ] can the step that asks about what type of hazard come before category of hazard?

Logic goes:
- i want to look at impact of flood on people
- i have raster hazard and raster exposure
- here is my hazard data
-- it represents a flood event 
-- it represents a single event (could use the radio button on the step above for assigning kw)
-- it is continuous data
 
- here is my exposure data
 -- it represents population
 -- it is continuous data
 -- no i don't want it to be resampled (could be a radio button on the continuous exposure step above)
- [ ] the wizard offers & allows me to select some options that should be considered invalid eg MMI for a tsunami raster 

@ismailsunni - i trust you will filter this list in terms of what is relevatn now, what should wait & assign things to people. I'm happy to do the text tweaks if you want.

**Comment by borysiasty** [comment]
@Charlotte-Morgan, Thanks a lot for your remarks!

> 3. assumes the user knows what type of data they have and invites them to select the IF. as an
> IFCW it makes sense that this comes before choosing the data. However is our user more likely to 
> know what data they have or what IF they want to use. if choosing the IF came after selecting the
> data the user would be given less choices in this screen. (just thinking aloud here)

This will be DCW (data-centric wizard) - a task for next month. Initially, the first step of the IFCW was a function tree, the tables came later ;)

> is there a reason why the wizard offers me all the available raster data loaded in QGIS and not just
> the ones that meet hazard kw when the data already have kw assigned?

It should offer you just the selected hazard rasters plus, additionally, all rasters without keywords (or with obsolete  keywords), written with an italic font. Maybe it's the case?

> can the step that asks about what type of hazard come before category of hazard?

@ismailsunni - we need another api update. To make it flexible and easily reversible, what about making it "symmetric", with the second parameter optional:
hazards_for_layer(layer_geometry, hazard_category_key = None)
hazard_categories_for_layer(layer_geometry, hazard_key = None)

And the same for exposures.

**Comment by Charlotte-Morgan** [comment]
@borysiasty - yes I agree my comments are data centric and i think we abandoned that in favour of a single wizard. So you are correct, we are IFC right now
The wizard offered me all rasters regardless of hazard or exposure that were loaded in qgis. These all had relatively up to date metadata.
I'm just grabbing your pull request to make sure my comments are still valid

**Comment by Charlotte-Morgan** [comment]
ok - rasters offered are in italic but kw are current -1 version :)

**Comment by borysiasty** [comment]
@Charlotte-Morgan: if they are italic, it seems the layer_purpose keyword is missing.

**Comment by borysiasty** [comment]
>  Step 1. Add text explaining what a single event and multiple event is here or it comes up on a later
> step. is the radio button still needed if the hazard data will also have a key word assigned for this, ie the
> wizard can read from the metadata

Good question. According to the table in the *Metadata Conceptual Overview for InaSAFE* document, switching from Single to Multi Event should make raster volcanos cell enabled. It's the only difference, and it seems even it doesn't work :) It means the IF api finds the same possibilities for both scenarios.  So maybe we can drop the radiobuttons? If I'm right, the only effect will be the list of available functions displaying functions appropriate for both scenarios. @timlinux, you was the inventor, wasn't you? What do you think? @ismailsunni, @akbargumbira, and you guys?

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan 
for
```
the wizard offers & allows me to select some options that should be considered invalid eg MMI for a tsunami raster
```
The reason is, in generic IFs, we put all possible hazards and all possible units to be able to run in the generic IF.
After some thought, perhaps it will be better to put only all hazards, and only put `generic` unit or classifications.
What do you think?

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni 
Is is possible to only offer some units depending on hazard?
Same - i am also looking at other issues for generic IF & wonder if units and thresholds can be set based on hazard? eg if i choose continuous raster hazard on population (but have already stepped through telling it that i want to look at flood) then should it know that only some units are suitable for continuous flood raster and also what the default threshold is for flood? I have no idea where the default threshold is coming from for now

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
> Step 3. assumes the user knows what type of data they have and invites them to select the IF. as an IFCW it makes sense that this comes before choosing the data. However is our user more likely to know what data they have or what IF they want to use. if choosing the IF came after selecting the data the user would be given less choices in this screen. (just thinking aloud here).

What about adding additional information when we select an IF. Currently we only show Name and Overview. We can add `hazard_input` and `exposure_input` so that the user will have more information to choose. What do you think?

**Comment by borysiasty** [comment]
@Charlotte-Morgan, @ismailsunni, @timlinux:
> Step 1. Add text explaining what a single event and multiple event is here or it comes up on a later
> step. 
> Is the radio button still needed if the hazard data will also have a key word assigned for this, ie the
> wizard can read from the metadat

The radiobuttons are only to slightly limit the number of available hazards/exposures, geometry types and functions. Actually they make more mess than convenience so I'll be happy to remove them.

**Comment by borysiasty** [comment]
@Charlotte-Morgan:
> Step 3. assumes the user knows what type of data they have and invites them to select the IF. as an
> IFCW it makes sense that this comes before choosing the data. However is our user more likely to
> know what data they have or what IF they want to use. if choosing the IF came after selecting the data
> the user would be given less choices in this screen. (just thinking aloud here).

So I'm not sure what is the conclusion:) Can I just remove this point?

**Comment by timlinux** [comment]
@Charlotte-Morgan wrote:

> So I'm not sure what is the conclusion:) Can I just remove this point?


@borysiasty wrote:

> So I'm not sure what is the conclusion:) Can I just remove this point?

I think we should park this and get the wizard into use in the Real World (TM) and then do some survey / get feedback from training on whether / how we can optimise it in the future.

**Comment by Charlotte-Morgan** [comment]
+1 for real world testing. Sorry - I am not going to be able to look at anything until 6th July.

**Comment by borysiasty** [comment]
@timlinux: There was also a question for you about the radiobuttons (could you please search the discussion for your nick)

**Comment by timlinux** [comment]
@borys if you mean relating to whether we should hide / remove the radio buttons onthe first step, - personally I would be happy to remove them for now - perhaps we can bring them back in the future if they will more meaningfully update the filtering of the first table. @Charlotte-Morgan that OK for you?

**Comment by borysiasty** [comment]
Thanks a lot! I fully support removing them :) Let's wait for Charlotte's comeback, and if there is no veto, I'll hide them and close this ticket.

**Comment by Charlotte-Morgan** [comment]
hi @borysiasty - i am happy for the radio buttons to go now that we have this single and multiple hazard events in the key words

**Comment by borysiasty** [comment]
@Charlotte-Morgan: The radiobuttons are gone. Can we close this issue? There is one remaining checkbox with a question waiting for your answer;)

**Comment by Charlotte-Morgan** [comment]
Radio button are gone - we can close this now.
Thanks @borysiasty
