### ISSUE TITLE
Mismatch of metadata with the layer

### ISSUE THREAD

**Issue by lucernae** [AIFDR/inasafe#1965]
I'm not sure where to start. I'm also not sure is this the expected outcome? 
Here's what I found:

### Earthquake Polygon can't be matched with any exposure layer we have in test data (safe.test package)

I tried possible combination of hazard and exposure. When I arrived at Earthquake Polygon, I assumed that it can be matched by building exposure, because we have classified polygon building IF? But the IF doesn't show up. @akbargumbira is this the expected behaviour?

@ismailsunni I think I've found why I'm not able to select layer from QGIS, if I use the wizard. Perhaps this is because I select Earthquake + Building combination, and then polygon + polygon, then there is one IF match (classified polygon building), but after that I can't select any layer from QGIS (because no layer met the constraint specified by the IF).

After that, I found that in [here](https://github.com/lucernae/inasafe/blob/791bd02249340841f2ee2070f4d2c8270148c8b3/safe/impact_functions/generic/classified_polygon_building/metadata_definitions.py#L86-86) somehow raster_hazard_classifications is assigned by all_vector_hazard_classes. I'm not sure is this intentional, but seeing 'raster' and 'vector', perhaps this is a typo? :p

**Comment by lucernae** [comment]
In case this is a typo, just merge my PR, if not, just close it.

**Comment by akbargumbira** [comment]
Thanks for the PR
