### ISSUE TITLE
Description Text to be Added in definitions.py

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#1975]
Problems
------------
Some descriptions in definitions.py are missing:
- hazard_category_single_hazard
- hazard_category_multi_hazard
- exposure_land_cover
- exposure_people_in_building
- unit_kilogram_per_meter_square

The other are written in https://github.com/AIFDR/inasafe/blob/develop/safe/definitions.py

If you see improper definitions, please tell me.

**Comment by Charlotte-Morgan** [comment]
I've made some edits for single event and multi event. Just need to work out where they went :(

**Comment by Charlotte-Morgan** [comment]
these are all addressed in #2035
