### ISSUE TITLE
We need to harmonise the application toolbar icons with the HIG guidelines

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1985]
# Problem

Our icon set is rather haphazard. We should have icons that are consistent with the design guidelines for InaSAFE (as per http://github.com/AIFDR/inasafe-graphics ).

@MariaSolovyeva has produced two options as proposed replacements:

![screen shot 2015-05-30 at 20 19 55](https://cloud.githubusercontent.com/assets/178003/7898783/ff0ee838-070b-11e5-9b6a-6ee62aea25b8.png)

or 

![screen shot 2015-05-30 at 20 20 13](https://cloud.githubusercontent.com/assets/178003/7898912/6b74ff8c-070f-11e5-8d96-fbce3d504dd3.png)

My preference is for the black outline theme

**Comment by MariaSolovyeva** [comment]
Here is the updated set of icons, I made a preview with gray background to show the transparency. @timlinux , please let me know if I didn't miss any?
![icons-preview](https://cloud.githubusercontent.com/assets/10400420/8391956/929dd94e-1ce0-11e5-8bd0-0c974c2cdd51.png)

**Comment by MariaSolovyeva** [comment]
Update: show-impact-merge fix
![icons-preview](https://cloud.githubusercontent.com/assets/10400420/8392238/92a63bf0-1cec-11e5-817d-4dfc33e56adb.png)

**Comment by timlinux** [comment]
That looks really good @MariaSolovyeva - can you give me SVG's for these and we settle on them for now?
