### ISSUE TITLE
Wrong help page for User Extents/Analysis Area tool

### ISSUE THREAD

**Issue by KathrynOwen** [AIFDR/inasafe#1989]
# Problem
When help is clicked in the User Extents/Analysis Area tool, the help text doesn't match the current ability of the tool.

Charlotte mentioned that the help page is meant for version 3.2, not the current 3.1 version.

Current options on the tool are only to use a bookmark, input co-ordinates or select extent on the map:
![image](https://cloud.githubusercontent.com/assets/10971278/7928625/990b2236-0936-11e5-891f-2a6cfbffa504.png)

But the help page mentions other 'tickable box' options that are currently not part of the released tool:
![image](https://cloud.githubusercontent.com/assets/10971278/7928642/ddf27b42-0936-11e5-84d4-50b8573000a5.png)

**Comment by timlinux** [comment]
Hi

Just a note to say that the help file is in fact correct, but it will be defunct in 3.2, so it will need to be updated for that release. I am going to close this for now.

Thanks for the feedback.

Regards

Tim
