### ISSUE TITLE
WPML Plugin for Wordpress is not redirecting to /en/

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#1997]
Hi @MariaSolovyeva 

I did some updates to the blog site so we can get it ready to go into production. I used a newer wordpress container which uses apache instead of nginx. Do you remember we had problems with urls like:

http://blogtest.inasafe.org/en/

Not redirecting properly? It was caused by the WPML plugin and I made these changes to the nginx configuration to fix it:

```
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to index.html
                #try_files $uri $uri/ /index.php?q=$uri&$args;
                # Changed to below for Maria by Tim on 30 April 2015
                # to resolve redirect issues.
                try_files $uri $uri/ /index.php?q=$uri$is_args&$args;
                # Uncomment to enable naxsi on this location
                # include /etc/nginx/naxsi.rules
        }
```

With the configuration upgrade it is now using apache again and the problem is back. I remember you pointed me to a link for the apache configurations needed, but I don't see them on the WPML site. Can you help? For now I have disable multilingual support so that at least the english version of the site is working.

**Comment by MariaSolovyeva** [comment]
Ok it is fixed, I had to reset the permalink structure

**Comment by timlinux** [comment]
Oh awesome, thanks very much!
