### ISSUE TITLE
We need an InaSAFE T-shirt

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2003]
We need an InaSAFE t-shirt for significant project team members that can be worn during training, promotions etc. This is not a t-shirt for training participants.
- [ ] use the official t-shirt design developed by kartoza
- [ ] number & sizes to be determined by @timlinux 
- [ ] production & delivery to be managed by HOT  @iyan31 
- [ ] funded by AIFDR through Grant to HOT
- [ ] required by 10 June 2015 - please :)

# cc
@MariaSolovyeva

**Comment by iyan31** [comment]
Once we got the number and sizes, we will start the production immediately

**Comment by timlinux** [comment]
@iyan31 hi! 

I think the number is up to you (how much budget you have), and also the sizes probably we want a mix of :

Size | Ratio |
------|----------|--
Small | 20% |
Medium | 50% |
Large | 20% | 
X-Large | 10% |

That is just a guess as to a good split, if you can indicate from your previous runs  what a good ratio is, that will be great.

The t-shirt design is here. 

https://github.com/AIFDR/inasafe-graphics/blob/master/inasafe-tshirt/T-shirt-final.png

I suggest to get some on black, blue or gray shirts shirts (or maybe a mix). The shirts should be higher quality polo shirts.

Could you get a sample made first before making a bulk order?

Thanks!

Regards

Tim

**Comment by emirhartato** [comment]
Let me know when it's done? I'm willing to get one :)
I'll be in Indonesia from 31 July - 3 August form my sister's wedding so I hope I can get it while I'm back ;) 

Cheers

**Comment by timlinux** [comment]
Hey @emirhartato 

Yes a well-deserved tshirt should be allocated to you. Though probably nobody will ever see it since you are living in the frozen wastelands of New Zealand and so are bundled up with 15 layers of clothes everyday :-)

**Comment by Charlotte-Morgan** [comment]
ah @timlinux  - in NZ it is very fashionable to wear shorts and t-shirt over your long thermals.
Maybe @emirhartato should tell us what colour his thermal are so we can be sure he has a matching t-shirt?

**Comment by emirhartato** [comment]
@timlinux it is not too cold, I'm getting used to it :-) -- I think I can live with 2-3 layers.
@Charlotte-Morgan I got three colours: brown, white, and grey :-)

**Comment by iyan31** [comment]
Hello all, here are the mockups for the Polo shirt design made by Regia based on the t-shirt design that Tim shared previously:
https://drive.google.com/folderview?id=0B0EZH6HSh0G1fk9pajVWT3B3QThpN3loeWFwTlJFbXQ1aC1ZNkVDZDR3a3N0QXlMeHRBRUk&usp=sharing. 

Intially I want to put the mockups here directly but since the size of the file is quite big I choose to put it in Gdrive. Let me know if you have comments.

Thanks!

**Comment by timlinux** [comment]
Ah I just realised that what I am calling 'gray' in the pictures is actually labelled 'white' in the file name. So to clarify: the only one that works under the current colour scheme is the white one, if we use any other (darker) colour, we should get @MariaSolovyeva to make a 'dark background' ready version of the t-shirt design.

**Comment by iyan31** [comment]
Okay, looking forward for 'dark background' version. In the meantime is it okay if we proceed and produce one sample of the white polo shirt?

**Comment by timlinux** [comment]
+1 To make a sample based on the white - @MariaSolovyeva will you make a variation of the tshirt artwork designed for a dark background?

**Comment by MariaSolovyeva** [comment]
Hello everybody,

Here are 4 variations for dark background, sorry I didn't find a polo
mock-up, so using common t-shirt.
The .svg files are attached as well

Let me know if you need to try more variants

Best,
Maria

**Comment by MariaSolovyeva** [comment]
Just to let you know, myself I prefer 2nd version )

all the best

**Comment by timlinux** [comment]
Thanks @MariaSolovyeva where shall we look for the mockups you made? I dont see them in the comments above...

**Comment by MariaSolovyeva** [comment]
Sorry, they are here. 

![t-shirt-dark-4](https://cloud.githubusercontent.com/assets/10400420/8010535/8eef7588-0bb9-11e5-8d10-9dfa00f74109.jpg)
![t-shirt-dark-1](https://cloud.githubusercontent.com/assets/10400420/8010533/8ec4f682-0bb9-11e5-953b-3f2b8e077df7.jpg)
![t-shirt-dark-2](https://cloud.githubusercontent.com/assets/10400420/8010536/8ef2463c-0bb9-11e5-8f30-c2ec99360054.jpg)
![t-shirt-dark-3](https://cloud.githubusercontent.com/assets/10400420/8010534/8eda0d1a-0bb9-11e5-84a5-c834e8061e09.jpg)

**Comment by timlinux** [comment]
Thanks Maria. I agree the second ine looks great! Can you share the original svgs with @iyan31 please?

**Comment by MariaSolovyeva** [comment]
Hello @iyan31 !
Please let me know your e-mail so I can send you the SVG files

**Comment by Charlotte-Morgan** [comment]
I think this is done. Wonderful tshirts designed, delivered & handed out last week.
Thanks everyone. Lets make a separate ticket for the next production run. :)
Closing this ticket

**Comment by timlinux** [comment]
> I think this is done. Wonderful tshirts designed, delivered & handed out last week.
> Thanks everyone. Lets make a separate ticket for the next production run. :)
> Closing this ticket

+1 to that, great job everyone!
