### ISSUE TITLE
Keywords creation wizard is causes QGIS to crash

### ISSUE THREAD

**Issue by lucernae** [AIFDR/inasafe#2005]
# Environment

- QGIS 2.8.1 Wien
- Linux, Ubuntu 14.04
- InaSAFE develop branch

# Steps to Reproduce

- Enable developer mode
- load standard layers
- select Flood Polygon layer
- click Keywords Creation Wizard
- click next all the way until it ends or crash

**Comment by borysiasty** [comment]
@lucernae: When exactly does it crash? I mean after what step? I can't reproduce it od Debian‚ will try with Ubuntu.

**Comment by lucernae** [comment]
@borysiasty I'm also using a debian based (ubuntu).
It doesn't crash anymore. Last time it crashed when we try to classify the hazard layer values to certain categories (wet/dry).

I will close this. Since it has been fixed.
