### ISSUE TITLE
We need to get BMKG to update their configuration for realtime

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2014]
# Problem

Currently we have given BMKG a fixed IP address as reference for uploading shake data. However this poses a problem since it makes it very difficult to move the service between hosts without interruptions. For this reason we need to contact them and ask them to update the ssh/config and any other places where they have referenced the specific ip address in favour of using a DNS entry.

# Proposed solution

@akbargumbira and @lucernae  to make contact with BMKG staff and walk them through what is needed. All references to host:

```
136.243.23.73
```

To be changed to 

```
realtime.inasafe.org
```

**Comment by lucernae** [comment]
This is resolved by providing BMKG ssh access to sftp.inasafe.org

**Comment by timlinux** [comment]
Hi Rizky

We need to follow this up by ensuring that the back quakes are uploaded and new quakes run properly. Please write a new ticket for that!

Regards

Tim
> On 17 Jun 2015, at 11:00, Rizky Maulana Nugraha <notifications@github.com> wrote:
> 
> Closed #2014 <https://github.com/AIFDR/inasafe/issues/2014>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/AIFDR/inasafe/issues/2014#event-332955343>.
> 

—





Tim Sutton

Visit http://kartoza.com <http://kartoza.com/> to find out about open source:

* Desktop GIS programming services
* Geospatial web development
* GIS Training
* Consulting Services

Skype: timlinux Irc: timlinux on #qgis at freenode.net
Tim is a member of the QGIS Project Steering Committee

Kartoza is a merger between Linfiniti and Afrispatial

**Comment by timlinux** [comment]
Hi Rizky

We need to follow this up by ensuring that the back quakes are uploaded and new quakes run properly. Please write a new ticket for that!

Regards

Tim
> On 17 Jun 2015, at 11:00, Rizky Maulana Nugraha <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Closed #2014 <https://github.com/AIFDR/inasafe/issues/2014>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/AIFDR/inasafe/issues/2014#event-332955343>.
> 

—





Tim Sutton

Visit http://kartoza.com <http://kartoza.com/> to find out about open source:

* Desktop GIS programming services
* Geospatial web development
* GIS Training
* Consulting Services

Skype: timlinux Irc: timlinux on #qgis at freenode.net <http://freenode.net/>
Tim is a member of the QGIS Project Steering Committee

Kartoza is a merger between Linfiniti and Afrispatial
