### ISSUE TITLE
Impact on roads not showing correct totals in reports

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2026]
# Problem

When we generate report for impact on roads, the total is the same always as impacted. The total should actually represent the total in that category in the analysis area.

![screen shot 2015-06-09 at 22 40 28](https://cloud.githubusercontent.com/assets/178003/8062197/aafd044c-0ef8-11e5-9965-e38d4412a50e.png)

**Comment by cchristelis** [comment]
I think this is the impact on buildings is broken down in impact categories and this total is the total impacted:
![selection_003](https://cloud.githubusercontent.com/assets/2319504/8567290/7d584024-2564-11e5-865b-233de97aeb73.png)
But even in this case, showing the total in the impacted area makes sense. I will change it.

**Comment by cchristelis** [comment]
Hi @timlinux,

This behaviour is changed in PR #2101. 
See the new snippet:
![selection_004](https://cloud.githubusercontent.com/assets/2319504/8567492/f23ba542-2565-11e5-8f13-e14daab1a68a.png)
