### ISSUE TITLE
We need to tweak the InaSAFE Postcard

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2030]
The InaSAFE postcard is a massive hit. I find it invaluable to have some handy to give away whenever someone asks "what is InaSAFE"?

Minor tweaks are required before the next print run:
- [ ] make sure the text mentions QGIS :) - @timlinux 
- [x] swap the "Who can use it?" & "How does it work?" headings to they match the relevant text.
- [x] update the logos. replace the AIFDR logo with the Australian Aid (Skippy) logo
- [x] ie 4 logos =  BNPB, Skippy, DFAT, WB_GFDRR
- [x] make DFAT logo a little bigger to accommodate printing at A6

Process:
 - [ ] minor tweaks as above
- [ ] HOT to share translated version back to central repo - @iyan31 
- [ ] file names to be updated to indicate language
- [ ] arrange proof reading and DFAT approval prior to printing 

Action:
- [ ] tweaks - @Maria
- [ ] file sharing - @iyan
- [ ] proof reading and approvals - me
- [ ] promotion - everyone

thanks everyone.

# cc
@timlinux, @iyan

**Comment by Charlotte-Morgan** [comment]
Hi @MariaSolovyeva - we have been asked to supply the post card file so that it can be turned into a standing banner for the CDSP closing event next week.
@iyan31 - please supply the translated files asap so Maria can make these tweaks to the files.
@MariaSolovyeva - can you make the tweaks so we can share updated files on monday?

# cc 
@timlinux @fredychandra @adissadis @samnawi

**Comment by MariaSolovyeva** [comment]
Hi @Charlotte-Morgan and @iyan31 ,
I added the banners PDFs to the shared folder 
https://drive.google.com/a/kartoza.com/folderview?id=0B_OO5LIaN7-xfktHVmN6N3RLYmFyUV85SWU3bm0xVTB1clVfNnBRRkRadHdhQWQ2MnpZdTA&usp=sharing_eid&tid=0B_gC8poAYEtefm4yVzFtVWNtR1J1eGc2SEJjeVM3d1pnM3FUSGJqUkdVQWlKUGYxM1R1dzQ

All the best

**Comment by Charlotte-Morgan** [comment]
Hi @MariaSolovyeva - thank you so much for making the tweaks. Can you please confirm that you are working with the previously approved postcard file or have you made a new file with different proportions? 

I have ticked off above the tweaks that have been made however there are some new things to fix :(
- [ ] InaSAFE should always be spelled "InaSAFE" - please fix first line
- [ ] typo in text - replace realistis with realistic
- [ ] no hypenation in scenario or in any of the text please
- [ ] no line break before "it also calculates ...  in the "how does it work section"
- [ ] the logos should only be on the back of the postcard
- [x] the logos look much better - thank you but maybe a bit bigger than last time?

- [ ] a banner file (if you made something special) should have the front and back of the postcard all on one side (ie its a one sided banner). 

- [ ] has anyone supplied the Indonesian file, because this is the one we need for Monday? - @iyan31 
- [ ] we still need to get a QGIS mention in there - @timlinux 
- [ ] we still needed the same tweaks made to the postcard file.

# cc 
@timlinux @fredychandra @adissadis @samnawi

**Comment by MariaSolovyeva** [comment]
Hi @Charlotte-Morgan , I was working on the file with the new proportions. But it is OK, I will make the necessary changes to the poster files as well and will merge the both sides into one for the banner. I will upload the files today. All the best!

**Comment by MariaSolovyeva** [comment]
The files are uploaded here: https://drive.google.com/drive/u/1/folders/0B_OO5LIaN7-xfktHVmN6N3RLYmFyUV85SWU3bm0xVTB1clVfNnBRRkRadHdhQWQ2MnpZdTA

**Comment by iyan31** [comment]
Apologies for the delay, the translated version can be accessed here: https://drive.google.com/folderview?id=0ByCluDMnTfMPfnZrendEQVhnemtWZlQwenlSN2tVSUo0VmNLblNVQTg1Q1NzQnVYenkzUWc&usp=sharing

**Comment by Charlotte-Morgan** [comment]
Thanks @iyan31. To you have the files in an editable format or at least the text in a format that @maria can cut and paste?

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva - thank you this is looking great.
Banner: - wonderful :)
- [ ] bold in header should be on "free software" not "better planning"
- [ ] still need a QGIS mention - @timlinux 

Postcard (English) - front
- [ ] bold in header should be on "free software" not "better planning"

Postcard (English) - back
- [ ] swap headings for "Who can use it" and "How does it work"
- [ ] logos are great :)

Postcard (Indonesian) - waiting for text

**Comment by iyan31** [comment]
Hi @Charlotte-Morgan and @MariaSolovyeva, we just found and uploaded the .psd file in the folder that I shared previously, or I can just put it here the link again:
https://drive.google.com/folderview?id=0ByCluDMnTfMPfnZrendEQVhnemtWZlQwenlSN2tVSUo0VmNLblNVQTg1Q1NzQnVYenkzUWc&usp=sharing#list 

Let me know if you need anything else

**Comment by Charlotte-Morgan** [comment]
+1 - thanks.
lets make sure these final files are stored in Github and that becomes the place we go for files anytime we need to print / update etc.

**Comment by MariaSolovyeva** [comment]
Hi @Charlotte-Morgan and @iyan31 , the files are re-uploaded, Indonesian versions are added.
https://drive.google.com/drive/u/1/folders/0B_OO5LIaN7-xfktHVmN6N3RLYmFyUV85SWU3bm0xVTB1clVfNnBRRkRadHdhQWQ2MnpZdTA

**Comment by timlinux** [comment]
> +1 - thanks.
> lets make sure these final files are stored in Github and that becomes the place we go for files anytime we need to print / update etc.

Agreed  - I am busy adding the updated versions to github inasafe-graphics.

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva - this is all looking great.
Can you please correct the spelling on Indonesian Versions 
correct spelling is "ANCAMAN" not "ANKAMAN"

@fredychandra @iyan31 @samnawi - can you please proof read Indonesian products ?

**Comment by MariaSolovyeva** [comment]
the spelling is fixed

**Comment by Charlotte-Morgan** [comment]
ooh - i just added some more :(

**Comment by iyan31** [comment]
Thanks a lot @MariaSolovyeva! @Charlotte-Morgan @regiaandi can do some spelling edits and re-upload the result if that is okay

**Comment by Charlotte-Morgan** [comment]
thanks @iyan31  and @regiaandi - that would be great

**Comment by Charlotte-Morgan** [comment]
InaSAFE Poster has been cleared by DFAT and approved for printing. 
Thanks everyone
