### ISSUE TITLE
Fix postprocessor settings summary in the IFCW  

### ISSUE THREAD

**Issue by borysiasty** [AIFDR/inasafe#2038]
@ismailsunni @akbargumbira @Charlotte-Morgan @timlinux:

Is the following postprocessors summary formatting ok?
For checkboxes (like *Gender* and *MinimumNeeds*) put translatable strings "Disabled" and "Enabled"
For *Age*, there is a list: one checkbox and three numerical values, so I display the param names, of course except of the first boolean value to not duplicate the label. 

![postproc](https://cloud.githubusercontent.com/assets/1000043/8104940/008b2b4a-1035-11e5-9dd8-e2378ad91844.png)

The source of the settings:

![postproc0](https://cloud.githubusercontent.com/assets/1000043/8104926/f1e7b55e-1034-11e5-8795-e07d2dea9384.png)

**Comment by ismailsunni** [comment]
hi @borysiasty 
Looks great...

one comment, is it possible to make minimum needs items in a row by row?
So it will be something like:

-    | -                     | -
------------ | ------------- | -------------
Mimimun needs:    | Rice                     | 3kg
                              | Drinking water      | 18l
                              | Clean water         | 67l
                              | Family kits            | 0
                              | Toilets                  | 0
                              | Provenance          | The minimum needs are based on Perka 7/2008

Ignore the header, the grid,... It's hard to write it in comment... Basically, make it like they are inside invisible table

**Comment by borysiasty** [comment]
Sure, will do
