### ISSUE TITLE
We need a parting gift for @akbargumbira

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2041]
# Problem

@akbargumbira is leaving and I have no gift for him

# Proposed solution

Lets give him this:

![present](https://cloud.githubusercontent.com/assets/178003/8125367/575a683e-110f-11e5-8b26-6805142117a5.jpg)

# Expected Outcome

@akbargumbira opens box and finds everything he wishes for inside.

# CC

@Charlotte-Morgan @ismailsunni @lucernae 

# Final Note

So long @akbargumbira and thanks for all your hard work. Closing this ticket will be the last thing we ask of you...

**Comment by Charlotte-Morgan** [comment]
+1  thanks for everything Akbar :)

**Comment by akbargumbira** [comment]
The expected outcome is not satisfied yet. Make it happy :)

**Comment by akbargumbira** [comment]
sorry, make me happy was what I meant :p

**Comment by lucernae** [comment]
Do you want a wife to make you happy, @akbargumbira ? :p

**Comment by emirhartato** [comment]
:+1:  for the wife idea! and whoever the wife is, she should close this ticket :p

**Comment by timlinux** [comment]
I'm closing this ticket - @akbargumbira told me the thrill and honour of working on InaSAFE all this time has completely eclipsed any need for gifts.
