### ISSUE TITLE
Error when open Set InaSAFE Analysis Area

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#2045]
Problem
-----------
Scenario : on develop branch, open QGIS, click button for launching Set InaSAFE Analysis Area, got this problem:
![python error_029](https://cloud.githubusercontent.com/assets/1421861/8181091/3e258704-144d-11e5-9f31-4e055ea05c23.png)

Does anyone get similar problem?

**Comment by timlinux** [comment]
No I didnt get this - we dropped use of resources so I wonder why you are seeing it? Can you share the specific SHA for the core you are testing against?

**Comment by ismailsunni** [comment]
I use the latest commit: 0d9e8d246fee202934531132dd8a64facca2f74f

![selection_031](https://cloud.githubusercontent.com/assets/1421861/8200944/db0a070e-14f5-11e5-8926-d1dafe03e631.png)
