### ISSUE TITLE
We need to update the web page text

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2050]
This is a list (that will have more added) of things I spotted that need editing for content

Update Blog:
- [ ] Blog events - add missing
- [ ] people - this list needs updating (regularly ?)
- [ ] disclaimer - update branding
- [ ] copyright - update branding

# cc
@timlinux @MariaSolovyeva

**Comment by rduivenvoorde** [comment]
@Charlotte-Morgan @timlinux I actually made the old contents.html the index page:
http://docs.inasafe.org/en/
if you want another index.html I have to revert that....

**Comment by timlinux** [comment]
@MariaSolovyeva Also note that http://inasafe.org/en/general/governance/roles_and_responsibilities.html still needs to be migrated

**Comment by timlinux** [comment]
AIFDR references should be updated where appropriate.

**Comment by Charlotte-Morgan** [comment]
I have prepared new text for the about box in the dock and the about, disclaimer & supporter links.
The proposed new wording is with DFAT for approval. References to AIFDR have been included in this proposed revision

**Comment by Charlotte-Morgan** [comment]
disclaimer is covered in #2244
no idea what copyright i was thinking of
blog events are covered in #2216 

I think this is good to close?
@MariaSolovyeva @rduivenvoorde - anything else?

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva - i had a go at editing the people page on the website. I updated the affiliations and replaced reference to AIFDR. I notice there are still some spare columns for role and description. Do we still need these or can they be removed? Or maybe you can say what should go in them?
thanks

**Comment by MariaSolovyeva** [comment]
hi @Charlotte-Morgan , the empty cells are removed

**Comment by Charlotte-Morgan** [comment]
that's great thank you
