### ISSUE TITLE
We need some posters

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2057]
# Background:
We (RnV) have been invited to contribute display materials for the CDSP (Capacity Development Support Program) closing event. This is an opportunity to showcase the work of AIFDR and in particular to promote the science program, the risk assessment & contingency planning work, OSM and HOT, InaSAFE and the end to end delivery of science to the community.

I have said yes we will do it. 
I'm now looking for some magic from HOT, RnV & Kartoza to make it happen.

# Details:
- [ ] the event is on 25 & 26th June in Bogor
- [ ] materials are required in Jakarta for printing on 23rd June
- [ ] the event will involve booths (one for each of 4 priority provinces) & workshops
- [ ] display material we prepare will be part of the main booth & provincial booths
- [ ] we are expecting to be invited to the event - so we can wear our t-shirts!

# Materials Requested:
- [ ] published hazard maps for each province - to be combined into province specific graphics
- [ ] poster showing risk assessment process - emphasis on infographics

# Proposal for products:
- [ ] that poster materials be prepared as standing banners (size to be confirmed)
- [ ] that the hazard maps be presented in a format suitable for projection in a 42" TV screen
- [ ] that the materials can be 'reworked' for other events in the future
- [ ] that a single hazard map design is prepared but produced in 4 versions - one for each province
- [ ] that a single poster is designed but produced in 4 versions - one for each province
- [ ] that its all in Indonesian
- [ ] this is not just about InaSAFE but provides an opportunity to create materials that can be reused in different contexts.

# Proposed Action:
- [x] @MariaSolovyeva to confirm that she is able to do this work within the given time frame
- [x] @timlinux to confirm that Kartoza are able to support this effort

- [x] @fredychandra & @samnawi (AIFDR) to prepare poster concept diagram today
- [x] @samnawi to supply TV hazard concept diagram today
- [x] @samnawi to share hazard poster maps today
- [x] @fredychandra to confirm poster size tomorrow
- [x] @iyan31 @adissadis (HOT) to share province specific materials for contingency planning and risk assessment to AIFDR (may i suggest a shared folder rather than email)
- [x] AIFDR to supply content to Kartoza (text, diagrams, etc).
- [x] @fredychandra & @samnawi (AIFDR) to prepare poster concept diagram today

- [x] DFAT to confirm branding and logo content :)
- [x] HOT and RnV to proof read.

# Contributors:
@MariaSolovyeva @timlinux @fredychandra @samnawi @iyan31 @adissadis (please add more HOTTIES here) @davidr007 .. can't tag myself :)

please update, add and tick off items as required.

**Comment by MariaSolovyeva** [comment]
I confirm, awaiting for the materials! :)

**Comment by Charlotte-Morgan** [comment]
great thank you - i just updated the requirements again.

**Comment by timlinux** [comment]
Big +1 frim Kartoza to support this

**Comment by fredychandra** [comment]
@MariaSolovyeva 
Please find the rough concept of the Risk Assessment process that we plan to develop the info graphic. If you can not access the link, please send me your email address to chandra.fredy@gmail.com? I need it also to send some materials for your reference to capture the substance. Thank you.
 
https://docs.google.com/document/d/1BOJ_cbT9uRvPUtFxuMA-aSG5ta7jzmn3GSLHYmceWDU/edit

**Comment by fredychandra** [comment]
Update : 
1. The info graphic size  : (80 x 200) cm (need to re-confirm)
2. We only need one Risk Assessment Process info graphic because it is same process in each provincial 
3. CDSP (Widya) prefer the info graphic of the output of risk assessment from each provinces are developed separately (not include in risk assessment process info graphic), so each provinces have their own for detail. This can be displayed on 42" TV at each booths. 

tomorrow we will have technical meeting at 2 p.m. with CDSP guys to discuss for more detail. I will update more after.

**Comment by Charlotte-Morgan** [comment]
@fredychandra - please set up a google folder for this project. Maria's email is maria@kartoza.com

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva - the risk assessment process reports against 5 sectors: Human, Infrastructure, Social, Environment Resources (landuse, agriculture), Economic.  Maybe you can start by finding infographics for these sectors

**Comment by MariaSolovyeva** [comment]
@fredychandra I can access the link, thank you!

**Comment by iyan31** [comment]
We already start sharing the maps inside folder that is shared by Fredy in "Map Products"

**Comment by Charlotte-Morgan** [comment]
Thanks @iyan31  & Hotties.
We need to stay focused on materials that are directly relevant for this purpose
Ideally, we want to use items that are:
- [ ] relevant to the priority provinces
- [ ] relevant to the risk assessment process
- [ ] illustrate specific aspects of the risk assessment process or products
- [ ] maps have marginalia that explain source, date, etc with current logos if possible

**Comment by iyan31** [comment]
Understood, will revise and focus on the relevant materials

**Comment by fredychandra** [comment]
Update :
 1. The available space for Risk Assessment Process info graphic is 200 x 240 cm (Fix)
 2. There are 4 available space (size 120 x 80) at foyer. I think we can put InaSAFE postcard to fill one space to promote InaSAFE. 
We just need to share the electronic file to ashep.ramadhan@gmail.com. Ashep will organize and print it then put it into that space.

**Comment by Charlotte-Morgan** [comment]
please see #2030 first before electronic file for the postcard is shared

**Comment by fredychandra** [comment]
Hi @maria. We need to finish the graphic tomorrow morning at 10 a.m. The Event Organizer will bring the material to the venue lately tomorrow 2 p.m.

**Comment by Charlotte-Morgan** [comment]
Hi @Maria - an update on requirements and materials supplied. 
Thanks for your time to discuss the progress earlier today.

1. Risk Assessment Process Poster - in Indonesian
this is a single poster showing the general process which is the same in all provinces.
Text and links to illustration materials are shared in the Risk Assessment Process document. https://docs.google.com/document/d/1BOJ_cbT9uRvPUtFxuMA-aSG5ta7jzmn3GSLHYmceWDU/edit
Required 10am tomorrow for printing.

2. InaSAFE Banner - In Indonesia - InaSAFE themed
I believe this is almost done - HOT are making minor tweaks to spelling
Thank you :)
Required tomorrow for printing

3. Hazard Slide Show to fit a 42" TV screen
1 for each province (4 files)
Links to files for each province and logos are provided in the Risk Assessment Process document.
Required Wednesday (I'll deal with any fallout)

4. Risk Assessment Results to fit a 42" TV screen
1 for each province except West Sumatera (3 files)
Links fo files for each province and are provided in the Risk Assessment Process document.
Required Wednesday (I'll deal with any fallout)

Iwan has narrowed down the number of files available :)

I hope this is making sense and apologies if requirements keep changing :(
I am confident that we now have the requirements refined and everything you need has been provided (except maybe a wizard to work some magic).
Please ping me on hipchat if you need anything later today & good luck with making it all beautiful. 

thanks everyone who has contributed materials so far

**Comment by Charlotte-Morgan** [comment]
Hi @Maria - thank you so much for turning our ideas into good looking products at such short notice.
Risk Assessment Poster:
We have a few minor corrections that we hope you can do by 2pm today when we can send the files for printing.
InaSAFE Banner: this is looking good - will be send for printing at 2pm today
TV Screen hazard map slide show: - ready for iwan to deliver Thursday morning
TV Screen Risk Assessment results slide shows: - ready for Iwan to deliver Thursday morning

@timlinux @fredychandra @samnawi @iyan31

**Comment by Charlotte-Morgan** [comment]
hi @Maria - plan B
@samnawi is tweaking the Risk Assessment Poster - so that it is finished in time.
Can you please work on the TV Screen slide shows :)

**Comment by Charlotte-Morgan** [comment]
poster approved by Dom for DFAT :)
