### ISSUE TITLE
Analysis error with Polygon flood on people run on the test data

### ISSUE THREAD

**Issue by borysiasty** [AIFDR/inasafe#2059]
I get an analysis error with Polygon flood on people.

Steps to reproduce
-------------------------

1. Load the Population layer from the test dataset (pop_binary_raster_20_20.asc) .
2. Load the Flood Polygon Cross Kabupaten layer from the test dataset (flood_polygon_crosskabupaten.shp).
3. Set a reasonable analysis extent, for example covering all the Flood area (otherwise another error caused by with insufficient overlap may interfere).
4. Run the analysis ("Need evacuation" from the dock or "Polygon flood on people" from the wizard).
5. The result is below.

Output from the results browser (selected sections)
--------------------------------------------------------------------

**Problem**

The following problem(s) were encountered whilst running the analysis.
- TypeError

**Details**

These additional details were reported when the problem occurred.
- An exception occurred when running the impact analysis.
- a float is required

**Diagnostics (click for details)**

1. In file "/home/borys/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 965, in run_analysis self.run_aggregator()
2. In file "/home/borys/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 891, in run_aggregator self.run_post_processor()
3. In file "/home/borys/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 905, in run_post_processor self.postprocessor_manager.run()
4. In file "/home/borys/.qgis2/python/plugins/inasafe/safe/impact_statistics/postprocessor_manager.py", line 482, in run value.process()
5. In file "/home/borys/.qgis2/python/plugins/inasafe/safe/postprocessors/gender_postprocessor.py", line 61, in process self._calculate_total()
6. In file "/home/borys/.qgis2/python/plugins/inasafe/safe/postprocessors/gender_postprocessor.py", line 83, in _calculate_total result = int(round(result))

**Comment by borysiasty** [comment]
Btw. @ismailsunni suspects it's not related to #1158.

**Comment by ismailsunni** [comment]
I think it's not related. Based on the error message, it shows that it's related to postprocessor parameter (asking for float). *I just retell the error message :)

**Comment by ismailsunni** [comment]
This error only occurs in QGIS 2.8.2. I checked with QGIS 2.8.3, it's running as expected. Closing this.
