### ISSUE TITLE
Wizard window is off the screen

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2062]
# problem
both the wizard windows are off the top of my screen.
environment: QGIS 2.8, InaSAFE 3.2dev, windows laptop

# proposed solution
make it behave

**Comment by borysiasty** [comment]
Again??? :(( We'll see...

**Comment by adissadis** [comment]
it same with issue #2021

**Comment by Charlotte-Morgan** [comment]
i think this is fixed now - closing this
