### ISSUE TITLE
Layer Keyword Version

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#2069]
Problem
======
We need to store version of keyword that we uses in the layer's keywords

Proposed Solution
==============
Add layer's keyword version.
- Using key `keyword_version`.
- For the next release of InaSAFE v3.2 we will use keyword_version=3.2
- Handle the version writing in lower level class (KeywordIO or LayerMetadata class)

To Do (now)
==========
- [x] @ismailsunni to write the current version in definitions.py
- [x] @ismailsunni update all test data by putting the version number in the keyword / xml file
- [x] @ismailsunni makes the current KeywordIO write automatically the version number
- [ ] @mbernasocchi make sure the LayerMetadata class also write the version number automatically and add property for it.

Future Usages
===========
- Show to the user that they have unsupportable version of keyword (if there is no keyword version or has previous version number in the keywords / xml file). We can adapt how QGIS handle a project that saved from previous QGIS version
- Create converter from previous keyword version to the current keyword version, if possible.

CC @timlinux @Charlotte-Morgan @cchristelis @Jannes123 @Gustry @borysiasty @lucernae

**Comment by timlinux** [comment]
+1 for this, thanks @ismail

**Comment by ismailsunni** [comment]
I made a PR for this in #2072 , can you review it @timlinux  ?

**Comment by ismailsunni** [comment]
Pass to you @mbernasocchi

**Comment by Gustry** [comment]
Do we need to patch the OSM Downloader too ?
Currently, the downloader will ship XML or keywords file according to the inasafe version but the version number is not written in the file.

**Comment by ismailsunni** [comment]
Hi @Gustry 
No need to do that. I made the changes in KeywordIO, so if the downloader will be automatically written by it. And I just checked it for make sure, and it does write the version. So, no need to patch.

**Comment by mbernasocchi** [comment]
adressed in #2173
