### ISSUE TITLE
Icon about the networking analysis

### ISSUE THREAD

**Issue by Gustry** [AIFDR/inasafe#2076]
I've started the new icon about the networking analysis tool.
https://github.com/Gustry/inasafe/blob/routing/resources/img/icons/show-routing-analysis.svg

Is it possible to have a icon with the new inasafe theme. The icon can represent a street network.

**Comment by MariaSolovyeva** [comment]
@Gustry , I've just sent you the file with the icon by e-mail.

**Comment by Gustry** [comment]
Thanks @MariaSolovyeva 
I will come back to you if needed.
