### ISSUE TITLE
Run button disabled if the selected analysis area is not set correctly

### ISSUE THREAD

**Issue by wonder-sk** [AIFDR/inasafe#2077]
Sometimes I forget to setup analysis area for my analysis, so the previously used area is going to be used. However, if there is no overlap between the analysis area, exposure and hazard layers, the "Run" button is disabled... even though InaSAFE tells me "You can proceed to run your model by clicking the Run button." I got reminded of Catch XXII :-)

Would it be possible to improve the feedback somehow so that the user is not left wondering what to do to fix the disabled Run button?

I would suggest to keep the Run button enabled, and if it is clicked with wrong area set up, InaSAFE will tell the user to fix the area (without actually running the impact function). Or have some kind of 'warning' icon and message next to disabled Run button...

**Comment by timlinux** [comment]
Agreed - I will fix this - though with a different approach to suggested - disable run button and show informative message in dock where possible (replace 'press run message if it is there, leave keywords etc messages alone if they are shown)
