### ISSUE TITLE
Fix Failing Test in QGIS 2.8.2

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#2078]
Problem
----------
I upgraded to QGIS 2.8.2 and got several failed test. See here https://gist.github.com/ismailsunni/9ed321370fcb0d487a3d

It seems Jenkins still use QGIS 2.8.1 (because no failing tests). We should update Jenkins also to use QGIS 2.8.2.

From @wonder-sk : in general it would be good to move away from 2.8.1, because it has a bug that makes land cover analysis unusable

To Do:
- [ ] Fixing failed test in QGIS 2.8.2
- [ ] Update Jenkins to use QGIS 2.8.2 

CC : @timlinux @Charlotte-Morgan @Gustry

**Comment by ismailsunni** [comment]
Some issues related to this 
- Analysis error with Polygon flood on people run on the test data #2059 
- Postprocessing fails with QGIS-master (will be 2.10) #2010
- Error When Run FloodVectorRoadExperimentalFunction #2065

An which version of QGIS we want to support for InaSAFE 3.2 @timlinux ?

**Comment by timlinux** [comment]
> I upgraded to QGIS 2.8.1 and got several failed test. See here

Do you mean 2.8.2 in that sentance?

**Comment by ismailsunni** [comment]
@timlinux 
Yes, typo. It should be 2.8.2. Fixed now.

**Comment by timlinux** [comment]
Can we close this? We should use 2.8.3 for tests - and all tests seem to pass ok on travis.

**Comment by ismailsunni** [comment]
Closing this. We want to support QGIS 2.8.3. Related issue #2188
