### ISSUE TITLE
Wizard - should work with data already loaded in QGIS

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2081]
# problem
The IF Wizard (Guided impact assessment wizard) does not recognise data loaded in QGIS 

# proposed solution
the IF wizard should allow users to work with data already loaded in QGIS and then launch the KW wizard to update key words as required. If not the user is forced to reload data in existing project files.

**Comment by borysiasty** [comment]
Could you please provide a sample layer that is affected?

**Comment by Charlotte-Morgan** [comment]
@borys - apologies for the delay getting back to you, i'm trying to give comment on this but ongoing problems with wizard doing a disappearing act #2207

I think it happens to any layer - but will check and get back

**Comment by borysiasty** [comment]
@Charlotte-Morgan - currently, the wizard lists all visible layers with matching keywords as well as those keywordless (with italic font). So if you can't see your layer it means either:
 - the layer has keywords, but they are unsuitable (or just obsolete!)
 - the layer visibility is off

I'm not sure what exactly do you want to change:
 - just the problem of obsolete keywords should be fixed
 - disabled layers should be listed as well 
 - also layers with unsuitable keywords should be listed with gray font, with a description what exactly is not matching
 - all above ;)

**Comment by Charlotte-Morgan** [comment]
i think this has been fixed - closing this one
