### ISSUE TITLE
Wizard - Volcano hazard point options

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2085]
In the KW wizard, I think that we should be able to select single event when assigning key words to a volcano xy point. 
Are volcano xy points considered to be classified data based on the name field?
@ismailsunni ?

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
IIRC, we considered it as classified data, since we classify the zone around the point to some classess; Low, Medium, and High.

If you think it should be able to work on single event, I can update it.

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - i have tried again to assign key words to a single volcano xy data set and then to run the volcano impact function and i think something is missing.
A volcano xy point needs to be a single event where any 'classification' should relate to the name field.
At present i do not get the option to choose single event.
I should then be able to run "point volcano on buildings" - this works now but only if i use the multiple event radio button in the IFW.
Please update to make this a single event option :)

**Comment by ismailsunni** [comment]
I am making PR #2095 for this.

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - LGTM - this PR:
- [x] allows a volcano xy point to be a assigned the single event key word
- [x] allows users to select point volcano on buildings IF in the IFW

I think that i should add some text to the classified option in definitions.py to explain that classified also describes the buffer distances from a volcano point.

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan 
Great. I will merge it then.
