### ISSUE TITLE
Wizard - auto select defaults

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2086]
In many cases, if only one option is available in a wizard step, the option is already highlighted and the next button is active.

However, in some cases , eg exposure, roads, classified - the single option is not active.
Please update so that any time there is no choice, the single option is active and the next button is also active

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
I am checking this bug, and it seems, all is fine. See my screen record here https://youtu.be/3SxAGlqOC_I

**Comment by timlinux** [comment]
Can you check that list items are really shown as selected - I think the confusion relates to the fact that the item is selected but doesn't appear to have the same selection look as when they user has clicked on it with the mouse.

**Comment by Charlotte-Morgan** [comment]
i think this is fixed
