### ISSUE TITLE
Wizard - UI - no valid key words message

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2092]
# problem
The UI messages do not fit neatly in the window.
![Uploading image.png…]()

# proposed solution
make it happy

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan can you re-upload the image. It seems the uploading process is not finished.

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - try this one

**Comment by ismailsunni** [comment]
@Charlotte-Morgan Still no image...

**Comment by Charlotte-Morgan** [comment]
![image](https://cloud.githubusercontent.com/assets/5743135/8544104/9c00ece4-24cc-11e5-8bd0-436ff2eb61e4.png)

**Comment by Charlotte-Morgan** [comment]
@ismailsunni - i hope you can see this one

**Comment by ismailsunni** [comment]
I tried to add <wbr> tag in the source text. But, apparently, Qlabel doesn't recognize it (?).

**Comment by borysiasty** [comment]
@Charlotte-Morgan, is it still valid? I can't reproduce.

**Comment by Charlotte-Morgan** [comment]
no - i have not seen this for a while - closing this now

**Comment by ismailsunni** [comment]
Hi, I checked this issue. So, it seems the wizard use scroll bar for it. Great.

![inasafe impact function centric wizard_059](https://cloud.githubusercontent.com/assets/1421861/9653293/a7129fbc-524c-11e5-9e4e-f289e083ca94.png)
