### ISSUE TITLE
Volcano Report - not reading name attribute

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2099]
# problem
The Volcano IF are not reading / reporting the name of the volcano.
![image](https://cloud.githubusercontent.com/assets/5743135/8565137/d918cea2-257c-11e5-8eb5-dbf3fdb34c96.png)

# proposed solution
make it happy

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan  Do you mean InaSAFE doesn't obtain the volcano's name from layer's attribute that you have set in the wizard?

**Comment by Charlotte-Morgan** [comment]
i think this bit is not picking up the name and we end up with the else: option
![image](https://cloud.githubusercontent.com/assets/5743135/8565443/2c89f2c0-2580-11e5-93b7-a7bfe7310caf.png)

**Comment by ismailsunni** [comment]
So the state in develop, it will find attribute called "NAME" to find the volcano name. We hard coded this.

I have fixed it on my PR #2080. In this PR, InaSAFE will use the attribute name that user has set in layer's keywords.

**Comment by ismailsunni** [comment]
this is closed by #2127
