### ISSUE TITLE
IF Issues : Volcano Point Report - Agregation not appear

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2103]
# Problem
I doing volcano analysis use the aggregation. 
The report is fine when it use to analysis the population impacted.
![selection_051](https://cloud.githubusercontent.com/assets/8871958/8587555/b4ef80ec-2627-11e5-9854-801a76c317cd.png)

But, when I try to use it to analysis buildings (point & polygon) and infrastructure (point), the aggregation result not appear in the report
![selection_055](https://cloud.githubusercontent.com/assets/8871958/8587689/a3e8b08c-2629-11e5-9c51-508cfbf7a005.png)
![selection_056](https://cloud.githubusercontent.com/assets/8871958/8587691/a8710f14-2629-11e5-86ed-5cbc5d4f84c0.png)

cc :
@Charlotte-Morgan 
@timlinux 
@ismailsunni

**Comment by cchristelis** [comment]
Fixed in PR, please review.
