### ISSUE TITLE
IF Issue : Volcano Polygon - Aggregate issue

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2104]
# Problem
Same when I doing IF with volcano point, the similar event occurs again in here. The aggregation result not appear in the report when I use it to analysis buildings (point and polygon) and infrastructure (point).
![selection_057](https://cloud.githubusercontent.com/assets/8871958/8587899/35873fce-262d-11e5-9018-42563596a9c1.png)
![selection_058](https://cloud.githubusercontent.com/assets/8871958/8587903/37e401d0-262d-11e5-81f2-8bdad4da7838.png)

Also, there is an error report when I use it to analysis the population and then the result aggregated by villages, whereas when I use it to analysis the population impacted without aggregation, the result is fine.
**Population Analysis with aggregation**
![selection_059](https://cloud.githubusercontent.com/assets/8871958/8587965/4521ba12-262e-11e5-9eea-862ef4e2b8b1.png)

**Population analysis without aggregation**
![selection_060](https://cloud.githubusercontent.com/assets/8871958/8587970/56733c96-262e-11e5-863e-5671fccf1a64.png)

# Proposed Solution
Make it happy

cc :
@Charlotte-Morgan 
@timlinux 
@ismailsunni

**Comment by cchristelis** [comment]
Fixed in PR, please review.
