### ISSUE TITLE
Wizard - Volcano Polygon Population IF option

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2107]
# Problem
There is a few confusion in the step of InaSAFE wizard. 
I try to do an analysis volcano polygon population IF using the InaSAFE wizard. 
In the step to select the polygon volcano hazard, there are 2 options: 
* Classified polygon hazard on population.
  * Function: Classified polygon hazard on population.
  * Overview: To Assess the number of people that may be impacted by each hazard zone.
* Polygon volcano on population
  * Function: Polygon volcano on population.
  * Overview: To Assess the impact of a volcano eruption on people.

![volcano wizard](https://cloud.githubusercontent.com/assets/8871958/8613814/511e7960-270d-11e5-89db-cd71aa7773cf.png)

1. In my assumption, if I choose the *Classified polygon hazard on population*, it means that we will use the hazard zone map (KRB form PVMBG). But in the in the reality: 
  * When I create the keyword for the volcanic hazard map using *volcano classes*, the hazard map can not use in the option of *classified polygon hazard on population* .
  * When I create the keyword for the volcanic hazard map using *generic classes*, the hazard map can use in the option of *classified polygon hazard on population*.

2. As the user, because we have been chosen volcanic IF, so in my mind for the 2 options is all about volcanic hazard:
  * Classified polygon hazard on population --> its will use Volcanic hazard (KRB from PVMBG), because in the overview write *....impacted by each hazard zone*.
  * Polygon volcano on population --> its like use for hazard map in single event like pyroclastic flow.

# Proposed Solution
Make it happy.
Make the overview for each class is clearer, because it's like ambiguously. 
Maybe the overview can be written like this:
* First IF
  * Function: Classified polygon hazard on population
  * Overview: Using volcanic hazard map that agreed by some agency or government.
* Second IF
  * Function: Polygon volcano on population
  * Overview: Using the real hazard polygon as the event in the location, like pyroclastic flow area, etc.

# CC
Please add some comment from @ismailsunni and @fredychandra like we have been discussed before

**Comment by fredychandra** [comment]
# PROBLEM
Also If we choose classified polygon hazard on population (fig.1) then the hazard layer will not be detected on (fig.2). Then we can not continue to run this IF wizard.

Fig. 1
![image](https://cloud.githubusercontent.com/assets/6345285/8665548/53b79e9a-2a0f-11e5-92e7-a576c56f3891.png)

Fig.2
![image](https://cloud.githubusercontent.com/assets/6345285/8665451/6bf75708-2a0e-11e5-83ef-dad53914e445.png)

# Proposed Solution
Make it detected. 

CC : @samnawi @ismailsunni  @timlinux @Charlotte-Morgan 
The Classified polygon hazard on population overview looks more suitable to used if the hazard layer source come from ESDM-Badan Geologi (Volcanic Hazard Zone- Peta KRB Gunungapi)

**Comment by ismailsunni** [comment]
Hi @samnawi 
After I read again both impact functions (IFs), I can reply your questions:
Both of the IFs are used for hazard zone (or KRB), not single event. The difference is only the classifications. For `Classified polygon hazard on population` you need to use generic classifications. For `Polygon volcano on population` you need to use volcano hazard classes.

I can make one of them (or both) work for single event. But, we need to ask @Charlotte-Morgan whether is it right to make it so or not.

Hi @fredychandra 
From fig 2, the wizard shows all suitable hazards. What hazard that doesn't come out? Can you paste here the keywords.
I suspect that the layer use volcano classes. And it won't be detected by classified polygon hazard on population. The classified polygon hazard on population only accept generic classes for the classification.

**Comment by Charlotte-Morgan** [comment]
@fredychandra & @samnawi - can you please look at this again

**Comment by samnawi** [comment]
@ismailsunni I've latest version of InaSAFE 3.2, and it's look like I expect in the issue. But, for the IF that should be just in multiple event or also available in single event, my expectation is just if there is a data like pyroclastic flow or spread of the heat cloud, I think InaSAFE must have tool to calculate this impact.

The data maybe just a footprint, so the attribute can be like the flood (impacted : yes or no).
The example of kind the data that I mean, I upload in here https://www.dropbox.com/s/pdwav2cu9bz33hz/Sinabung%20Heat%20Clouds.zip?dl=0

Thank you

cc : @Charlotte-Morgan @fredychandra

**Comment by fredychandra** [comment]
@ismailsunni I have check it and tested it again using Qgis 2.8.3 and InaSAFE 3.2 Dev-Master. It works :) . I am not sure for the last keyword that I using when rise this problem issue, but for this recent test I am using both generic classes and volcanic classes, and it works.

**Comment by ismailsunni** [comment]
Since we have set all IF to have both single and multiple event hazard category, we can close this ticket. See the PR #2251
