### ISSUE TITLE
Error in Keywords creation wizard for flood raster layer (using meters as unit)

### ISSUE THREAD

**Issue by machakux** [AIFDR/inasafe#2111]
Error in creating a keywords for a raster layer using keywords creation wizard. 

When creating keyword using the wizard everything goes well except in the last stage which gives the `TypeError` 

    An error has occured while executing Python code:

    Traceback (most recent call last):
      File "/home/user/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard_dialog.py", line 3014, in on_pbnNext_released
        self.set_widgets_step_kw_source()
      File "/home/user/.qgis2/python/plugins/inasafe/safe/gui/tools/wizard_dialog.py", line 1404, in set_widgets_step_kw_source
        self.leSource_date.setText(source_date)
    TypeError: QLineEdit.setText(QString): argument 1 has unexpected type 'int'

    Python version:
    2.7.6 (default, Mar 22 2014, 23:03:41) 
    [GCC 4.8.2]

    QGIS version:
    2.8.2-Wien Wien, exported

    Python path: ['/usr/share/qgis/python/plugins/processing', '/home/user/.qgis2/python/plugins/GeoCoding/libs', '/usr/share/qgis/python', u'/home/user/.qgis2/python', u'/home/user/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', u'/home/user/.qgis2//python', '/home/user/.qgis2/python/plugins/mmqgis/forms', '/home/user/.qgis2/python/plugins/inasafe', '/home/user/.qgis2/python/plugins/inasafe/safe_extras/parameters', '/home/user/.qgis2/python/plugins', '/home/user/.qgis2/python/plugins/inasafe/safe_extras', '/usr/share/qgis/python/plugins/fTools/tools']

Things seems to work fine if I create the keyword file manually using a text editor

category: hazard
subcategory: flood
unit: meters 
...

QGIS version: 2.8.2
Inasafe version: 3.1.0 (Installed from default QGIS plugin repository)
OS: Ubuntu 14.04 64bit

cc: @vdeparday

**Comment by timlinux** [comment]
Was it a raster or vector flood layer you had @machakux ?

**Comment by timlinux** [comment]
Also could you share the dataset you used so that we can test with it?

**Comment by machakux** [comment]
It was a raster layer @timlinux

**Comment by ismailsunni** [comment]
From my investigation:
The wizard save a string as a integer (in this case, source's date), if it's only contains integer character (e.g. 2015, 1234, etc). *Based on the error message.

I have fixed it and made a PR in #2122

**Comment by timlinux** [comment]
Thanks @ismailsunni - can you backport to master too please?
