### ISSUE TITLE
We need to fix various issues with volcanos

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2125]
@ismailsunni kindly compiled this list of volcano related issues. Since there is some activity right now relating to volcanos it would be good to tackle these and backport to 3.1 release too until 3.2 is ready.

- [ ] #2107 @ismailsunni 
- [x] #2105 @cchristelis 
- [x] #2104 @cchristelis 
- [x] #2103 @cchristelis 
- [x] #2099 @ismailsunni
- [x] #2090 @cchristelis 

for #2099 will be fixed after finisihing the safelayer

**Comment by cchristelis** [comment]
When we backport #2103, #2104 and #2015 we also need to backport #2144, since the building totals where wrong and have been fixed there.

**Comment by cchristelis** [comment]
Issues are in PR #2146.
