### ISSUE TITLE
Python Error on aggregation keyword process

### ISSUE THREAD

**Issue by fredychandra** [AIFDR/inasafe#2128]
# PROBLEM
Python error occurs when I run keyword for aggregation on female ratio attribute input step.

![image](https://cloud.githubusercontent.com/assets/6345285/8692487/c0068996-2af8-11e5-9797-18f8fd978cfe.png)

# PROCESS
1. Open Aggregation keyword 
2. Selected aggregation layer attribute 
3. Defined the female ratio attribute and then when press next button the python error occured

# Operating System
- [ ] Windows 8, 64 Bit
- [ ] Qgis 2.8.2 
- [ ] InaSAFE 3.2.0 Dev-master

# Data
- [ ] District of Jakarta layer.shp

# Proposed Solution
Make it works, so we can continue to process aggregation keywords and run IF with aggregation

CC : @ismailsunni

**Comment by ismailsunni** [comment]
This issues is fixed in develop and have been patched to master and released in 3.1.2. See similar issue in #2111
