### ISSUE TITLE
Minimum needs profile manager fails when adding a new item

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2142]
```
Traceback (most recent call last):
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_manager_dialog.py", line 574, in save_resource
    self.add_resource(resource)
  File "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gui/tools/minimum_needs/needs_manager_dialog.py", line 243, in add_resource
    item.setText(updated_sentence)
RuntimeError: wrapped C/C++ object of type QListWidgetItem has been deleted

```

Options I used are as per notes below:

Press the new button to create a new profile. A dialog will appear asking for the name of your profile. Call it ‘training’ and press ‘save’.

The first thing to do is to enter the ‘provenance’ for the profile. Typically you should enter a short statement explaining which legislation or guideline was used to define this needs profile. In our case we will just use a sentence like ‘Needs as defined for InaSAFE Training Course’ to make it clear that this is just a training profile.

Now click the add button and create a new need item with the following properties.

name, description, units (in singular, plural and abbreviated forms), specify maxima and minima for the quantity of item allowed, a default and a frequency.

<img width="576" alt="screen shot 2015-07-22 at 08 37 31" src="https://cloud.githubusercontent.com/assets/178003/8818670/f52a8182-304c-11e5-99ae-d8c2fcd21359.png">

Now press the save resource button

**Comment by timlinux** [comment]
I was using 3.1.2 when encountering the above.

**Comment by ismailsunni** [comment]
@timlinux 
I tried locally, all fine. Which version of QGIS do you use? I use 2.10

**Comment by cchristelis** [comment]
I cannot reproduce this either. If I try a minimum of 5 and maximum of 1 I get an error message. 
When I flip it around to 1 min, 5 max and 2.5 default, I don't get the error. Is there any other information that might help me reproduce this?

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux & @cchristelis 
so i reproduced the original situation and now get a nice helpful error message
![image](https://cloud.githubusercontent.com/assets/5743135/9409531/72959796-4845-11e5-964f-e218b2e75b42.png)

if i enter min and max values the same (actually did this by accident - not really being awkward)
i got a less helpful error message
![image](https://cloud.githubusercontent.com/assets/5743135/9409569/a6ed2252-4845-11e5-9862-cf76024de3db.png)

I now understand what its telling me. would it be possible for the error message to say that the default (value) must be greater than the minimum (value) and less than the max (value)

This PR fixes the original issue - my comment is a papercut
