### ISSUE TITLE
IF Issues : Volcanic Ash - Point Structure

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2156]
# Problem
Thank for @cchristelis as your fix the issue #2105.
But, there is a new problem when I try to run the volcanic ash impacted to centroid building (Point structure). The IF is shown the error when I try to run this function.
![image](https://cloud.githubusercontent.com/assets/8871958/8903894/4b22ae52-3485-11e5-8eee-033b3296415a.png)

In the past, when I run this IF, the process is running until show the report. I try this by changing the Inasafe develop version to SHA 10c28e7 (a day before I post the issue #2015), and this function is run.
![selection_088](https://cloud.githubusercontent.com/assets/8871958/8904008/37e737ee-3486-11e5-8ddf-b537c4db80c3.png)

# Detail
I run use Linux Ubuntu 14.04 and Windows 7, also use the QGIS 2.8.2 and QGIS 2.10, the result is same.

# Proposed Solution
Make it happy

# cc
@Charlotte-Morgan 
@timlinux 
@ismailsunni

**Comment by ismailsunni** [comment]
Hi @samnawi 
I tried to use QGIS 2.8.3, all is fine. Can you check it again by using QGIS 2.8.3 ? Ping me in gitter.im if you need help to install QGIS 2.8.3 in  you Linux.

**Comment by ismailsunni** [comment]
**Update**
By using the data from @samnawi https://www.dropbox.com/sh/vubprsh00b4dh3p/AAAsc3HFfIz9qvlKmCojl2Pja?dl=0 the problem occurs

**Comment by ismailsunni** [comment]
**UPDATE**
This error occurs when we run ClassifiedPolygonHazardBuildingFunction, Polygon Hazard vs Building Centroid. It's not specific to volcanic ash hazard.
