### ISSUE TITLE
Running code in run-env-linux gives wrong result

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#2159]
Problem
----------
While bug fixing, I encounter a case I get different result from the same code between in run-env-linux and QGIS python console.

The code:
```python
from qgis.core import QgsVectorLayer, QgsRasterLayer
QgsVectorLayer('/home/ismailsunni/dev/python/inasafe-dev/safe/test/data/exposure/buildings.shp', 'abc', 'ogr')
a = QgsVectorLayer('/home/ismailsunni/dev/python/inasafe-dev/safe/test/data/exposure/buildings.shp', 'abc', 'ogr')
print a.isValid()
```

From QGIS python console, I got True for a.isValid().
```
from qgis.core import QgsVectorLayer, QgsRasterLayer
a = QgsVectorLayer('/home/ismailsunni/dev/python/inasafe-dev/safe/test/data/exposure/buildings.shp', 'abc', 'ogr')
a.isValid()
True
```

From the environment set by run-env-linux qgis_path, I got False.
```
In [1]: from qgis.core import QgsVectorLayer

In [2]: a = QgsVectorLayer('/home/ismailsunni/dev/python/inasafe-dev/safe/test/data/exposure/buildings.shp', 'abc', 'ogr')

In [3]: a.isValid()
Out[3]: False
```

Does anyone have idea why does this happen?

cc @timlinux @cchristelis @Jannes123 @Gustry @lucernae

**Comment by lucernae** [comment]
I think I encountered these sometimes when I ran the tests. But it is fixed when I called get_qgis_app in the test files.

**Comment by Gustry** [comment]
run-env-linux doesn't create the qgis app. You should call get_qgis_app or 
```
QgsApplication.setPrefixPath("your_qgis_path", True)
QgsApplication.initQgis()
```

**Comment by ismailsunni** [comment]
Hi @Gustry @lucernae 

Thanks for the helps. I think I forgot about it again and again. :)
