### ISSUE TITLE
We need to verify that all fixes from 3.1.x are in develop

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2198]
Only those that can be back ported to develop...

**Comment by ismailsunni** [comment]
List of changes
3.1.1
- This is a bugfix release - it fixes an issue with resizing of the minimum needs configuration dialog.

3.1.2
- Fix: Issue parsing minimum needs - see #2132
- Fix: Error in Keywords creation wizard for flood raster layer (using meters as unit) #2111
- Fix: Error when open Set InaSAFE Analysis Area #2045

3.1.3
- Added Tanzanian minimum needs file
- Fix: Show building aggregation in volcanic ash impact function (#2105)
- Fix: Totals of affected buildings in aggregation regions now calculated correctly (#2144)
- Fix: Show building aggregation in volcano impact functions (#2103 #2014)
- Fix: Prevent hazard attribute names from masking exposure names during interpolation (#2090)
