### ISSUE TITLE
Earthquake polygon IF fails on points layer

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2200]
# Problem

Using the standard test layers, when I try to do

**Hazard:** Earthquake Polygons
* Hazard_category multiple_event
* Keyword_version 3.2
* Title Earthquake Polygon
* Hazard earthquake
* Field h_zone
* Value_map {'high': ['High Hazard Zone'], 'medium': ['Medium Hazard Zone'], 'low': ['Low Hazard Zone']}
* Vector_hazard_classification generic_vector_hazard_classes
* Layer_geometry polygon
* Layer_purpose hazard
* Layer_mode classified

**Exposure:** Building centroids

* License Open Data Commons Open Database License (ODbL)
* Keyword_version 3.2
* Structure_class_field TYPE
* Title Building centroids
* Layer_geometry point
* Source OpenStreetMap - www.openstreetmap.org
* Date 02-04-2015 03:23
* Layer_purpose exposure
* Layer_mode classified
* Exposure structure

**IF:** ClassifiedPolygonHazardBuildingFunction

I get this error:

<img width="347" alt="screen shot 2015-08-21 at 10 27 27" src="https://cloud.githubusercontent.com/assets/178003/9404451/2499b086-47f0-11e5-9a38-292fe1520b65.png">

```
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 971, in run_analysis self.impact_layer = calculate_impact(self.impact_function)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/engine/core.py", line 176, in calculate_impact result_layer = impact_function.run()
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/generic/classified_polygon_building/impact_function.py", line 118, in run self.hazard.layer, self.exposure.layer, wgs84_extent)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/engine/interpolation_qgis.py", line 60, in interpolate_polygon_polygon result = create_layer(target)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/gis/qgis_vector_tools.py", line 125, in create_layer raise WrongDataTypeException(msg)
```

# Proposed solution

We should do more rigorous checks to see the the data formats provided are acceptable, instead of blindly trusting the keywords.

**Comment by timlinux** [comment]
This was the scenario:

```
[Earthquake Polygon]
exposure = ../../Users/timlinux/.qgis2/python/plugins/inasafe/safe/test/data/exposure/building-points.shp
hazard = ../../Users/timlinux/.qgis2/python/plugins/inasafe/safe/test/data/hazard/classified_generic_polygon.shp
function = ClassifiedPolygonHazardBuildingFunction
extent = 39.237270, -6.798558, 39.240305, -6.795975
extent_crs = EPSG:4326
```

**Comment by lucernae** [comment]
Is this still valid?

I test this on Windows 10, QGIS 2.10 Pisa, and it ran happily...

**Comment by timlinux** [comment]
Closing - I cant replicate any more...
