### ISSUE TITLE
BUG : Windows off the screen again

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2207]
# Problem
The OSM downloader and both wizard windows are off the screen again.
I can open the windows & the top is off the screen. I can resize in both directions, the top bar appears and if i try to grab it it disappears again.

# proposed solution
this has been fixed previously - i think

**Comment by timlinux** [comment]
@borysiasty can you look at the wizard please? I will sort out the OSM downloader..Thanks!

**Comment by timlinux** [comment]
@Charlotte-Morgan I have refactored the OSM downloader dialog to look like this:

<img width="701" alt="screen shot 2015-08-22 at 17 21 02" src="https://cloud.githubusercontent.com/assets/178003/9424604/44d75792-48f2-11e5-8ec6-0459bc8c6da3.png">

The changes also make the extent selection more consistent with the extent selector dialog. I believe this dialog will work even on pretty low res screens. See #2211 for relevant PR

**Comment by timlinux** [comment]
Another round of tweaking - it now looks like this on OSX:

![screen shot 2015-08-23 at 00 37 58](https://cloud.githubusercontent.com/assets/178003/9426166/786215e2-492f-11e5-97b4-bce3d5c5c7d5.png)

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - this looks great. Fits on the screen and has some consistency with other UI - CLAF.
that is user interface - consistent look and feel.
Note - cancel and help buttons did not return anything. I did not actually use the queries or run anything - just looked at UI

**Comment by timlinux** [comment]
Thanks @Charlotte-Morgan 

For me the cancel, ok and help buttons are all working on OS X. I will test under windows and linux too to see that they work there.

I also tested that the basic download functionality works. Note that the help functionality no longer pops up a separate browser window, but rather shows the help directly in the dialog. I am going to make this the standard behaviour in all the dialogs.

**Comment by timlinux** [comment]
Oh and I didn't mean to imply that low res-screens are pretty above - the are not :-P

**Comment by borysiasty** [comment]
Ah the nightmare is back. I'll fix it somehow after this Wednesday.
