### ISSUE TITLE
UI: Dock message does not match user selected analysis extent

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2210]
# Problem
the user can now select analysis extent based on the intersection of data, window, book mark etc but in the dock, gets a message saying the analysis is based on window extent

# proposed solution
change the user message text in the dock to say that the analysis extent is as set by the user in the analysis extents selector

**Comment by timlinux** [comment]
Thanks @Charlotte-Morgan I'll fix this...

**Comment by timlinux** [comment]
@Charlotte-Morgan  Can you make a screenshot of the offending text so I can track how it is being triggered in the display?

**Comment by timlinux** [comment]
Just a ping on this to see if it is still an issue and if you can provide a little more light on the matter....Thanks!

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux 
here is a snip of the dock message
![image](https://cloud.githubusercontent.com/assets/5743135/9623954/2e077bcc-5172-11e5-9589-6a553f59abe7.png)
which does not reflect the settings in the analysis area dialog
![image](https://cloud.githubusercontent.com/assets/5743135/9623962/51447284-5172-11e5-955d-57d756f73b01.png)
or that no aggregation was used.

FYI - jakarta flood raster on buildings is the sample data

**Comment by timlinux** [comment]
@Charlotte-Morgan ah ok that makes sense now .. will clean that up - sorry @ismailsunni it will cause a string change to fix it :-(
