### ISSUE TITLE
We should hide single / multi event choices in the wizard

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2217]
For now we should not ask the user until we have IF's that are dependent on one or the other. @charlotte-morgan to confirm this.

**Comment by Charlotte-Morgan** [comment]
see #1961

**Comment by adissadis** [comment]
+1 i agree with that. Its really confusing to us when we tried to use IF wizard

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan by removing the radio button, I will also set all IF to have multiple_events and single_event.

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - i'm not really sure what you mean - except i think the IF is now reading this from the key words so its not needed in the IFCW

**Comment by ismailsunni** [comment]
I have set all IF to have single and multiple event. So, we only need to remove the radio button now. Under the hood, the radio buttons do not have any effects.
