### ISSUE TITLE
Traceback when running flood on roads

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2220]
Exception when running flood on roads. 

Using test layers from add test layers button...

```
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/utilities/analysis.py", line 971, in run_analysis self.impact_layer = calculate_impact(self.impact_function)
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/engine/core.py", line 176, in calculate_impact result_layer = impact_function.run()
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/inundation/flood_raster_road/impact_function.py", line 405, in run self.exposure.layer.crs())
In file "/Users/timlinux/.qgis2/python/plugins/inasafe/safe/impact_functions/inundation/flood_raster_road/impact_function.py", line 112, in _raster_to_vector_cells index = QgsSpatialIndex(vl.getFeatures())
```

**Comment by timlinux** [comment]
Possibly because there were no intersecting roads - we should write a test to check for that.

**Comment by lucernae** [comment]
@timlinux I can't replicate this.

Hazard: Continuous Flood
Exposure: Roads
InaSAFE 3.2.0 dev-master

Windows 10
QGIS 2.10 Pisa

**Comment by timlinux** [comment]
Yes it still occurs. You need to set the analysis extent to somewhere whithin the bounding box of roads and flood, but that does not actually intersect with any roads. Here is the scenario I had:

```
[Continuous Flood]
exposure = ../../Users/timlinux/.qgis2/python/plugins/inasafe/safe/test/data/exposure/roads.shp
hazard = ../../Users/timlinux/.qgis2/python/plugins/inasafe/safe/test/data/hazard/continuous_flood_20_20.asc
function = FloodRasterRoadsFunction
extent = 106.831991, -6.170044, 106.834868, -6.167793
extent_crs = EPSG:4326
```

Note that we should systematically check each IF for this kind of issue. In essence we should be telling the user 'Everything is ok, nothing will be affected because there are no roads in the analysis area.' We can do this by raising a ZeroImpactException - see the work in progress I am doing in my inasafe-2288 branch and in #2288 

@lucernae please create unit tests that check for this using the scenario I provided above.

Thanks!
