### ISSUE TITLE
Can not run Flood Impact Function (Vector) with Population (Raster) [bug]

### ISSUE THREAD

**Issue by harrymahar** [AIFDR/inasafe#2228]
# Problem
Can not run Flood Impact Function (Vector) with Population (Raster)

# Detail
When I want to run to calculate impact function of flood in DKI Jakarta using Vector Data of Flood DKI Jakarta with population, InaSAFE did not succeeded to running that impact function. at InaSAFE dock there is a message  Problem : Type Error. This problem happened both when using  InaSAFE dock and InaSAFE Impact Function Centric Wizard.

# Screenshot
![2](https://cloud.githubusercontent.com/assets/2534179/9462770/28b95df6-4b42-11e5-895c-b127460b92ab.png)

![error_flood vector _population_impact centric](https://cloud.githubusercontent.com/assets/2534179/9462781/3a8b63bc-4b42-11e5-9b23-b8ac30838f0c.PNG)

# Platform
Windows 8.1 64 Bit
RAM 4 GB
QGIS 2.8.3 Wien
InaSAFE 3.2.0 dev-master

# Data used
Hazard : Jakarta_Flood_18113__WGS84.shp (Vector)
Exposure : Java_Population_WGS84.tiff (Raster)

**Comment by timlinux** [comment]
@harrymahar would you mind pasting in the traceback (will be at the bottom of the dock after the exception occurred) please (and for any other tickets you may have already made? Thanks!

**Comment by samnawi** [comment]
@harrymahar a problem when you running the Flood IF with population is not occur in my computer.
I use the same data with you.
My computer platform is : 
Linux Ubuntu 14.04 64-bit
RAM 7.7 GB
QGIS 2.8.3 
InaSAFE 3.2.0 dev-4c5c078.

This is the result
![selection_137](https://cloud.githubusercontent.com/assets/8871958/9487844/958161a0-4bff-11e5-8bfa-193fafc3801e.png)

cc : @timlinux

**Comment by lucernae** [comment]
@harrymahar @samnawi perhaps you can help me get the data? If I may, ping me in gitter channel. :)

**Comment by samnawi** [comment]
@lucernae I use the package data in this link http://data.inasafe.org/InaSAFE%203.1%20Training%20Data/DKI%20Jakarta.zip.

This data is for InaSAFE 3.1 Training, and I change the keyword to 3.2.

**Comment by lucernae** [comment]
I test this on Linux and it fails. Strange... will look into this why sometimes it succeed and fails.

**Comment by harrymahar** [comment]
hai @lucernae @samnawi  I just want to inform you guys, today I update InaSAFE from Git bash and try run again this impact function. But the result still same..

![typeerror1](https://cloud.githubusercontent.com/assets/2534179/9537908/bd3d79b2-4d68-11e5-8f03-c9957de9bae5.PNG)

**Comment by samnawi** [comment]
Hmmm.... It's strange. @lucernae I also try use the test layer and it run.
I also doing test in windows platform (Win 7 64-bit), use QGIS 2.8.3 and 2.10 and it run

This is the result
Using Ubuntu 14.04 64-bit and QGIS 2.8.3.
![selection_142](https://cloud.githubusercontent.com/assets/8871958/9537835/cefb849c-4d67-11e5-81da-c80b7b4539e8.png)

Using Win 7 64-bit and QGIS 2.8.3
![image](https://cloud.githubusercontent.com/assets/8871958/9537896/91498134-4d68-11e5-8b62-311f9673b90a.png)

Using Win 7 64-bit and QGIS 2.10
![image](https://cloud.githubusercontent.com/assets/8871958/9537880/5d282630-4d68-11e5-8bd3-e52d19ae4e42.png)

**Comment by cchristelis** [comment]
Hi @samnawi , @harrymahar and @lucernae, 

could you guys please confirm that #2275 fixes this problem for you.

**Comment by lucernae** [comment]
Still not fixed in my Linux env @cchristelis .

Environment:

Linux Ubuntu 14
QGIS Pisa 2.10

I'm trying to use standard test layers:

Hazard: Flood Polygon (Vector)
Exposure: Population (Raster)

Perhaps this will help you, I got the stack trace when it is failed.

> In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/utilities/analysis.py", line 970, in run_analysis self.run_aggregator()
> In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/utilities/analysis.py", line 895, in run_aggregator self.run_post_processor()
> In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/utilities/analysis.py", line 909, in run_post_processor self.postprocessor_manager.run()
> In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/impact_statistics/postprocessor_manager.py", line 481, in run value.process()
> In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/postprocessors/gender_postprocessor.py", line 61, in process self._calculate_total()
> In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/postprocessors/gender_postprocessor.py", line 83, in _calculate_total result = int(round(result))

The stack trace is different from @harrymahar

**Comment by cchristelis** [comment]
Hi @lucernae, I think we have 2 problems here. The PR fixes @harrymahar's problem. I'm not able to re-produce your issue, but let me try and fix it based on the stack trace.

**Comment by samnawi** [comment]
Hi @cchristelis there is no problem to run this IF in my computer. The IF can run and the result is fine

**Comment by cchristelis** [comment]
@lucernae, what is the error type that is thrown?

**Comment by cchristelis** [comment]
Thanks for checking @samnawi!

**Comment by harrymahar** [comment]
Good Morning @timlinux @lucernae @cchristelis @samnawi I have some update and problem for this bug today.

After I update my InaSAFE through GitHub today, I try again to run Flood Impact function using DKI Jakarta Flood (Vector) and Java Population (Raster). It seems run well and the result shows number of people affected and need evacuation. However, when I scroll down the dock, Detailed minimum needs report (for people needing evacuation) result has no data even though Evacuated population minimum needs report has list of needs that need to be provided and its numbers.

![vector_population_flood](https://cloud.githubusercontent.com/assets/2534179/9571526/1b7f566e-4fc9-11e5-880b-455c51c03f27.PNG)

![vector_population_flood_no data](https://cloud.githubusercontent.com/assets/2534179/9571532/3d44803a-4fc9-11e5-964c-b35f357d22d7.PNG)

![vector_population_flood_no data2](https://cloud.githubusercontent.com/assets/2534179/9571535/46e56078-4fc9-11e5-914f-03760342b682.PNG)

thankyou..

**Comment by Charlotte-Morgan** [comment]
hi @harrymahar - if this is not resolved, please add your comment here and reopen (i have reopened)
please also see tickets #2318 #2320 and #2321

**Comment by Charlotte-Morgan** [comment]
@samnawi - please talk to @harrymahar to confirm that this was resolved for you

**Comment by Charlotte-Morgan** [comment]
@harrymahar & @cchristelis - i can confirm that i have the same issue as Harry using Flood polygon on Population.
My system is QGIS 2.8.3 an windows .
I have also checked all other tests we have run on reporting and this situation is unique to this IF / data.

**Comment by cchristelis** [comment]
The no data / zero column removal has been added in https://github.com/AIFDR/inasafe/pull/2345. The non- osm data issues will be looked at a later stage and can be followed in: https://github.com/AIFDR/inasafe/issues/2318 and https://github.com/AIFDR/inasafe/issues/2289
