### ISSUE TITLE
Can not run Volcano Impact Function (Vector) with Building (Vector) [bug]

### ISSUE THREAD

**Issue by dewisulistio** [AIFDR/inasafe#2230]
# Problem
Can not success to running Volcano Merapi with building

# Detail
When I want to run Vulcano Merapi point and building using InaSAFE Impact Function Centric, InaSAFE did not succeeded to running that impact function. at InaSAFE dock there is a message Problem : AttributeError. When I run with InaSAFE dock, it's successful.

# Screenshot
![volcano - merapi error impact function centric](https://cloud.githubusercontent.com/assets/2524177/9463207/5c58d080-4b45-11e5-8128-dd9c5d7ad3e4.png)

# Platform
Windows 7 64 Bit
RAM 4 GB
QGIS 2.8.3 Wien
InaSAFE 3.2.0 dev-master

# Data used
Hazard : Merapi Volcano (Vector)
Exposure : Buildings Yogyakarta (Vector)

**Comment by timlinux** [comment]
Thanks @dewisulistio  - when you make a ticket, can you also cut and paste the traceback printed in the dock into the ticket inside of three backticks? Could you update this one with the traceback too? Thanks! Pasting screenies like you have done is awesome too!

**Comment by dewisulistio** [comment]
Hi @timlinux 
This is the screenshot from InaSAFE dock while running Volcano hazard and building exposure. 
![inasafe dock - volcano merapi and building](https://cloud.githubusercontent.com/assets/2524177/9484710/f46894c0-4bd9-11e5-9b74-bf50a72b1105.png)

**Comment by ismailsunni** [comment]
hi @dewisulistio 
Can you paste here the traceback also?

**Comment by dewisulistio** [comment]
Hi @ismailsunni 

Problem:
The following problem(s) were encountered whilst running the analysis.
AttributeError

Suggestion:
You can try the following to resolve the issue:
Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.

Details:
These additional details were reported when the problem occurred.
An exception occurred when running the impact analysis.
'NoneType' object has no attribute 'replace'

Diagnostics:
In file "C:/Users/Dewi Pc/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 969, in run_analysis self.impact_layer = calculate_impact(self.impact_function)
In file "C:/Users/Dewi Pc/.qgis2/python/plugins\inasafe\safe\engine\core.py", line 176, in calculate_impact result_layer = impact_function.run()
In file "C:/Users/Dewi Pc/.qgis2/python/plugins\inasafe\safe\impact_functions\volcanic\volcano_point_building\impact_function.py", line 180, in run impact_summary = impact_table = self.generate_html_report()
In file "C:/Users/Dewi Pc/.qgis2/python/plugins\inasafe\safe\impact_reports\report_mixin_base.py", line 30, in generate_html_report return self.parse_to_html(self.generate_report())
In file "C:/Users/Dewi Pc/.qgis2/python/plugins\inasafe\safe\impact_reports\building_exposure_report_mixin.py", line 87, in generate_report report += self.buildings_breakdown()
In file "C:/Users/Dewi Pc/.qgis2/python/plugins\inasafe\safe\impact_reports\building_exposure_report_mixin.py", line 209, in buildings_breakdown building_type_name = building_type.replace('_', ' ')

**Comment by ismailsunni** [comment]
Hi @dewisulistio 
I tried similar scenario (merapi volcano and building from OSM), all is fine.

May be we have problem specific to the data. Where can I get your test data?

**Comment by ismailsunni** [comment]
Hi @dewisulistio 
I tried the data from data.inasafe.org. It's fine here. Can you update your InaSAFE first, and re-run the analysis?

![qgis 2 8 3-wien - yogyakarta_050](https://cloud.githubusercontent.com/assets/1421861/9499692/159109a4-4c4b-11e5-8147-e91e1aed3eec.png)

**Comment by dewisulistio** [comment]
Hi @ismailsunni 

I tried run the scenario with update InaSAFE and it's successful 

Thanks for help
