### ISSUE TITLE
[Bug] Can not run InaSAFE with flood hazard vector + building 

### ISSUE THREAD

**Issue by raniedwianugrah** [AIFDR/inasafe#2236]
# Problem 

Can not run InaSAFE with the data of Jakarta flood hazard vector and building. 

# Detail

I analyze the data of Jakarta flood hazard vector with building. When I click run in InaSAFE dock appear Python Error and it happens when I run in InaSAFE Impact Function Centric Wizard appear Python Error too.
Source data from inaSAFE training data in data.inasafe.org.

# Screenshot

InaSAFE Dock

![bug_1](https://cloud.githubusercontent.com/assets/2528195/9485099/030897a0-4bdf-11e5-9531-a8a07f9d381c.PNG)

InaSAFE Impact Function Wizard

![bug_4](https://cloud.githubusercontent.com/assets/2528195/9485591/faaabf14-4be5-11e5-8578-7f1a71dd0144.PNG)

# Platform

QGIS 2.8.3 Wien - InaSAFE 3.2 - Windows 7 - 32 Bit - RAM 2 GB

# Data used

-	Jakarta_buildings_WGS84.shp
-	Jakarta_flood_18113_WGS84.shp

**Comment by Charlotte-Morgan** [comment]
hi @raniedwianugrah - is this the same issue as  #2167? 
I think it might be fixed now by @cchristelis

**Comment by raniedwianugrah** [comment]
Hi @Charlotte-Morgan - Fix, InaSAFE can running these data..

**Comment by Charlotte-Morgan** [comment]
great - you can close the ticket if you are happy.
