### ISSUE TITLE
[Bug] Can not run InaSAFE with vulcano point + population

### ISSUE THREAD

**Issue by raniedwianugrah** [AIFDR/inasafe#2238]
# Problem

Can not run InaSAFE with the data of Merapi vulcano point and population (raster)

# Detail

I analyze the data of Merapi vulcano point and population (raster). When I click run in InaSAFE dock appear crash dumped. Source the data from InaSAFE training data in data.inasafe.org.

# Screenshot

![bug_3](https://cloud.githubusercontent.com/assets/2528195/9485290/80f7b9f0-4be1-11e5-8be8-c0a36ba87fdc.PNG)

# Platform

QGIS 2.8.3 Wien – InaSAFE 3.2 – Windows 7 – 32 Bit - RAM 2 GB

# Data used
-	Merapi_Vulcano_WWGS84.shp
-	Java_population_WGS84.tif

**Comment by fredychandra** [comment]
It is run on my test
InaSAFE 3.2.dev-master; Qgis 2.8.3 - Windows 8 - 64bit 

Data Used : 
1. Mt. Ebulobo_SHP
2. Population SP2010_BPS.tif

![image](https://cloud.githubusercontent.com/assets/6345285/9488467/8d4dfdf4-4c04-11e5-97af-007f65d4acda.png)

**Comment by ismailsunni** [comment]
Hi @raniedwianugrah 
I tried the same data, and it's fine. Can you update your InaSAFE, and re-run the analysis?
![qgis 2 8 3-wien - yogyakarta_052](https://cloud.githubusercontent.com/assets/1421861/9499785/aa138d68-4c4b-11e5-893c-0c5c066718ac.png)

**Comment by timlinux** [comment]
@raniedwianugrah It seems like your InaSAFE is not too up to date - can you test with the most recent version please? Thanks!

**Comment by raniedwianugrah** [comment]
hi @timlinux @ismailsunni The issue is fix, I can run the analysis and I've updated my InaSAFE..

**Comment by ismailsunni** [comment]
@raniedwianugrah can we close this then?

**Comment by raniedwianugrah** [comment]
@ismailsunni oke, you can close this issue
