### ISSUE TITLE
[Bug] Unbound Local Error InaSAFE analysis for Flood Raster Hazard

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#2240]
# Problem
Unbound local error when analysis Flood Raster Hazard with building polygon from OSMDownloader

# Detail
Me and my team get this error when tried to analysis Flood raster hazard with building polygon **only** from OSMDownloader. The problem come when we run InaSAFE analysis with Building polygon from OSMDownloader in bigger area. When we tried to run analysis again in smaller area, it works like a charm. This problem didn't occur if we use building polygon from InaSAFE Training Data.

# Screenshot
![image](https://cloud.githubusercontent.com/assets/2520159/9485865/bad1cdfc-4be9-11e5-9a77-52d857912b77.png)

If i use smaller area from OSMDownloader, it can run the analysis
![image](https://cloud.githubusercontent.com/assets/2520159/9485888/184e446a-4bea-11e5-9641-bfe37d5c6999.png)

# Platform
QGIS 2.8.3 InaSAFE 3.2 Windows 7 64bit
QGIS 2.8.3 InaSAFE 3.2 Windows 7 64bit
QGIS 2.8.3 InaSAFE 3.2 Windows 8.1 64bit

# Error
Please wait - processing may take a while depending on your hardware configuration and the analysis extents and data.
This analysis will calculate the impact of Jakarta_Flood_HKV_WGS84 on buildings .
The following postprocessors will be used:
Building type: Calculates building types related statistics.
Checking available memory
Computed cellsize was None. Memory check currently only works for raster input layers.
Preparing hazard data
We are resampling and clipping the hazard layer to match the intersection of the exposure layer and the current view extents.
Preparing exposure data
We are resampling and clipping the exposure layer to match the intersection of the hazard layer and the current view extents.
Preparing aggregation layer
We are clipping the aggregation layer to match the intersection of the hazard and exposure layer extents.
Calculating impact
This may take a little while - we are computing the areas that will be impacted by the hazard and writing the result to a new layer.
Problem
The following problem(s) were encountered whilst running the analysis.
**UnboundLocalError**
Suggestion
You can try the following to resolve the issue:
Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details
These additional details were reported when the problem occurred.
An exception occurred when running the impact analysis.
local variable 'usage' referenced before assignment
Diagnostics
In file "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\utilities\analysis.py", line 969, in run_analysis self.impact_layer = calculate_impact(self.impact_function)
In file "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\engine\core.py", line 176, in calculate_impact result_layer = impact_function.run()
In file "C:/Users/Sony/.qgis2/python/plugins\inasafe\safe\impact_functions\inundation\flood_raster_osm_building_impact\impact_function.py", line 147, in run if usage is None or usage == 0:

**Comment by cchristelis** [comment]
This problem was introduced here: 9fc87d8cfe8d83cb3d965f018bc9a2dfaee6a233.

**Comment by cchristelis** [comment]
Hi @adissadis,

Could you please confirm, that the bug is fixed by PR #2252?
