### ISSUE TITLE
InaSAFE Logo is gone

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2241]
# Problem
Dear All,

I try to print the report, and find that the Inasafe logo in the map is just appeared with red cross icon
![selection_136](https://cloud.githubusercontent.com/assets/8871958/9486803/153f1e3c-4bf6-11e5-982d-46982b7bb1df.png)
 
It's occur in both of old template and new template.

# Proposed Solution
Make the logo back in here :)

# CC
@ismailsunni @timlinux

**Comment by timlinux** [comment]
I fixed this in #2254 - thanks @samnawi !
