### ISSUE TITLE
UI: distorted logos & icons

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2242]
The new interface looks great. +1 :)

# problem
- [x] logo is distorted in the top bar of the impact function centric wizard
- [x] supporters logo is distorted in the About window

# proposed solution
make it happy

**Comment by timlinux** [comment]
>  logo is distorted in the top bar of the impact function centric wizard

This should be fixed in #2254

**Comment by timlinux** [comment]
> supporters logo is distorted in the About window

And this should be fixed in #2255 ...
