### ISSUE TITLE
UI - About Window - updated text

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2244]
The ABOUT window needs some updates as follows:
 - [x] About tab - please use the following text - approved by DFAT - removes reference to AIFDR

InaSAFE is free software that provides a simple but rigorous way to combine data from communities, local governments and scientists to help assess the possible impact of future disaster events on communities, assets and infrastructure. It uses innovative science and crowd sourcing techniques (OpenStreetMap, OSM) to create realistic disaster scenarios for better planning, preparedness and response activities. It is in demand by disaster managers across Indonesia and around the world.
InaSAFE was developed jointly by the Indonesia's National Disaster Management Agency (BNPB), the Australian Government and the World Bank - Global Facility for Disaster Reduction and Recovery (World Bank-GFDRR).

- [x] Disclaimer tab - please use the following text - approved by DFAT - removes reference to AIFDR

InaSAFE has been jointly developed by the Indonesian Government-BNPB, the Australian Government and the World Bank-GFDRR. These agencies and the individual software developers of InaSAFE take no responsibility for the correctness of outputs from InaSAFE or decisions derived as a consequence.

- [x] Supporters Tab - please use the following links- approved by DFAT - removes reference to AIFDR

Indonesia’s National Disaster Management Agency (BNPB)
http://www.bnpb.go.id/
Australian Government – Disaster Risk Management in Indonesia
http://dfat.gov.au/geo/indonesia/development-assistance/Pages/disaster-risk-management-in-indonesia.aspx
World Bank - Global Facility for Disaster Reductions and Recovery
https://www.gfdrr.org/
Humanitarian OpenStreetMap Team
http://hot.openstreetmap.org/
Kartoza Open Source Geospatial Solutions
http://kartoza.com/
Environmental Science for Social Change (Philippines)
http://essc.org.ph/

- [x] image credits
i think line 3 should not be there?
should we acknowledge UNOCHA for the icons as per requirements?

# cc
@timlinux 
@MariaSolovyeva  - could you please also update the disclaimer text on the website using the new wording above?
@iyan31 @adissadis - FYI - grateful if you can use the DFAT approved wording above in any HOT sites / documents . Happy to clarify if there are any questions.

**Comment by timlinux** [comment]
> image credits i think line 3 should not be there? should we acknowledge UNOCHA for the icons as per requirements?

I updated the wording to make it clearer that 'Add' and 'Remove' are actually the names of icons :-P

I added in OCHA too thanks.

**Comment by timlinux** [comment]
For the disclamer text, I updated it in defaults.py, so it should be updated wherever that is referenced.

**Comment by Charlotte-Morgan** [comment]
i already did that - see PR #2243
