### ISSUE TITLE
UI: new look is missing bold

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2245]
# problem
The new look is great but we have lost the bold in the layer key words and report headings
eg 
 - [ ] Layer keywords are not as easy to read without bold
![image](https://cloud.githubusercontent.com/assets/5743135/9488718/fd9a2b04-4c05-11e5-8258-f2242d268978.png)
 # solution 
use bold for the key word categories (not the user entered values) ie Layer_purpose is in bold but hazard is not

- [ ] report headings in the dock are missing bold
![image](https://cloud.githubusercontent.com/assets/5743135/9488786/74bf9fca-4c06-11e5-9d2a-5cdd0e2301ee.png)

but show in bold in web interface
![image](https://cloud.githubusercontent.com/assets/5743135/9488799/89b6b08a-4c06-11e5-99a9-24bda2cf91da.png)

# proposed solution
use bold in the dock too

**Comment by timlinux** [comment]
Strangely it works fine for me on Linux. I tested on OSX and get the no bold version like you do...

**Comment by timlinux** [comment]
@Charlotte-Morgan can you test if #2248 on windows - works for me now on OSX...

**Comment by Charlotte-Morgan** [comment]
working on windows now.
FYI - metadata comments in the hazard details and exposure details - sourced from key words are still in a different font
