### ISSUE TITLE
QGIS Closes Unexpectedly

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#2259]
Problem
----------
I find this cases several times, and seems randomly. For example, when loading standard test data. But, when I was lucky enough, QGIS is running well.

Just a moment ago, I find again. And this time, I can replicate it:
0. Open QGIS with InaSAFE enabled. (If InaSAFE is disabled, everything is OK)
1. Load building-points.shp (safe/test/data/exposure/building-points.shp)
2. Load tsunami_wgs84.tif (safe/test/data/hazard/tsunami_wgs_84.tif)
3. Boom. QGIS close.

Reversing the order of layers also create the same problem.

I tried to run QGIS from terminal, it said : 

```
Warning: void DBusMenuExporterPrivate::fillLayoutItem(DBusMenuLayoutItem*, QMenu*, int, int, const QStringList&): No id for action 
Warning: void DBusMenuExporterPrivate::fillLayoutItem(DBusMenuLayoutItem*, QMenu*, int, int, const QStringList&): No id for action 
Warning: void DBusMenuExporterPrivate::fillLayoutItem(DBusMenuLayoutItem*, QMenu*, int, int, const QStringList&): No id for action 
DEBUG:InaSAFE:Showing Generic Keywords
Warning: Loading a style file that was saved with an older version of qgis (saved in 2.6.1-Brighton, loaded in 2.8.3-Wien). Problems may occur.
DEBUG:InaSAFE:Showing Generic Keywords
Warning: Loading a style file that was saved with an older version of qgis (saved in 2.8.1-Wien, loaded in 2.8.3-Wien). Problems may occur.
DEBUG:InaSAFE:Showing Generic Keywords
DEBUG:InaSAFE:Showing Generic Keywords
DEBUG:InaSAFE:Showing Generic Keywords
Segmentation fault (core dumped)

```

Not sure why....

Does anyone experience this problem also?

**Comment by timlinux** [comment]
I'll try to see if I can replicate it in the morning @ismailsunni

**Comment by timlinux** [comment]
I tested here and it worked fine without crashing - tested on Fedora 22 with QGIS 2.8.3 built from source. I will test on OSX too...

**Comment by timlinux** [comment]
Tested on OSX and I cant replicate. @ismailsunni I think we should close this out for now. If you have time later you can debug it on your own system using QtCreator....
