### ISSUE TITLE
A Little Bug in the New Template

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2265]
Thank for all that work very hard to fix the bug in the new version of InaSAFE.
:+1: for this.

# Problem
A couple days ago, there is an update about the map template, both of the composition also the content.
Apparently, there is a little bug that I found in the new template :
1. @timlinux I think the first bug is come from my mistake. I'm not careful to notice all of element in the map. So, there is an article that clipped. But It's just occur in the portrait template.
2. Yesterday, @Charlotte-Morgan has been updated the article in the disclaimer. The implication of this, in the map, the last word in the disclaimer is overlap with the organization logo. It's also just occur in the portrait template

This is the overview
![selection_139](https://cloud.githubusercontent.com/assets/8871958/9514091/1bcd0306-4cc1-11e5-9ac2-841404e1c685.png)

I've tried to fix the template, and uploaded this *.qpt file in here
https://www.dropbox.com/s/dw1hegp8bzo9vwr/portrait_revised.qpt?dl=0

And this is the result
![selection_140](https://cloud.githubusercontent.com/assets/8871958/9514227/7875e4be-4cc2-11e5-88ee-7056c306aa79.png)

# Proposed Solution
Make it happy.
Is this solution will use my revised template, or there are the other method to fix it?

Thank you.

**Comment by Charlotte-Morgan** [comment]
I will look at problem 2 - then pass to others
@timlinux

**Comment by Charlotte-Morgan** [comment]
@samnawi - i think you might need to tweak the template. changing the line breaks makes no difference at this end

**Comment by samnawi** [comment]
@Charlotte-Morgan I've been make some change in the new portrait template that I post in the above.

**Comment by timlinux** [comment]
Ok just reassign to me if you want me to do any follow up help. I saw another bug in the table report that I will write a ticket for now (probably unrelated to this).

**Comment by Charlotte-Morgan** [comment]
thanks @timlinux - over to you. I dont think editing the disclaimer helped. so i stashed the edit.

**Comment by timlinux** [comment]
OK thanks...I have the baton :-)

**Comment by timlinux** [comment]
A little bug = a lot of work :-P


What do you think of this:

<img width="573" alt="screen shot 2015-09-18 at 14 03 57" src="https://cloud.githubusercontent.com/assets/178003/9953810/4efe6ad6-5e0e-11e5-863c-062f57e9cb86.png">

Some notes:

* Logo is properly overlaid onto orange bar
* fonts are all sans serif for consistency with our style guide
* Supporters title is more generic for when you swap out the logo with your own org's
* All elements are soft coded with tokens (see https://github.com/AIFDR/inasafe/wiki/Map-Composer-Templating for updated list of available tokens)
* All elements are translatable
* Improved spacing and layout for zen and symmetry

**Comment by timlinux** [comment]
More tweaks based on comments from @Charlotte-Morgan on gitter:

<img width="572" alt="screen shot 2015-09-18 at 14 17 23" src="https://cloud.githubusercontent.com/assets/178003/9954081/3d7f48c8-5e10-11e5-899f-74ced7813fdc.png">

* Logo made bigger
* Illustrates what it looks like with default disclaimer and logo
* Below is side by side of logo tweak

<img width="565" alt="screen shot 2015-09-18 at 14 18 19" src="https://cloud.githubusercontent.com/assets/178003/9954085/4429db48-5e10-11e5-9f2d-20c475f3bd1b.png">
