### ISSUE TITLE
BUG: Key words wizard - glitch

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2266]
# problem
The key words creation wizard has a glitch at step two fro both Exposure and Hazard. 
The text that should guide the user says 
MISSING CONSTANT: hazard_question
![image](https://cloud.githubusercontent.com/assets/5743135/9518697/327ad958-4ce3-11e5-90e9-226323c70711.png)

# proposed solution
send out a search party for the missing constant

**Comment by ismailsunni** [comment]
@Charlotte-Morgan can you check it now? It's been fixed in develop now.

**Comment by Charlotte-Morgan** [comment]
@ismailsunni - its fixed.. Thanks - search party can be stood down.
