### ISSUE TITLE
We need better presentation for the keywords in dock

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2268]
Currently our keywords look like this:

![screenshot from 2015-08-27 13-33-41](https://cloud.githubusercontent.com/assets/178003/9519627/78b0c63a-4cc0-11e5-9832-3d77e0b7e240.png)

There are a number of problems here:

* The text is not nicely laid out
* The titles have underscores and odd casing
* We could do a better job of ordering the information into a logical sequence

I am proposing to create a table rather and clean up the keyword names. @adissadis I don't want to mess with your work, so I would like to know if you would rather that I wait until 3.3 to make this change?

**Comment by adissadis** [comment]
I think its not a big issue for us. You can change it into table @timlinux

**Comment by timlinux** [comment]
@adissadis ok great, thanks

**Comment by timlinux** [comment]
@Charlotte-Morgan and @adissadis I am proposing something like this:

<img width="345" alt="screen shot 2015-08-27 at 22 57 36" src="https://cloud.githubusercontent.com/assets/178003/9532972/30eccae8-4d0f-11e5-8601-8b73767c8e4b.png">

It only addresses the layout, will do more hacking to remove underscores and improve the ordering of rows...

**Comment by adissadis** [comment]
@timlinux yes it's great layout and i like that.

**Comment by Charlotte-Morgan** [comment]
+1 for this +2 for no underscores and sensible row order

**Comment by timlinux** [comment]
Here is how it looks now (with PR #2274 ) - open to suggestions on layer order:

<img width="342" alt="screen shot 2015-08-28 at 09 24 46" src="https://cloud.githubusercontent.com/assets/178003/9541267/d50adb2c-4d66-11e5-9218-4966103db412.png">


Logic is basically these keywords get listed first if present (and in this order listed):

```
        preferred_order = [
            'title',
            'layer_purpose',
            'exposure',
            'hazard',
            'layer_geometry',
            'layer_mode'] # everything else in arbitrary order
```

After that the keywords are written out in whatever order they are received in the dict from keyword_io in...
