### ISSUE TITLE
Python Error Flood Impact using Hazard Vector with Building (OSM Downloader) + Aggregation RW Boundary (OSM Downloader) [Bug]

### ISSUE THREAD

**Issue by harrymahar** [AIFDR/inasafe#2273]
# Problem

Python Error Flood Impact using Hazard Vector with Building (OSM Downloader) + Aggregation RW Boundary (OSM Downloader)

# Details
When I try to run Flood Impact in DKI Jakarta using Flood Jakarta 2013 (Vector) with Building and RW boundary which downloaded from OSM downloader, InaSAFE shows python Error Box at the end of run process. Result comes up with number of inundated buildings, not affected and all buildings. However, aggregation results did not created in InaSAFE dock.

I thought this problem caused by size of analysis area so I try to run again with smaller area and It works perfectly. After that, I change aggregation layer using Jakarta_District_Boundary from BPBD DKI and the run analysis works well with aggregation results as well.

Conclusion : Flood Impact using vector hazard and building cannot run using RW boundary from OSM Downloader in large extent but works if we only run in small area. However, we still can run large extent  well if we using aggregation layer from other sources.

# ScreenShoot 
![python error_flood_vector_buildingosm_aggregationosm](https://cloud.githubusercontent.com/assets/2534179/9540316/a57772a0-4d87-11e5-8efd-122adbc95cc6.PNG)

![aggregation osm_error_building](https://cloud.githubusercontent.com/assets/2534179/9540325/c0642aea-4d87-11e5-8aad-7d3158474e1c.PNG)

![python error_flood_vector_buildingosm_aggregationosm_3](https://cloud.githubusercontent.com/assets/2534179/9540333/d78092c2-4d87-11e5-840b-6a40a20c2c77.PNG)

![python error_flood_vector_buildingosm_aggregationosm_4](https://cloud.githubusercontent.com/assets/2534179/9540340/e91864d8-4d87-11e5-93fc-1c3d933500f0.PNG)

# Platform 
Windows 8.1 64 Bit
RAM 4 GB
QGIS 2.8.3 Wien
InaSAFE 3.2.0 dev-master

# Data used
Hazard : Jakarta_Flood_18113__WGS84.shp (Vector)
Exposure : Building_Jakarta (Vector) from OSM Downloader
Aggregation : RW Boundary (Vector) from OSM Downloader

**Comment by Charlotte-Morgan** [comment]
hi @harrymahar - is this still an issue?

**Comment by samnawi** [comment]
@Charlotte-Morgan I also find this issue in my computer.
Similar with @harrymahar get, when I run All of DKI jakarta Province, there is a python error message.
But, when I try to make it smaller extent analysis, the IF run very well.

This the error message
![selection_202](https://cloud.githubusercontent.com/assets/8871958/9924827/83c82e00-5d2d-11e5-8aa7-3d4470fa3650.png)

# PC Platform
Linux Ubuntu 14.04
QGIS 2.8.3
InaSAFE 3.2.0.dev-c4129d3

**Comment by ismailsunni** [comment]
Note for myself (or others)
The problem is caused by the ErrorMessage object want to add `NULL` (not None) in here https://github.com/AIFDR/inasafe/blob/develop/safe/messaging/error_message.py#L191. This `NULL` value is coming from here (https://github.com/AIFDR/inasafe/blob/develop/safe/impact_statistics/postprocessor_manager.py#L567). So, the `NULL` value is the result from `_generate_tables` method in https://github.com/AIFDR/inasafe/blob/develop/safe/impact_statistics/postprocessor_manager.py#L100

**Comment by ismailsunni** [comment]
Further note:
I debug that `_generate_tables` method. Abracadabra. The bug is gone. It doesn't return the `NULL` value.

**Comment by ismailsunni** [comment]
Finally, found the problem. There are some `NULL` values in the `NAME` attribute in the aggregation layer:
![selection_064](https://cloud.githubusercontent.com/assets/1421861/9950643/d5a7dc34-5de6-11e5-8963-7a4235925084.png)

**Comment by Charlotte-Morgan** [comment]
@ismailsunni - is this fixed?
