### ISSUE TITLE
BUG: Big difference result in the report (Volcano IF with Structure)

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2276]
# Problem
When I run the Volcano IF whit structure, I get some bug in here.

This is the result
**Volcano Point with Building Polygon**
![selection_154](https://cloud.githubusercontent.com/assets/8871958/9542982/68d7c6e8-4d9f-11e5-8be1-245e5919edfb.png)

**Volcano Point With Building Point**
![selection_152](https://cloud.githubusercontent.com/assets/8871958/9542997/8096a934-4d9f-11e5-92aa-2e03e821eab1.png)

I think this bug is occur because the not affected building also calculated.

# Proposed Solution
Make it happy

# CC
@Charlotte-Morgan @timlinux 

Thank You

**Comment by Charlotte-Morgan** [comment]
proposed solution - only the affected should be in the total
