### ISSUE TITLE
Typo: Impact Function Wizard

### ISSUE THREAD

**Issue by roscoeKartoza** [AIFDR/inasafe#2279]
# Problem
"I would like to use a hazard layer already loaded in QGIS"
should be:
"I would like to use an aggregation layer already loaded in QGIS"

![image](https://cloud.githubusercontent.com/assets/10434570/9545211/a3fe6cf8-4d87-11e5-96b9-bd3cc0d560a1.png)

**Comment by ismailsunni** [comment]
Hi @roscoeKartoza 
Those two sentence are the same.

**Comment by roscoeKartoza** [comment]
Hi @ismailsunni, my mistake, the second was supposed to be:
"I would like to use an aggregation layer already loaded in QGIS"
