### ISSUE TITLE
Impact Function Wizard 

### ISSUE THREAD

**Issue by roscoeKartoza** [AIFDR/inasafe#2282]
![1](https://cloud.githubusercontent.com/assets/10434570/9547031/a112fa12-4d97-11e5-9c0a-b6d98b717e94.png)
When trying to select layers from disk, initially the 'Next' button is disabled but if I click 'Back' and make the same selection the 'Next' button becomes enabled. The data that was being used was from the testing data that had been added locally.
![2](https://cloud.githubusercontent.com/assets/10434570/9547032/a117e202-4d97-11e5-8498-6c94426c0607.png)
If 'Next' is clicked, I get an error that is listed below.

# Traceback
```
Traceback (most recent call last):
  File "C:/Users/Roscoe/.qgis2/python/plugins\inasafe\safe\gui\tools\wizard_dialog.py", line 3607, in on_pbnNext_released
    self.layer.name()):
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by borysiasty** [comment]
@roscoeKartoza, could you please provide the sample layer (both tif and xml file) that causes the error? It seems the wizard can't load it for some reason.

**Comment by roscoeKartoza** [comment]
@borysiasty, the classified_flood.tif layer is exactly the same as the  test data layer calledClassified Flood, I just saved it onto my machine directly from there. But [**here**](https://www.dropbox.com/sh/obr9tswigiho1cg/AACs7p9pNjCM5iz6po97MlWMa?dl=0) it is just in case.

**Comment by borysiasty** [comment]
Seems you selected a function that only accepts continuous raster, so the wizard is right it's not suitable.  For example 'Raster flood on roads' only works on continuous data, although it's name doesn't says it. Perhaps the top message "You selected **Raster Flood** ads hazard input to **Raster flood on roads** function" should be extended with "This function only accepts **continuous** data".

@Charlotte-Morgan @timlinux @ismailsunni - do you think I should add this sentence?

There was also a bug: the Next button shouldn't be enabled after coming back to this step. It's fixed now.

**Comment by ismailsunni** [comment]
@borysiasty yes, +1 from me. Better information for the user.

**Comment by borysiasty** [comment]
@roscoeKartoza @ismailsunni @timlinux @Charlotte-Morgan

Guys, what about this:

![bad_layer](https://cloud.githubusercontent.com/assets/1000043/9667084/16bd425e-527a-11e5-9db8-af1ce9114696.jpg)

**Comment by Charlotte-Morgan** [comment]
Hi @borysiasty - looks good in the screenie. Do you have a pull request?
Agree on fix now, polish later approach

**Comment by roscoeKartoza** [comment]
Hi @borysiasty. That makes more sense, thanks.
