### ISSUE TITLE
Earthquake Vector Building Failed if the extent is too smal

### ISSUE THREAD

**Issue by lucernae** [AIFDR/inasafe#2300]
# Scenario:

> [Earthquake]
> exposure = .qgis2/python/plugins/inasafe-dev/safe/test/data/exposure/buildings.shp
> hazard = .qgis2/python/plugins/inasafe-dev/safe/test/data/hazard/earthquake.tif
> function = EarthquakeBuildingFunction
> extent = 106.811151, -6.185024, 106.811781, -6.183888
> extent_crs = EPSG:4326

# Details:

> - An exception occurred when running the impact analysis.
> - StatisticsClasses [0, 1, 2, 3] does not include the None class which was found in the data. This is a problem in the impact function statistics_classes definition Aggregation error occurred

# Stack Trace:

> - In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/utilities/analysis.py", line 970, in run_analysis self.run_aggregator()
> - In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/utilities/analysis.py", line 882, in run_aggregator self.aggregator.aggregate(self.impact_layer)
> - In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/impact_statistics/aggregator.py", line 564, in aggregate qgis_impact_layer, safe_impact_layer)
> - In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/impact_statistics/aggregator.py", line 668, in _aggregrate_vector_impact self._aggregate_polygon_impact(safe_impact_layer)
> - In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/impact_statistics/aggregator.py", line 802, in _aggregate_polygon_impact self._aggregate_point_impact(safe_impact_layer, aggregation_points)
> - In file "/home/lucernae/.qgis2/python/plugins/inasafe-dev/safe/impact_statistics/aggregator.py", line 887, in _aggregate_point_impact raise KeyError(error)

# Possible cause:
Aggregated results contains NaN values, so it can't be classified according to StatisticsClasses

**Comment by lucernae** [comment]
![image](https://cloud.githubusercontent.com/assets/831865/9594850/fae12cda-508a-11e5-900f-c7289be23143.png)

Add some details to the issue. Try the issue again with different extent.
After discussing it with @ismailsunni the extent seems strange
Instead of only calculating the building inside the blue box, it calculates everything?
The orange building is succesfully calculated and classified, meanwhile the yellow one are the buildings that causes the errors, because its mmi is NaN. Somehow the interpolation assign NaN values.

@timlinux what is the expected output of this scenario?

**Comment by timlinux** [comment]
The extent will grow to include a minimum number of pixels needed for interpolation, so that behaviour is correct. The green box shows what the realised calculation area will be....

**Comment by timlinux** [comment]
I think in 3.3 we should systematically remove the use of interpolation in favour of 'greatest touching pixel' whereby the greatest value of any pixel that touches a building or road segment is considered to be the impact on the building. 

CC @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
+1 for not using interpolation.
i am not familiar with the 'greatest touching pixel' terminology. In Arc GIS we would call this maximum - ie the maximum value of any intersected pixel is assigned. This aligns well when the idea is to find a worst case scenario - ie what is the deepest water the building is in
