### ISSUE TITLE
Template Options: Custom Logo

### ISSUE THREAD

**Issue by roscoeKartoza** [AIFDR/inasafe#2301]
# Problem
When the custom logo option is selected, the custom logo replaces the default logo at the bottom on the Inasafe panel but it does not replace the logos on the templates that are generated.

![logo2](https://cloud.githubusercontent.com/assets/10434570/9580578/9e4059aa-4ffa-11e5-9465-87bcc2eb6ec1.png)

The logo is replaced in the Inasafe panel.
![logo](https://cloud.githubusercontent.com/assets/10434570/9580549/834109a6-4ffa-11e5-9cca-30e91a86ce65.png)

But the logo does not change in the pdf report.
![logo3](https://cloud.githubusercontent.com/assets/10434570/9580584/a6af4dda-4ffa-11e5-9149-ee8c2a3147ea.png)

# Environment
Windows 8.1 (64bit)
QGIS 2.8.3 (64bit)
Inasafe 3.2.0

**Comment by ismailsunni** [comment]
Hi @roscoeKartoza can you check it in you computer now (after pull from develop). Pleas re-open if it's not fixed yet.

Thanks
