### ISSUE TITLE
Minimum Needs Manager: Missing Tree

### ISSUE THREAD

**Issue by roscoeKartoza** [AIFDR/inasafe#2302]
# Problem
The file dialog in the minimum needs manager is not displaying icons in the tree panel on the left when the 'Import' and 'Export' buttons are clicked.

![file_dialog](https://cloud.githubusercontent.com/assets/10434570/9581362/5ef5e3c8-4fff-11e5-9e8a-1e6b94447555.png)

# Environment
Windows 8.1 (64bit)
QGIS 2.8.3 (64bit)
Inasafe 3.2.0

**Comment by ismailsunni** [comment]
I try in Ubuntu 14.04, looks good
![selection_054](https://cloud.githubusercontent.com/assets/1421861/9582615/ae8eef16-5030-11e5-9f87-12a17f371921.png)

Can you check it in Windows @lucernae

**Comment by lucernae** [comment]
![image](https://cloud.githubusercontent.com/assets/831865/9593891/b9876fbc-507e-11e5-8d57-4a79a58c05de.png)

Looks good. Export, import, save as, all looks like this

Windows 10 64 bit
QGIS 2.10 (64bit)
Inasafe 3.2.0

Maybe @adissadis can check it too?

**Comment by samnawi** [comment]
![image](https://cloud.githubusercontent.com/assets/8871958/9595008/4293f92a-508d-11e5-8f7d-5f56617a7c0b.png)
Looks very well

Windows 7 64-Bit
QGIS 2.8.3
InaSAFE 3.2.0

**Comment by adissadis** [comment]
Looks good in me:

![image](https://cloud.githubusercontent.com/assets/2520159/9595058/1b81840a-508e-11e5-9b74-1822c51f704f.png)

Windows 7 64-Bit
QGIS 2.8.3
InaSAFE 3.2.0

**Comment by Charlotte-Morgan** [comment]
hmm - try changing windows version :)

**Comment by Charlotte-Morgan** [comment]
@roscoeKartoza 
closing this as no one can replicate. Please reopen if it remains an issue
