### ISSUE TITLE
Website: needs intro text for realtime and user map

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2305]

**Comment by timlinux** [comment]
> We run near realtime earthquake impact assessments following recent earthquakes in the Indonesia region. Shakemaps of earthquake ground shaking are produced by the Indonesian Agency for Meteorology, Climatology and Geophysics (BMKG) and used by the Indonesian National Disaster Management Agency (BNPB) to produce InaSAFE impact assessments within minutes of an earthquake.

and

> We have added a community map to our web site. Please take a moment to register yourself there as an InaSAFE User, Developer or Trainer! It will help us a lot to see who our users are and where they are located. The map is built using the opensource Leaflet javascript library and uses the OpenStreemap .org Humanitarian Openstreetmap Style

(taken from staging.insafe.org)
