### ISSUE TITLE
Wizard Terminology

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2312]
# problem
we do not have consistent naming for the wizard - tool tip, window header and tool title bar say different things 

Tooltip says "Impact Function Centric Wizard" - good
Wizard window says "Impact Function Centric Wizard" - good
Tool title bar says "Guided impact assessment wizard" - confusing

![image](https://cloud.githubusercontent.com/assets/5743135/9648702/8731ae40-5215-11e5-95bd-96820e0da97b.png)

Tool title bar could say "Use this wizard to run a guided impact assessment"

# cc
@adissadis

**Comment by ismailsunni** [comment]
+1 for the new sentence. I will update it.
