### ISSUE TITLE
UI: We need consistent user facing terminology

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2313]
We have made some massive steps in developing terminology to help users understand their data and the impact functions but we still have a bit of 'geek speak' that may not make sense to users.

I propose we tweak the words so that user facing terminology is consistent and may not be the same words used by developers in the code. This should have no impact on code or how things work.

I propose that we match the question asked in the KW wizard with the keywords report in the dock
that we match the metadata and training materials too :)

Below is a sample of the current wording and the proposed wording for 3 examples. there are also minor changes to order of items in the dock report.

Why - I think it will make the link between steps in the KW Wizard and the key words more intuitive and make it easier to write training materials

![image](https://cloud.githubusercontent.com/assets/5743135/9649523/465ff29a-5220-11e5-9811-5f48f9668f13.png)

# cc
@samnawi @fredychandra @iyan31 @adissadis

**Comment by ismailsunni** [comment]
Hi, we can do it by simply changing the name value of each item in definitions.py

**Comment by Charlotte-Morgan** [comment]
oh - so i can do this. but @timlinux could change the order in the dock?

**Comment by samnawi** [comment]
I've been tried to create the keyword wizard diagram.
It's like as flow chart which could guide to user to know about the whole process in the keyword wizard.
![selection_162](https://cloud.githubusercontent.com/assets/8871958/9653765/14789716-5250-11e5-8eb1-75845c5b4cea.png)

# cc
@Charlotte-Morgan @iyan31 @adissadis

**Comment by ismailsunni** [comment]
Hi @samnawi 
Before creating the wizard, @borysiasty @timlinux and I also had a discussion about the workflow. And we created a similar diagram like yours for the wizard also.

Do you remember where do we put it @timlinux @borysiasty ?

**Comment by timlinux** [comment]
Hmm - Borys made his in a desktop UML app I think - We also made a version which is here:

https://www.lucidchart.com/invitations/accept/463ccb7f-6494-465e-95eb-832bd4722f67

**Comment by timlinux** [comment]
I just discussed this with @Charlotte-Morgan  - what we are going to do is:

* @Charlotte-Morgan is going to ensure that the ``name`` field in definitions.py are consistent with the terms that she would like to see used
* @timlinux will update the keywords table generator so that it looks up the names instead of showing the keys with underscores removed
* @ismailsunni (really sorry to throw last minute translations at you) to update translations for changed names in definitions.py

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni @timlinux - I don't think that the terms I plan to change are in definitions.py or wizard_strings.py (eg value_map). I am not making any edits until you can confirm the correct file.

**Comment by ismailsunni** [comment]
Thanks @Charlotte-Morgan 

@timlinux  I just look at the code, it's a little bit different, and needs to do some code in the dock.

Example:
Layer Purpose, see the definitions in https://github.com/AIFDR/inasafe/blob/231c826bd4c61966734ac61c58e3226d8dccca86/safe/definitions.py#L68

After I check, we haven't use this layer_purpose definitions anywhere. So, by changing its name will not make any difference.

Short solution:
We need to update `show_generic_method` in https://github.com/AIFDR/inasafe/blob/231c826bd4c61966734ac61c58e3226d8dccca86/safe/gui/widgets/dock.py#L1517
We do the ordering in this method also. But, we still use the raw term (the one that use underscore) to show the keyword in this method.
One solution perhaps, create another list to list the human friendly term in the method, or connect the definitions in definitions.py to the current list, and access the name from the connection.

I hope it's clear.

**Comment by timlinux** [comment]
@Charlotte-Morgan and @ismailsunni 

My preference for undefined terms is that we simply add them to definitions.py as new terms..that way we collect all terms in one place and make it easy to review them later.

@ismailsunni I have been updating the ```show_generic_keywords``` method to read from definitions.py nicely and show the name rather than the keyword as read from the metadata file. The updates I am making will fail gracefully if there is no definition and simply show the key name capitalised and with underscores removed as before.

I hope that makes sense.

**Comment by Charlotte-Morgan** [comment]
@timlinux 
ok - makes sense. i will proceed with edits to definintions.py by tweaking names for existing terms and creating new terms with names (will need @ismailsunni to check this for me)

**Comment by borysiasty** [comment]
@samnawi, my diagram is here:

![wizard_workflow](https://cloud.githubusercontent.com/assets/1000043/9678867/d3e8b434-52e9-11e5-8dbd-de230a281b66.png)

**Comment by Charlotte-Morgan** [comment]
hehe - thanks @borysiasty - we don't want to scare the users :)
This is be really helpful for tracking the terminology & proposed changes

**Comment by timlinux** [comment]
OK check my income PR for an example of how to proceed (I added a stub definition for ```value_map```)

Before:

![screenshot from 2015-09-04 09 49 12](https://cloud.githubusercontent.com/assets/178003/9678928/4152f69c-52ea-11e5-945d-249541ad2057.png)


After:

![screenshot from 2015-09-04 09 47 52](https://cloud.githubusercontent.com/assets/178003/9678930/45d1de18-52ea-11e5-90cd-a4c7e1794f8f.png)


Addition to definitions.py

```
# General terminology and descriptive terms

value_map = {
    'key': 'value_map',
    'name': tr('Vector classes'),
    'description': tr(
        'Vector classes are used to group features with similar meanings. ')
}
```

**Comment by timlinux** [comment]
On one more thing @Charlotte-Morgan for consistency I think it would be good to use leading title case for names i.e.

```Hazard category``` in preference to ```hazard category``` or ```Hazard Category```

This is the rule we use for user interface labels throughout InaSAFE and will add a sense of cohesion....low priority on the maslow's hierarchy of needs though ...

**Comment by Charlotte-Morgan** [comment]
noted

**Comment by Charlotte-Morgan** [comment]
PR #2333 looks a bit like this
![image](https://cloud.githubusercontent.com/assets/5743135/9682670/1c064170-5333-11e5-9fe8-7c8496d6c79f.png)
![image](https://cloud.githubusercontent.com/assets/5743135/9682682/33b4c47c-5333-11e5-8c38-22093ed05d2c.png)

@timlinux - the order of items appearing in the dock table could still do with a tweak

**Comment by timlinux** [comment]
For ordering just let me know what you would like to change, no problem to do it

**Comment by Charlotte-Morgan** [comment]
we are thinking something like the same order the user assigns things with a few exceptions: 
- [ ] title , purpose, hazard, scenario, geometry, data type, units / attribute field, attribute value / volcano name ; source, date, url, licence, kw version
- [ ] title, purpose, exposure, geometry, data type, units / attribute field, attribute value  ; source, date, url, licence, kw version
- [ ] title, aggregation ... source, date, url, licence, kw version

@samnawi @adissadis - any comments - this relates directly to training materials

**Comment by samnawi** [comment]
@Charlotte-Morgan It's good.
For my propose about the order of table, maybe similar with the keyword step by step in the wizard.
i.e. Title, Purpose, Hazard, Scenario, Geometry, Data Type, Units, Source, URL, Scale, Date, License....

**Comment by timlinux** [comment]
@Charlotte-Morgan I would like to remove the release blocker label - we can continue making improvements post 3.3 release

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - i agree with the comment from @samnawi that the order still needs a tweak to completely align with the user experience.
Your call on whether you have time to do this now or next week :)

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - did you want to tweak the order for 3.2?

**Comment by timlinux** [comment]
Ok in the #2377 PR I set the order like this to match @samnawi's list:

```
        preferred_order = [
            'title',
            'layer_purpose',
            'exposure',
            'hazard',
            'hazard_category',
            'layer_geometry',
            'layer_mode',
            'exposure_unit',
            'continuous_hazard_unit',
            'source',
            'url',
            'scale',
            'license',
            'date'
        ]  # everything else in arbitrary order
```

Here is a little preview of how it looks:

<img width="394" alt="screen shot 2015-09-17 at 11 53 10" src="https://cloud.githubusercontent.com/assets/178003/9925257/72621594-5d33-11e5-9517-92b4c00f1ce3.png">


<img width="400" alt="screen shot 2015-09-17 at 11 53 24" src="https://cloud.githubusercontent.com/assets/178003/9925258/779c4516-5d33-11e5-991f-f21e83f0fe01.png">

**Comment by Charlotte-Morgan** [comment]
the top looks good
between unit and source - can we add attribute field, attribute values, classes, resample
...
then right at the bottom
...
source, url, scale, date, license, kw version

**Comment by samnawi** [comment]
It's good.

But, could we make some change in this stuff?
- **Field** (3rd row from bottom) changes to **Analysis Field**
- **Name field**, maybe we can change to **Object name** and the value is the name of the object (depend on the attribute)

I propose it, because maybe user will confuse about the word "field" in this part. 

Because, if I a new user in InaSAFE, maybe I have a think that all of field name in this part is have a relationship, whereas it not.

**Comment by Charlotte-Morgan** [comment]
hi @samnawi - i think we have already dealt with all this naming. The names we see are the names we use in the training materials and metadata. Lets leave the names as they are for now.
This final tweak was about the order.

thanks

**Comment by samnawi** [comment]
Ok @Charlotte-Morgan.

Thank you.

**Comment by timlinux** [comment]
Based on chat with @Charlotte-Morgan we will put classes after data type (internally called layer_mode) so revised version will be:

```
   preferred_order = [
            'title',
            'layer_purpose',
            'exposure',
            'hazard',
            'hazard_category',
            'layer_geometry',
            'layer_mode',
            'classes',
            'exposure_unit',
            'continuous_hazard_unit',
            'attribute_field', 
            'attribute_values', 
            'resample',
            'source',
            'url',
            'scale',
            'license',
            'date',
            'version'
        ]  # everything else in arbitrary order
```

I am also going to add some magic to present the attribute values in a more friendly way...

**Comment by Charlotte-Morgan** [comment]
what would a wizard be without some magic

**Comment by timlinux** [comment]
Here is the next iteration.....

<img width="418" alt="screen shot 2015-09-17 at 17 12 43" src="https://cloud.githubusercontent.com/assets/178003/9930661/7507d2c6-5d5f-11e5-877a-47cc82b44aea.png">

@Charlotte-Morgan I think I will go ahead and add that special rule for classes too (and move it up under ```data_type``` too) as I can't cope with the non human friendly text there :-P

**Comment by timlinux** [comment]
btw the bullets are there because the high / med / low could contain more than one value each....

**Comment by timlinux** [comment]
<img width="394" alt="screen shot 2015-09-17 at 17 26 43" src="https://cloud.githubusercontent.com/assets/178003/9930920/515840de-5d61-11e5-9fcb-fbcd83ae5ecb.png">


@Charlotte-Morgan how about this? Alternative option is this:

<img width="399" alt="screen shot 2015-09-17 at 17 28 05" src="https://cloud.githubusercontent.com/assets/178003/9930942/7d9075d6-5d61-11e5-87b5-4de491b7c76a.png">

I also added a rule to suppress the bullets if there is only one item in the value map....

**Comment by timlinux** [comment]
Here is a little video showing the keywords rendered for each of the standard test datasets:

https://youtu.be/SJVmzJfgRLA

**Comment by Charlotte-Morgan** [comment]
LGTM - one final tweak :)
in aggregation can you rearrange so that logical pairs are adjacent. ie
youth attribute
youth default
adult attribute
adult default
elderly attribute
elderly default
female attribute
? female default (not there now)
