### ISSUE TITLE
BUG : Detailed information in the report is truncated

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2321]
# Problem
When I and @fredychandra was doing systematic test to InaSAFE, one of a bug that we're found is truncated information in the report.

# Detail
![selection_164](https://cloud.githubusercontent.com/assets/8871958/9655009/a401ac08-5258-11e5-97c8-124d02ec7e74.png)
![selection_168](https://cloud.githubusercontent.com/assets/8871958/9655067/da45aa62-5258-11e5-8a05-a04a60197cc3.png)

# Where is the bug found?
Mostly, the bug is found in IF hazard VS Road/structure
![selection_169](https://cloud.githubusercontent.com/assets/8871958/9655093/07931ac2-5259-11e5-8e93-d9c85464bba6.png)

# Proposed Solution
Fixed it with paper size, or maybe we can hide the "zero" result or something like that.
Make it happy.

# CC
@timlinux 

Thank you

**Comment by timlinux** [comment]
See also #2320 - we should work to remove superfluous columns from the report

**Comment by cchristelis** [comment]
This has been fixed by PR https://github.com/AIFDR/inasafe/pull/2345

**Comment by samnawi** [comment]
@cchristelis Could we re-opened this issue?
Mostly the truncated issue that I found and present like in the picture in above has done.
But, I still found the truncated issue that I found in the Flood hazard (both of vector and raster) VS roads.

This is the sightings
![selection_196](https://cloud.githubusercontent.com/assets/8871958/9846131/2ac8fe54-5afa-11e5-92c8-5e16118f7cd6.png)

Thankyou

**Comment by Charlotte-Morgan** [comment]
hi @samnawi - agree there is still a truncation issue. However this is because there are too many columns and not related to 0 values. 
I think this is fixed - lets write a new ticket for 3.3. cross reference to this & then close this ticket
