### ISSUE TITLE
BUG : Layer order of the impact result in the map

### ISSUE THREAD

**Issue by samnawi** [AIFDR/inasafe#2322]
# Problem
When we're doing some testing, we found that the layer impact in the result sometimes in the above, sometimes in the bottom of the result. Apparently, if occur because of the selected layer in the table of content.

1.If there is no layer that selected, the result automatically will appear in the above of all layers. 
![selection_170](https://cloud.githubusercontent.com/assets/8871958/9655831/20d46928-525e-11e5-8de7-0d26196b51af.png)

2.But, if the user click a layer in the table of content, the result automatically will appear in the above of the selected layer. If the position of a layer that selected is in the bottom of exposure layer, so the result will not show in the map.
![selection_172](https://cloud.githubusercontent.com/assets/8871958/9656192/b14efe62-5260-11e5-9fa4-d77e53b81f4a.png)

# Proposed Solution
Could we make the result of the impact function always appear on top of all layers, altough there is layer that selected as the example in above?
Make it happy.
 
# CC
@timlinux 
@Charlotte-Morgan 
@fredychandra 

Thank you.

**Comment by timlinux** [comment]
So I will add some logic to always insert the impact layer 1 layer above the exposure layer.
