### ISSUE TITLE
 IFCW has a great error message

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2334]
nice - first time ive seen this
![image](https://cloud.githubusercontent.com/assets/5743135/9682848/a72201e4-5334-11e5-98f2-d21966c948a0.png)

**Comment by timlinux** [comment]
@Charlotte-Morgan glad you like the error message!

Is there some action that needs taking in order to close this issue?

**Comment by Charlotte-Morgan** [comment]
No action.
I started a bug ticket, then realised it was a bug. No way to delete tickets you write in error. 
I'll close this now - no action required.
