### ISSUE TITLE
Get last shake event id in realtime doesn't count timezone probabilities

### ISSUE THREAD

**Issue by lucernae** [AIFDR/inasafe#2340]
Currently, after all this time, elapsed time in generated pdf report always shows 7 hours ago.
It turns out that it wasn't a timezone issues with the elapsed time, the report actually generated 7 hours after the shakemap from BMKG was received.
The problem lies when trying to get the last shake event id of the folder. It is calculated using ```datetime.now()``` which returned a datetime object for the current timezone. Because inasafe docker is in UTC and the shakemap id is in UTC+7, it still thinks that the new shakemap is not the last (because it is in the future 7 hours later).

The proposed solution is to always get the biggest shake id for the last shake event.

**Comment by timlinux** [comment]
I think we had problems in the past where the wrong time stamps were being set in the grid and so we needed up with quakes in the future...but I think your approach is good and we rather deal with upstream inconsistencies via BMKG.

Thanks

Tim
