### ISSUE TITLE
EQ Realtime: remove AIFDR reference

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe#2342]
We need to update the Realtime report to remove reference to AIFDR.

replace 'population data derived by AIFDR from worldpop....." with 
'population data derived by Australian Government from worldpop ..."

replace 'supported by Australia - Indonesia ....... and World Bank - GFDRR" with 
'Supported by Australian Government ..... and World Bank- GFDRR"

hope this makes sense

**Comment by Charlotte-Morgan** [comment]
@lucernae - is this under control?

**Comment by lucernae** [comment]
Will do it, but I think we will just let the old report be?

**Comment by Charlotte-Morgan** [comment]
please see comment for exact wording.
Old reports are fine to stay as they are.
