### ISSUE TITLE
InaSAFE produce a lot of 'safe_ag' columns in generated output 

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe#2357]
# Problem
When i run InaSAFE for flood raster with building and i checked the attribute, i found that the output produced lot of 'safe_ag' columns such as safe_ag_1, safe_ag_2, safe_ag_3, ..., safe_ag_16. I think it should produced only one column which is only safe_ag column to explain whether the building wet, inundated or dry. 

From my experience, it produce 'affected' column or 'inundated' column and now changed into 'safe_ag' column.

# Screenshot
![result](https://cloud.githubusercontent.com/assets/2520159/9815015/234be112-58bd-11e5-99b6-a3c34757fbc1.png)

# System operation
Windows 7 64 bit with QGIS 2.8 and InaSAFE 3.2

**Comment by samnawi** [comment]
@adissadis I also found somethings like you when I run Flood Raster Vs Building.  It's produce lot of safe_ag column in attribute table. Actually, in the realease version (3.1.3), the column name in attribute table is INUNDATED.

But, I also found it in the other **raster hazard Vs vector exposure** (i.e. Tsunami (R) Vs Building (V), Tsunami (R) Vs Road (V), EQ (R) Vs Building (V), etc), but it just produce one column "safe_ag".

EQ Raster VS Building
![selection_187](https://cloud.githubusercontent.com/assets/8871958/9841040/da5f9a66-5ac4-11e5-829b-fd56db199c8e.png)

Tsunami Raster VS Roads
![selection_191](https://cloud.githubusercontent.com/assets/8871958/9841053/055d1f2c-5ac5-11e5-8dbb-77c704646f11.png)

I Just found Flood Raster VS Buildings that produce lot of "safe_ag" in the attribute.

# CC
@Charlotte-Morgan

**Comment by samnawi** [comment]
Apparently is not a bug.
@timlinux ask me to check the exposure data, and apparently the safe_ag1, 2, 3..... come from the buildings data.
It's my mistake not to check the data first before use it.

Thank you.

**Comment by timlinux** [comment]
Ok so I reviewed this issue with @samnawi and I believe it is only a data issue - the original input data set has all these extra ``safe_ag`` attributes. I am not sure if the ``safe_ag`` columns were added to the data explicitly for a test, but for now I would suggest to simply remove them.

A separate issue is the naming of the 'affected' column - @samnawi is going to compile a list of preferred column names in a separate issue.

**Comment by akbargumbira** [comment]
This is my signature :) https://github.com/AIFDR/inasafe/blob/2823beb685b4e9ff49aa3b5e8cdfc0d459fada61/safe/impact_functions/base.py#L83

When making vector impact layer, InaSAFE creates one extra column to mark the analysis output of each feature. This extra column is unique. You probably use the impact layer as exposure layer over and over again. The first impact layer will create one safe_ag column. The next analysis, if you set this impact layer as exposure layer, it will create safe_ag_2, and so on. 

This field is supposed to be overrided by each IF to represent a better name according to the IF. E.g for Flood IF, probably 'inundated' is the best name.
