### ISSUE TITLE
Typo on inasafe_en.ts?

### ISSUE THREAD

**Issue by kant** [AIFDR/inasafe#2407]
On string # 1299 
"The minimal threshold is greater then the maximal specified threshold. Please check the values." 
it should not be 
"The minimal threshold is greater than the maximal specified threshold. Please check the values."

**Comment by ismailsunni** [comment]
hi @kant 
It seems both of your strings are the same. Perhaps you made a typo?

Thanks

**Comment by kant** [comment]
There is a little difference. Look at "is greater then" and my proposal: "is greathen than"
