### ISSUE TITLE
Keywords wizard should not offer to use impact layer as hazard

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#2414]
While showing InaSAFE to @akbargumbira the other night we were playing with the wizard and noticed that it will try to use the impact layer from a previous analysis as a possible hazard layer. Here is a screen sequence to illustrate:

<img width="1021" alt="screen shot 2015-09-24 at 09 41 16" src="https://cloud.githubusercontent.com/assets/178003/10064264/ce65e5ce-62a0-11e5-9ac8-207887ab4806.png">

<img width="1021" alt="screen shot 2015-09-24 at 09 41 26" src="https://cloud.githubusercontent.com/assets/178003/10064426/7051d4f0-62a2-11e5-95c8-f1569bf90492.png">

<img width="1024" alt="screen shot 2015-09-24 at 09 41 50" src="https://cloud.githubusercontent.com/assets/178003/10064430/7d888812-62a2-11e5-8536-eba5920e2fbc.png">

<img width="1021" alt="screen shot 2015-09-24 at 09 42 01" src="https://cloud.githubusercontent.com/assets/178003/10064435/85c8f30e-62a2-11e5-8206-e4c4efccc774.png">

<img width="1021" alt="screen shot 2015-09-24 at 09 42 14" src="https://cloud.githubusercontent.com/assets/178003/10064437/8b4e003a-62a2-11e5-96cd-4427c265404b.png">

On the last screen you can see that it fails to load the impact layer keywords and wants to offer the user the chance to use this layer as a hazard layer, registering keywords in the process.

I could see in some distant future where we may want to rerun an analysis using the impact layer as the exposure layer, but I don't see it ever making sense to offer it for use as the hazard layer. **For the short term though I want to suggest that you simply do not offer impact layers as either hazard or exposure candidates to the user in the wizard workflow.**

**Comment by borysiasty** [comment]
@timlinux what is the best keyword to detect the layer is an impact layer? I'm thinking about one of those three:

 - impact_summary
 - postprocessing_report
 - elapsed_time

Probably the first one, if it's not going to be changed soon.

**Comment by Charlotte-Morgan** [comment]
@borysiasty the keywork for any analysis output layer should be impact summary.
This aligns with our terminology in training materials.
