### ISSUE TITLE
Need tool to merge building footprints with building points

### ISSUE THREAD

**Issue by uniomni** [AIFDR/inasafe#276]
Kristy and Trias brought this up:

Currently, OSM building data comes as either footprints (when digitized) or point data (when collected on the ground). The attributes are the same but geometries obviously different.

The suggestion is providing a tool that will merge multiple vector layers (polygon or point) into one point  geometry. The script should complain if the attribute names are not the same.

We'll do this in two stages: 
1. Ole will write the function and expose it as a command line tool
2. Someone else will make the QGIS gui within InaSAFE exposing this functionality.

But first we need the data in the test area

**Comment by akbargumbira** [comment]
@Gustry can you confirm that if we download the building points from the OSM downloader, the buildings polygons will be converted to its centroid? If so, we can close this

**Comment by timlinux** [comment]
@akbargumbira yes the OSM downloader will fetch buildings centroids as an option now.
