### ISSUE TITLE
Need to decide whether to use FLOODPRONE attribute or not

### ISSUE THREAD

**Issue by uniomni** [AIFDR/inasafe#404]
Currently, the flood OSM building impact function is using an attribute called FLOODPRONE as the default for hazard polygon data.

However, for e.g. forecasts we set the more generic attribute Flooded to True or False depending on the predicted grid. In addition, we have a convention that any element covered by a polygon gets the attribute Affected set to True. 

I have modified the current incarnation of this impact function to first look for Flooded, the Affected and finally for FLOODPRONE. But this is very messy.

What do you think?

**Comment by akbargumbira** [comment]
I am closing this. For 3.1 release, we remove the old style IF and use the QGIS-IF. This IF will ask for an attribute that represent the affected and the value of affected e.g the affected field is FLOODPRONe and the affected value is YES
