### ISSUE TITLE
impact function browser

### ISSUE THREAD

**Issue by lianarazafy** [AIFDR/inasafe#439]
Using the v1.0.1, I could not really make sense of what the "Impact function browser" will give me as an end-user. I knew what it was for from discussions with Ole and Tim but by myself I don't think I would have guessed how I should use it and how it can help me in my analysis. 

Some documentation might be helpful...

Also once I choose my filters and get some idea of the impact tool I need to use, I am not sure what I should do next (closing the browser, getting back to the Inasafe panel, and choose/correct the impact function I need to use). This is not intuitive as one might expect more from the browser. 
Just some ideas: what about linking the listed impact function to the MIGHT box of the Inasafe panel for example?

**Comment by timlinux** [comment]
OK So I am reassigning this to @ismailsunni with the following actionable tasks:

-[] Implement link or button on each IF row that will change context to full details for that IF (please use a widget stack or something so that we don't get another popup
-[] Implement context help explaining how the IF browser is intended to be used

Note that all IF metadata should be based on the new rich metadata  system.

**Comment by timlinux** [comment]
Actually on further discussion we are proposing to drop the IF browser and move filtering functionality into the wizard. @charlotte-morgan as client of course you are welcome to veto this if you see a good point in keeping it around.

**Comment by Charlotte-Morgan** [comment]
hi @timlinux 
While i agree the IF browser has not delivered the desired outcome for users, and i agree that it should be 'retired'; i would like to firstly show some appreciation for the people who designed and built it in the first place and secondly offer some thoughts on why it may not have been as successful as planned.

So - thank you to all who worked on it and delivered what was required at the time.

As to why I found the IF browser difficult to use. I think that its a matter of terminology; the browser uses words that users are not familiar with.

I agree that filtering in the wizard is a good way to go; but I would like some lessons to be learned from the IF browser & for us to look at using different terminology when we apply filtering in the wizard.  I will offer some suggestions in other tickets.

#1482 
#1489 

@adissadis @ismailsunni @borysiasty @timlinux
