### ISSUE TITLE
QGIS Training Manual - Content Adaptation and Reduction

### ISSUE THREAD

**Issue by takmid** [AIFDR/inasafe#495]
4) QGIS Training Manual - Content Adaptation and Reduction 

Trias to take the lead in this.

* Make localised BI datasets that accompany translated tutorial persistently and publicly available (Tim to suport with this).
* Investigate whether it is worth auto generating a reduced version of the training manual with just the training relevant elements in it.

**Comment by timlinux** [comment]
Closing this as stale
