### ISSUE TITLE
Aggregation, difference between "zero" and "no data"

### ISSUE THREAD

**Issue by Riangga** [AIFDR/inasafe#501]
We are doing a tsunami model with population.
the aggregation of desa (viillage) level is correct.

however two of a villages got "no data" value.

is it a problem or not, because it should be zero.

![TsunamiMaumere_NoData](https://f.cloud.github.com/assets/2775194/144229/8e54e1b4-7401-11e2-8a97-5e55f2677201.jpg)

**Comment by cchristelis** [comment]
I have been struggling to re-produce this as I don't find this data-set. It seems like there is 'no data' in the attribute table to begin with and hence carried forward. 
Either as long as this cannot be reproduced, it can't be said for sure whether this is still a problem.

**Comment by cchristelis** [comment]
This is expected behavior for no data.
