### ISSUE TITLE
InaSAFE impact function configuration

### ISSUE THREAD

**Issue by vanpuk** [AIFDR/inasafe#504]
I would like to see more information about how this 'Threshold' works, my main concern is that it would be nice for the "Flood Evacuation Function" to tell you that the last number you put in will be the people evacuated.  And also how to put in multiple number "03;05;1" or is it "0.3,0.5,1"

**Comment by timlinux** [comment]
In 3.2 we use new parameters UI which makes parameter selections much clearer. @charlotte-morgan will also be doing a separate review of text used in InaSAFE.
