### ISSUE TITLE
Impact function modified - polygon hazard, population density

### ISSUE THREAD

**Issue by vanpuk** [AIFDR/inasafe#522]
It would be benefical to modify all impact functions with a polygon hazard and population density so that the output data (the impacted layer) is the same as the exposure layer, i.e. raster.
Benefits:
This will allow consistency - all output layers are the same spatial unit as the exposure
The current aggregation function will work (raster output).

**Comment by akbargumbira** [comment]
I have implemented this one https://github.com/AIFDR/inasafe/pull/1871. All the IF's that basically work on polygon hazard and raster exposure will return the raster exposure (with some modification). Those IF's are:
- Classified Polygon on Population
- Volcano Point on Population
- Volcano Polygon on Population
- Flood Polygon on Population

The impact layer will return the population layer with some modification:
- For Classified Polygon on Population, Volcano Point/Polygon on Population, the impact layer grids values will follow this rule: If the grid covered by polygon, the grid will be assigned the pops grid value. If it's not covered, the grid will be assigned no data value (see interpolate_polygon_on_raster)
- For Flood Polygon on Population, the impact layer grids values will follow this rule: If the grid covered by polygon AND match the parameters (value in the affected field == affected value), the grid will be assigned the source population grid. If it's not covered, the grid will be assigned no data value. If it doesn't match the criteria in the parameter, it will be assigned 0
