### ISSUE TITLE
Functions for generic categorized vector hazard layer and building

### ISSUE THREAD

**Issue by vdeparday** [AIFDR/inasafe#532]
I talked about it with @vanpuk and @uniomni  during the last call so I am creating an issue to record it.

From my experience so far, the most common use case I have been encountering are agencies who have hazard layers that are categorized. They can be any hazard (flood, tsunami,  inland erosion, costal erosion, storme surge, wind, waves, drought..) but all of their layers are basic shapefile categorized with 3 or 5 categories (very low, low, medium, high, very high).

So far, I have been recommending the work around of rasterizing the layer as there is a basic function that deals with (despite issue #531). But ideally it would be better to make it work with vector layer. Then more detailed output could be added too.
I haven't looked at the population exposure case yet but I expect there will be the same needs.

I will try to take a stab at it in the next couple weeks using the volcano function as an example as recommended by @vanpuk .

**Comment by akbargumbira** [comment]
Gladly, we have this for 3.1. The IF will ask the attribute that contains the hazard areas. The result will show all the buildings affected for all unique hazard areas. There is also another IF that works on population. You can make another ticket if you have other ideas on the current state of those IF's. I am closing this.
