### ISSUE TITLE
Use name of volcano for volcano impact function

### ISSUE THREAD

**Issue by ismailsunni** [AIFDR/inasafe#541]
There is (previously) a parameter for volcano name when we want to run volcano-analysis. But, it seems, it does not work (so I remove it). It will be great if we can use this name of volcano as a paramater.

**Comment by akbargumbira** [comment]
I am not clear with the intention here. We do have a parameter to get the attribute in which we get the volcano name. Or from Ole's comment, does it mean that we should have another attribute to specify what volcano (from volcanoes layer) that we want to run (if it's left blank, it will run all of the volcanoes)?

**Comment by timlinux** [comment]
Hi @akbargumbira 

I think their intention was that you can enter 'Merapi' in the options dialog and that would then be propogated to the report etc. For me there are flaws in this idea:

* the name should come from an attribute rather
* it assumes only one volcano feature ever exists in the shapefile

I think it is superceded by having the volcano name attribute in the IF parameter so I am going to close this out.
