### ISSUE TITLE
Volcano impact function that process & output layer is based on exposure layer

### ISSUE THREAD

**Issue by uswatunkh21** [AIFDR/inasafe#554]
# Problem
>   Ketika saya melakukan analisis InaSAFE untuk bencana gunungapi, layer yang menjadi output adalah layer hazard, bukan layer exposure (padahal seharusnya yang menjadi diproses & output adalah layer exposure).

When I ran InaSAFE analysis for volcano, the output layer is hazard layer, not exposure layer (whereas the one that must be processed and become the output is the exposure layer)

# Expected Result
>    Layer terdampak (yang menjadi output) seharusnya adalah layer exposure.

Impact layer (the output) should be an exposure layer

**Comment by akbargumbira** [comment]
As of now, for the impact on building, we already have the exposure as the impact layer, but not yet for population

**Comment by akbargumbira** [comment]
Right now, the volcano IF's will return the exposure layer (works for population and building exposure). Closing this
