### ISSUE TITLE
Building Impact function (Break down for buildings)

### ISSUE THREAD

**Issue by Riangga** [AIFDR/inasafe#598]
# Problem 
No Break down building (type of building such as hospital, school, university, etc)

# Proposed Solution

for another building impact function, follow Jakarta Flood to show break down building. Currently there is only Building in Jakarta shown the break down building

# Expected Outcome
The same break down as Jakarta Flood Hazard for buildings

# Notes

I have clarified the requriements here. @vanpuk  do you have any specific thoughts on how we should present the building breakdown? We are proposing to do:

```
Hazard Level    Buildings Affected
Low 0
Medium  0
High    898
```

and then below breaking out each hazard level into sub tables which list the breakdown of buildings affected per builing type for that hazard level. e..g:

```
Low Hazard:
  Churches: 10
  Schools 3
High  Hazard:
  Residential: 800
  Schools: 3
etc.
```

Where a hazard level has no affected buildings it will be left out of the details table.

@Riangga can you also confirm that this is what you have in mind?

**Comment by cchristelis** [comment]
I had a look at using the work I had previously done on this, but the branch is not really merge-able anymore.

**Comment by cchristelis** [comment]
This has been fixed in the Reporting Mixin update.
