### ISSUE TITLE
Problem with InaSAFE translation

### ISSUE THREAD

**Issue by vanpuk** [AIFDR/inasafe#629]
# Problem
Just started to play with the new version of InaSAFE (1.2.0-8) and swapped into Bahasa Indonesian the front page "Getting started and Limitations" is still in English

# Solution
Translate "Getting started and Limitations" - check that the translation link is not broken.

**Comment by akbargumbira** [comment]
Closing this, not relevant anymore (@timlinux is still working on the translation refactor though)
