### ISSUE TITLE
Keyword translation

### ISSUE THREAD

**Issue by vanpuk** [AIFDR/inasafe#630]
# Problem
When viewing InaSAFE in bahasa the keywords are shown in English and Bahasa.

# Solution
Only show the language that QGIS is in. 

![screen shot 2013-08-08 at 3 29 07 pm](https://f.cloud.github.com/assets/1421818/930194/a18a94d8-0004-11e3-8766-2a57d4977994.png)

**Comment by lucernae** [comment]
I think this is already resolved.

![image](https://cloud.githubusercontent.com/assets/831865/7283908/10c3d054-e964-11e4-972e-1c6759877c2d.png)
