### ISSUE TITLE
RFC Implement a robust resampling regime for density data

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#689]
# Problem

Currently we do not have a decent way of resampling density data (e.g. population per cell) and thus place an artificial restriction on InaSAFE to have density  in EPSG:4326.

In our current implementation, everything gets reprojected / resampled to EPSG:4326 during the clipping phase. Because of this, we do no support density data in other CRS's and all subsequent analysis assumes that we are in EPSG:4326.

In the new QGIS API, there is support for 'save as' of rasters and an API for this functionality. However there is no capability of choosing the resampling regime. For density data we need

* **down sampled** pixels to have the sum of the contained pixels from the original dataset, 
* and the proportional value of the intersected pixels to be assigned to **upsampled pixels**

The following images illustrate the basic resampling approach we are looking for:
![rasterresamplingrequirements](https://f.cloud.github.com/assets/178003/1331126/f0ddcf82-3547-11e3-9f15-a30f26424581.png)

![rasterresamplingrequirements2](https://f.cloud.github.com/assets/178003/1331128/03056d00-3548-11e3-8dbb-f3021c93edbc.png)

There are other scenarios we need to deal with:

* dealing with rectangular pixels
* dealing with rasters in difference CRS's
* dealing with rasters containing density data and not counts

Other resampling options could be handy e.g.:

* SUM (as above)
* AVG
* MAX
* MIN
* MEAN
* MODE

We also envisage having a slider metaphor in the ``save as`` dialog of QGIS whereby a user can use humanistic values for resampling e.g.

![screen shot 2013-10-15 at 10 09 55 am](https://f.cloud.github.com/assets/178003/1331158/587a2cc0-3549-11e3-9d38-592420da996d.png)

At run time we would use this extended API directly from within the impact function to retrieve the Area of Interest (AOI) block directly from the QGIS raster provider as a numpy array at the preferred scaling (e.g. relative 2* or absolute 100map units) and using the preferred resampling algorithm (e.g. SUM).

# Proposed solution

- [ ] Create a small contract with Radim Blazek (architect of the new raster system in QGIS 2) to implement support for different resampling strategies (@timlinux to organise this in collaboration with @vanpuk). This work should be made available as part of QGIS 2.1
- [ ] @KolesovDmitry  to update the 'new style' impact functions to support the workflow as described above.

# Expected outcome

An eventual outcome of this work would be to:

* include new resampling options in raster ``save as`` dialog in QGIS 2.1
* support reprojection and scaling of density data
* carry out InaSAFE analysis in any CRS

# See also

#123 
#52
#391
#74

# CC

@KolesovDmitry 
@ingenieroariel 
@vanpuk

**Comment by wonder-sk** [comment]
Done: functionality merged to experimental branch, needs QGIS 2.12 (or current development version).

See also:
- RFC: Align Rasters Tool #1998
- PR: Align raster layers using QGIS functionality #2070
