### ISSUE TITLE
Backport Impact functions to support all QGIS native input layers

### ISSUE THREAD

**Issue by vanpuk** [AIFDR/inasafe#707]
# Problem
With the introduction of QGIS native intputs into impact functions, we want to ensure that all impact functions are able to accept the native and produce a native output.

# Solution
That each individual Impact function is checked to ensure it can use QGIS native input layers.

# Source
Tim, Charlotte and Kristy ticket clearing session on the 23 Oct 2013

**Comment by akbargumbira** [comment]
I am closing this. We can pass to all Impact Function QgsMapLayer. The IF's will handle the converting by itself.
