### ISSUE TITLE
Qt strings need translation

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#772]
# Problem

The Qt user interface elements (e.g. close button) are not being translated

# Proposed solution

Werner can we make a qt translation file for Bahasa Indonesia and get the HOT team to do the translations in time for the release?

# Expected outcome

Qt native elements of the dialogs should also appear in Bahasa Indonesia.

**Comment by mach0** [comment]
@timlinux no solution for this so far as it is rather an upstream issue for QGIS
leave it or close it?

**Comment by timlinux** [comment]
Lets close this for now - we can come back to it if there is demand for native translation of Qt elements
