### ISSUE TITLE
Detailed aggregation categorical report

### ISSUE THREAD

**Issue by vanpuk** [AIFDR/inasafe#781]
# Problem
I dont understand the purpose of "Detailed aggregation categorical report" if aggregation was not defined.  Specifically in relation to earthquake.
![screen shot 2014-02-12 at 7 14 02 pm](https://f.cloud.github.com/assets/1421818/2148140/3c64ee72-93df-11e3-997b-ce165958146d.png)

# Solution 
Can the aggregation window be taken out if aggregation is "entire area"

**Comment by akbargumbira** [comment]
Can we open this again?
So, this is the workflow of running one postprocessor depends on its param:
![img_20150401_113939939_hdr](https://cloud.githubusercontent.com/assets/992519/6934882/72d97190-d866-11e4-845c-4bcc0c399aa0.jpg)

So as Kristy proposed the solution: 
"Can the aggregation window be taken out if aggregation is "entire area", I think it isn't necessary to add another param 'disable_for_entire_area_aggregation'. Why don't we just do:
- If no aggregation layer, the postprocessor tab is disabled (and we don't run all the postprocessor)
- If aggregation layer provided, look at the values (whether user wants to run it or not)

**Comment by mbernasocchi** [comment]
> If no aggregation layer, the postprocessor tab is disabled (and we don't run all the postprocessor)
I don't really agree with this, as there are postprocessors that make sense even with no aggregation.

**Comment by mbernasocchi** [comment]
I think: if we have non user aggregation layer then we can hide the postprocessors that don'T make sense

**Comment by akbargumbira** [comment]
Based on the discussion, I removed the 'disable_for_entire_area_aggregation_param'. All the postprocessors make sense for both aoi mode and with aggregation layer provided. If user doesn't want to see the postprocessor, (s)he can always disable it prior to running analysis.
