### ISSUE TITLE
We need to review code for direct usage of resources

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe#832]
# Problem

When using resources, application code should not try to access files from the filesystem, but should rather use files in the resource bundle.

For example:

https://github.com/AIFDR/inasafe/blob/develop/safe_qgis/tools/impact_merge_dialog.py#L82

# Proposed solution

Review all resource usage and make sure it is using ``:/`` style urls.

# Expected outcome

We should be able to ship InaSAFE packages without any resource folder (and all needed resources compiled into the resources.py

# CC

@akbargumbira 
@mbernasocchi

**Comment by akbargumbira** [comment]
Closing this. We are using file based resources now with a dynamic uic compilation
