### ISSUE TITLE
OSM downloader error

### ISSUE THREAD

**Issue by vanpuk** [AIFDR/inasafe#894]
# Problem 
Error Received on Mac - InaSAFE 2.0.4
# Solution
Fix error???

![screen shot 2014-03-19 at 8 12 27 am](https://f.cloud.github.com/assets/1421818/2455646/b4764002-af03-11e3-979a-383d11876bf4.png)

**Comment by timlinux** [comment]
@Gustry Can you look into this and close if you can't replicate. Please test when your project is using projected CRS.

**Comment by Gustry** [comment]
I can't replicate it.
With OTF enabled, it works.
With OTF disabled, I get 
``The bounding box is not valid. Please make sure it is valid or check your projection!``
@timlinux Should the OSM downloader allow to download if OTF is disabled, and then activate it ?
