### ISSUE TITLE
Possible optimization of raster flood on roads

### ISSUE THREAD

**Issue by assefay** [AIFDR/inasafe#906]
# Status
This is a draft RFC 

# Problem

Doing raster flood on roads takes a significant amount of time. It becomes even more compounded for raster with higher resolution

# Proposed solution

Review of the process and propose possible optimization.

# Initial tests

Modifying the way we "polygonize" and avoid some costly operations (union, clip), we can have a big improvement in terms of total time to accomplish the task.

Some initial figures on time when tested locally with Jakarta flood and OSM data:

* small region (106.86960330299968, -6.159488509883394, 106.95870407784028, -6.083051804563279) with about 2800 considered features, the same process would take 8.5s vs 1.5min with the current process

* on a medium size regions (about 6000 roads) ~33s vs ~4min

* on a large area (about 22000 roads) : 350s vs xxx (will update this value)

# Expected Outcome

An optimized version of raster flood or roads

**Comment by wonder-sk** [comment]
The speed of raster flood on roads was significantly improved in #2007
