### ISSUE TITLE
Kristy's Note on Keyword Wizard

### ISSUE THREAD

**Issue by akbargumbira** [AIFDR/inasafe#961]
Hi all,
I have started to make some suggestions about the wizard, they are only superficial, but thought it would be best to do it in a google doc then transfer the results to a git ticket when everyone is happy. 

To start with I love this tool!!!
Some suggestions for improvement:
- [x] Font size - its quite small, can it be a bit bigger
- [x] Explanation and UNOCHA icon - can the icon be on top then the text below, rather than side by side.
- [x] I tested tsunami raster hazard layer and when it came to units I was able to choose wet/dry but when I ran the scenario it still assumed it was meters. Maybe for rasters the wet/dry option should not be available.
- [ ] The wizard icon looks faded out even though it is active, can the black outlines be the same as the keyword icon
- [ ] I was wondering if we could explain why they can only select roads on this page, i.e. the dataset you have chosen is a line dataset, the only line exposure dataset InaSAFE recognises is roads.  
- [x] Also I think the explanation at the top of the wizard should instruct people to select one of the types in the white window, 
- [x] If there is only one choice could it be automatically selected?
- [x] In step 6 - What is “Scale” - will this have any impact on the impact function chosen.I think we need instructions per line, in the step. 
  - Source: Please record who is the custodian of this layer i.e. OpenStreetMap
URL: Does the custodians have their own website i.e. www.openstreetmap.org
  - Scale: ???
  - Date: When was this data collected or downloaded i.e. 1-May-2014
- [x] Should we say that step 6 is optional??? or indicated on all steps what is essential and what is optional???
- [x] Step 7 - title - can it be defaulted to the current layer name?
- [x] Volcano point hazard doesn't need choosing-unit step. Generally, we should revisit all IFs and see if we don't need some steps for some IFs.

**Comment by Charlotte-Morgan** [comment]
i think the road issue is not current any more?
maybe this can be closed

**Comment by ismailsunni** [comment]
yes, I think so. Closing this. If it comes up again, we can re-open this ticket.
